/* 
 * SAS code generated by JMP v16.2.0
 * From the following model(s): 
 *   Fit Generalized/Lasso - itype1
 * Variable name mapping: 
 *   Most Likely itype1,!Most Likely itype1 => Most_Likely_itype1_Most_Likely_
 *   Probability( itype1=Case ) => Probability_itype1_Case_
 *   Probability( itype1=Case ),!Probability( itype1=Case ) => Probability_itype1_Case_Prob
 *   Probability( itype1=Control ) => Probability_itype1_Control_
 *   Probability( itype1=Control ),!Probability( itype1=Control ) => Probability_itype1_Control_P
 *   original_firstorder_minimum_fc => original_firstorder_minimum_fc
 *   original_glszm_smallareaemphasis_fc => original_glszm_smallareaemphasis
 *   original_shape_elongation_lm => original_shape_elongation_lm
 *   original_shape_sphericity_mm => original_shape_sphericity_mm
 *   v455_fc => v455_fc
 *   v620_fc => v620_fc
 *   v810_mm => v810_mm
 *   wavelethhh_firstorder_minimum_fc => wavelethhh_firstorder_minimum_fc
 *   wavelethhh_glcm_clustershade_mm => wavelethhh_glcm_clustershade_mm
 *   wavelethhh_glcm_imc1_lm => wavelethhh_glcm_imc1_lm
 *   wavelethhh_glrlm_runvariance_mm => wavelethhh_glrlm_runvariance_mm
 *   wavelethhh_glszm_largeareahighgr_fc => wavelethhh_glszm_largeareahighgr
 *   wavelethhl_firstorder_mean_mm => wavelethhl_firstorder_mean_mm
 *   wavelethhl_glcm_clusterprominenc_fc => wavelethhl_glcm_clusterprominenc
 *   wavelethhl_glcm_correlation_mm => wavelethhl_glcm_correlation_mm
 *   wavelethhl_glcm_imc1_mm => wavelethhl_glcm_imc1_mm
 *   wavelethhl_glcm_imc1_tc => wavelethhl_glcm_imc1_tc
 *   wavelethhl_gldm_smalldependencel_fc => wavelethhl_gldm_smalldependencel
 *   wavelethhl_gldm_smalldependencel_mm => wavelethhl_gldm_smalldependence2
 *   wavelethhl_glrlm_longrunhighgray_mm => wavelethhl_glrlm_longrunhighgray
 *   wavelethhl_glszm_graylevelvarian_mm => wavelethhl_glszm_graylevelvarian
 *   wavelethhl_glszm_largearealowgra_fc => wavelethhl_glszm_largearealowgra
 *   wavelethhl_glszm_smallareaemphas_fc => wavelethhl_glszm_smallareaemphas
 *   wavelethlh_firstorder_median_lm => wavelethlh_firstorder_median_lm
 *   wavelethlh_glszm_largeareahighgr_tc => wavelethlh_glszm_largeareahighgr
 *   wavelethlh_glszm_zoneentropy_tc => wavelethlh_glszm_zoneentropy_tc
 *   wavelethll_firstorder_kurtosis_mm => wavelethll_firstorder_kurtosis_m
 *   wavelethll_firstorder_skewness_lm => wavelethll_firstorder_skewness_l
 *   wavelethll_glszm_graylevelnonuni_fc => wavelethll_glszm_graylevelnonuni
 *   wavelethll_glszm_largearealowgra_lm => wavelethll_glszm_largearealowgra
 *   wavelethll_glszm_smallareaemphas_fc => wavelethll_glszm_smallareaemphas
 *   wavelethll_ngtdm_busyness_mm => wavelethll_ngtdm_busyness_mm
 *   waveletlhh_firstorder_maximum_mm => waveletlhh_firstorder_maximum_mm
 *   waveletlhh_firstorder_median_lm => waveletlhh_firstorder_median_lm
 *   waveletlhh_glszm_smallareaemphas_mm => waveletlhh_glszm_smallareaemphas
 *   waveletlhl_firstorder_minimum_tc => waveletlhl_firstorder_minimum_tc
 *   waveletlhl_firstorder_skewness_fc => waveletlhl_firstorder_skewness_f
 *   waveletlhl_firstorder_skewness_tc => waveletlhl_firstorder_skewness_t
 *   waveletlhl_glcm_clustershade_fc => waveletlhl_glcm_clustershade_fc
 *   waveletlhl_glszm_zoneentropy_lm => waveletlhl_glszm_zoneentropy_lm
 *   waveletlhl_glszm_zoneentropy_mm => waveletlhl_glszm_zoneentropy_mm
 *   waveletllh_firstorder_minimum_fc => waveletllh_firstorder_minimum_fc
 *   waveletllh_glcm_correlation_mm => waveletllh_glcm_correlation_mm
 *   waveletllh_glcm_imc1_mm => waveletllh_glcm_imc1_mm
 *   waveletllh_gldm_smalldependencel_mm => waveletllh_gldm_smalldependencel
 *   waveletllh_glszm_zoneentropy_fc => waveletllh_glszm_zoneentropy_fc
 *   waveletlll_glcm_clustershade_lm => waveletlll_glcm_clustershade_lm
 *   waveletlll_glcm_idn_fc => waveletlll_glcm_idn_fc
 *   waveletlll_gldm_largedependenceh_lm => waveletlll_gldm_largedependenceh
 *   waveletlll_glszm_graylevelnonuni_fc => waveletlll_glszm_graylevelnonuni
 *   waveletlll_glszm_graylevelvarian_mm => waveletlll_glszm_graylevelvarian
 *   waveletlll_ngtdm_busyness_tc => waveletlll_ngtdm_busyness_tc
 */
DECLARE int idx_max;
DECLARE double val_max;
DECLARE double acc_max;
idx_max = 0;
acc_max = .;

Probability_itype1_Control_P = (1/(1+exp(-((138.906662284563 + -0.0374840613777587*original_firstorder_minimum_fc + 30.0851204984573*
  original_glszm_smallareaemphasis + -5.16886931938608*original_shape_elongation_lm + -22.6027937197107*original_shape_sphericity_mm + 
  -183.241411245849*v455_fc + -31.2864884900061*v620_fc + 13.0929184029347*v810_mm + -0.0449150326270933*wavelethhh_firstorder_minimum_fc + 
  -80.5541121951956*wavelethhh_glcm_clustershade_mm + -175.513292031235*wavelethhh_glcm_imc1_lm + 14.1388520672465*wavelethhh_glrlm_runvariance_mm + 
  -0.0000000065806757192*wavelethhh_glszm_largeareahighgr + 8.44401662768123*wavelethhl_firstorder_mean_mm + -2.50698631344467*
  wavelethhl_glcm_clusterprominenc + -70.4834404869617*wavelethhl_glcm_correlation_mm + 135.159288730406*wavelethhl_glcm_imc1_mm + 
  68.3596341150643*wavelethhl_glcm_imc1_tc + -580.872797304735*wavelethhl_gldm_smalldependencel + -634.382491552537*wavelethhl_gldm_smalldependence2 + 
  -0.0725533381359363*wavelethhl_glrlm_longrunhighgray + 7.05678012366991*wavelethhl_glszm_graylevelvarian + 0.0000034063862657645*
  wavelethhl_glszm_largearealowgra + -23.7451543847941*wavelethhl_glszm_smallareaemphas + -2.46711982513115*wavelethlh_firstorder_median_lm + 
  0.000000052516315218*wavelethlh_glszm_largeareahighgr + -1.61594579730143*wavelethlh_glszm_zoneentropy_tc + -0.315597348534774*
  wavelethll_firstorder_kurtosis_m + 2.72362187343286*wavelethll_firstorder_skewness_l + -0.00363176200000953*wavelethll_glszm_graylevelnonuni + 
  -0.0000108750618386455*wavelethll_glszm_largearealowgra + -34.6049578360473*wavelethll_glszm_smallareaemphas + -0.00622267395786139*
  wavelethll_ngtdm_busyness_mm + 0.0125102964039785*waveletlhh_firstorder_maximum_mm + -1.63901757644153*waveletlhh_firstorder_median_lm + 
  -5.4573283165394*waveletlhh_glszm_smallareaemphas + -0.00913208687306463*waveletlhl_firstorder_minimum_tc + 3.82470924731225*
  waveletlhl_firstorder_skewness_f + -2.44052577290932*waveletlhl_firstorder_skewness_t + -0.271269630988434*waveletlhl_glcm_clustershade_fc + 
  -2.22075325292815*waveletlhl_glszm_zoneentropy_lm + -1.73129068376673*waveletlhl_glszm_zoneentropy_mm + -0.0049465095877357*
  waveletllh_firstorder_minimum_fc + -22.7839150149442*waveletllh_glcm_correlation_mm + -49.4931066442567*waveletllh_glcm_imc1_mm + 
  508.07815254672*waveletllh_gldm_smalldependencel + -4.27054091625983*waveletllh_glszm_zoneentropy_fc + 0.00258323341544075*
  waveletlll_glcm_clustershade_lm + -66.2396707106205*waveletlll_glcm_idn_fc + 0.0000154180694582632*waveletlll_gldm_largedependenceh + 
  0.00278500701223195*waveletlll_glszm_graylevelnonuni + 0.12855055853742*waveletlll_glszm_graylevelvarian + -0.237040444584005*
  waveletlll_ngtdm_busyness_tc)))));
Probability_itype1_Case_Prob = 1 + -1*(1/(1+exp(-((138.906662284563 + -0.0374840613777587*
  original_firstorder_minimum_fc + 30.0851204984573*original_glszm_smallareaemphasis + -5.16886931938608*original_shape_elongation_lm + 
  -22.6027937197107*original_shape_sphericity_mm + -183.241411245849*v455_fc + -31.2864884900061*v620_fc + 13.0929184029347*
  v810_mm + -0.0449150326270933*wavelethhh_firstorder_minimum_fc + -80.5541121951956*wavelethhh_glcm_clustershade_mm + -175.513292031235*
  wavelethhh_glcm_imc1_lm + 14.1388520672465*wavelethhh_glrlm_runvariance_mm + -0.0000000065806757192*wavelethhh_glszm_largeareahighgr + 
  8.44401662768123*wavelethhl_firstorder_mean_mm + -2.50698631344467*wavelethhl_glcm_clusterprominenc + -70.4834404869617*wavelethhl_glcm_correlation_mm + 
  135.159288730406*wavelethhl_glcm_imc1_mm + 68.3596341150643*wavelethhl_glcm_imc1_tc + -580.872797304735*wavelethhl_gldm_smalldependencel + 
  -634.382491552537*wavelethhl_gldm_smalldependence2 + -0.0725533381359363*wavelethhl_glrlm_longrunhighgray + 7.05678012366991*
  wavelethhl_glszm_graylevelvarian + 0.0000034063862657645*wavelethhl_glszm_largearealowgra + -23.7451543847941*wavelethhl_glszm_smallareaemphas + 
  -2.46711982513115*wavelethlh_firstorder_median_lm + 0.000000052516315218*wavelethlh_glszm_largeareahighgr + -1.61594579730143*
  wavelethlh_glszm_zoneentropy_tc + -0.315597348534774*wavelethll_firstorder_kurtosis_m + 2.72362187343286*wavelethll_firstorder_skewness_l + 
  -0.00363176200000953*wavelethll_glszm_graylevelnonuni + -0.0000108750618386455*wavelethll_glszm_largearealowgra + -34.6049578360473*
  wavelethll_glszm_smallareaemphas + -0.00622267395786139*wavelethll_ngtdm_busyness_mm + 0.0125102964039785*waveletlhh_firstorder_maximum_mm + 
  -1.63901757644153*waveletlhh_firstorder_median_lm + -5.4573283165394*waveletlhh_glszm_smallareaemphas + -0.00913208687306463*
  waveletlhl_firstorder_minimum_tc + 3.82470924731225*waveletlhl_firstorder_skewness_f + -2.44052577290932*waveletlhl_firstorder_skewness_t + 
  -0.271269630988434*waveletlhl_glcm_clustershade_fc + -2.22075325292815*waveletlhl_glszm_zoneentropy_lm + -1.73129068376673*
  waveletlhl_glszm_zoneentropy_mm + -0.0049465095877357*waveletllh_firstorder_minimum_fc + -22.7839150149442*waveletllh_glcm_correlation_mm + 
  -49.4931066442567*waveletllh_glcm_imc1_mm + 508.07815254672*waveletllh_gldm_smalldependencel + -4.27054091625983*waveletllh_glszm_zoneentropy_fc + 
  0.00258323341544075*waveletlll_glcm_clustershade_lm + -66.2396707106205*waveletlll_glcm_idn_fc + 0.0000154180694582632*waveletlll_gldm_largedependenceh + 
  0.00278500701223195*waveletlll_glszm_graylevelnonuni + 0.12855055853742*waveletlll_glszm_graylevelvarian + -0.237040444584005*
  waveletlll_ngtdm_busyness_tc)))));
val_max = Probability_itype1_Control_;
IF (not missing(val_max) AND (missing(acc_max) OR val_max > acc_max)) THEN DO;
  idx_max = 1;
  acc_max = val_max;
END;
val_max = Probability_itype1_Case_;
IF (not missing(val_max) AND (missing(acc_max) OR val_max > acc_max)) THEN DO;
  idx_max = 2;
  acc_max = val_max;
END;

Most_Likely_itype1_Most_Likely_ = 
 SELECT (idx_max)
  WHEN (1) 'Control'
  WHEN (2) 'Case'
  OTHERWISE ''
 END
;
