"use strict";

var jmp = require('./jmp_score.js');


/* ==================================================================
 Copyright(C) 2018 SAS Institute Inc.All rights reserved.
 
 Notice:
 The following permissions are granted provided that the
 above copyright and this notice appear in the score code and
 any related documentation. Permission to copy, modify
 and distribute the score code generated using
 JMP(R) software is limited to customers of SAS Institute Inc. ("SAS")
 and successive third parties, all without any warranty, express or
 implied, or any other obligation by SAS. SAS and all other SAS
 Institute Inc. product and service names are registered
 trademarks or trademarks of SAS Institute Inc. in the USA
 and other countries. Except as contained in this notice,
 the name of the SAS Institute Inc. and JMP shall not be used in
 the advertising or promotion of products or services without
 prior written authorization from SAS Institute Inc.
 ================================================================== */

/* JavaScript code generated by JMP v16.2.0 */
var getModelMetadata = function() {
	return {"creator": "Naive Bayes", "modelName": "", "predicted": "itype1", "table": "final-2022-11-18", "version": "16.2.0", "timestamp": "2023-02-13T04:46:41Z"};
};

var getInputMetadata = function() {
    return {
   "$schema": "http://json-schema.org/draft-04/schema#",
   "id": "/",
   "type": "object",
   "properties": {
     "original_firstorder_minimum_fc": {
       "id": "original_firstorder_minimum_fc",
       "type": "number"
     },
     "original_glszm_smallareaemphasis_fc": {
       "id": "original_glszm_smallareaemphasis_fc",
       "type": "number"
     },
     "original_shape_elongation_lm": {
       "id": "original_shape_elongation_lm",
       "type": "number"
     },
     "original_shape_flatness_fc": {
       "id": "original_shape_flatness_fc",
       "type": "number"
     },
     "original_shape_sphericity_fc": {
       "id": "original_shape_sphericity_fc",
       "type": "number"
     },
     "original_shape_sphericity_mm": {
       "id": "original_shape_sphericity_mm",
       "type": "number"
     },
     "v455_fc": {
       "id": "v455_fc",
       "type": "number"
     },
     "v620_fc": {
       "id": "v620_fc",
       "type": "number"
     },
     "v810_mm": {
       "id": "v810_mm",
       "type": "number"
     },
     "wavelethhh_firstorder_minimum_fc": {
       "id": "wavelethhh_firstorder_minimum_fc",
       "type": "number"
     },
     "wavelethhh_firstorder_range_fc": {
       "id": "wavelethhh_firstorder_range_fc",
       "type": "number"
     },
     "wavelethhh_firstorder_skewness_fc": {
       "id": "wavelethhh_firstorder_skewness_fc",
       "type": "number"
     },
     "wavelethhh_glcm_clustershade_mm": {
       "id": "wavelethhh_glcm_clustershade_mm",
       "type": "number"
     },
     "wavelethhh_glcm_imc1_lm": {
       "id": "wavelethhh_glcm_imc1_lm",
       "type": "number"
     },
     "wavelethhh_glrlm_runvariance_mm": {
       "id": "wavelethhh_glrlm_runvariance_mm",
       "type": "number"
     },
     "wavelethhh_glszm_largeareahighgr_fc": {
       "id": "wavelethhh_glszm_largeareahighgr_fc",
       "type": "number"
     },
     "wavelethhl_firstorder_mean_mm": {
       "id": "wavelethhl_firstorder_mean_mm",
       "type": "number"
     },
     "wavelethhl_glcm_clusterprominenc_fc": {
       "id": "wavelethhl_glcm_clusterprominenc_fc",
       "type": "number"
     },
     "wavelethhl_glcm_correlation_fc": {
       "id": "wavelethhl_glcm_correlation_fc",
       "type": "number"
     },
     "wavelethhl_glcm_correlation_mm": {
       "id": "wavelethhl_glcm_correlation_mm",
       "type": "number"
     },
     "wavelethhl_glcm_imc1_mm": {
       "id": "wavelethhl_glcm_imc1_mm",
       "type": "number"
     },
     "wavelethhl_glcm_imc1_tc": {
       "id": "wavelethhl_glcm_imc1_tc",
       "type": "number"
     },
     "wavelethhl_gldm_smalldependencel_fc": {
       "id": "wavelethhl_gldm_smalldependencel_fc",
       "type": "number"
     },
     "wavelethhl_gldm_smalldependencel_mm": {
       "id": "wavelethhl_gldm_smalldependencel_mm",
       "type": "number"
     },
     "wavelethhl_glrlm_longrunhighgray_mm": {
       "id": "wavelethhl_glrlm_longrunhighgray_mm",
       "type": "number"
     },
     "wavelethhl_glszm_graylevelvarian_mm": {
       "id": "wavelethhl_glszm_graylevelvarian_mm",
       "type": "number"
     },
     "wavelethhl_glszm_largearealowgra_fc": {
       "id": "wavelethhl_glszm_largearealowgra_fc",
       "type": "number"
     },
     "wavelethhl_glszm_smallareaemphas_fc": {
       "id": "wavelethhl_glszm_smallareaemphas_fc",
       "type": "number"
     },
     "wavelethhl_ngtdm_strength_fc": {
       "id": "wavelethhl_ngtdm_strength_fc",
       "type": "number"
     },
     "wavelethlh_firstorder_median_fc": {
       "id": "wavelethlh_firstorder_median_fc",
       "type": "number"
     },
     "wavelethlh_firstorder_median_lm": {
       "id": "wavelethlh_firstorder_median_lm",
       "type": "number"
     },
     "wavelethlh_glszm_largeareahighgr_tc": {
       "id": "wavelethlh_glszm_largeareahighgr_tc",
       "type": "number"
     },
     "wavelethlh_glszm_zoneentropy_tc": {
       "id": "wavelethlh_glszm_zoneentropy_tc",
       "type": "number"
     },
     "wavelethll_firstorder_kurtosis_mm": {
       "id": "wavelethll_firstorder_kurtosis_mm",
       "type": "number"
     },
     "wavelethll_firstorder_skewness_lm": {
       "id": "wavelethll_firstorder_skewness_lm",
       "type": "number"
     },
     "wavelethll_glszm_graylevelnonuni_fc": {
       "id": "wavelethll_glszm_graylevelnonuni_fc",
       "type": "number"
     },
     "wavelethll_glszm_largearealowgra_lm": {
       "id": "wavelethll_glszm_largearealowgra_lm",
       "type": "number"
     },
     "wavelethll_glszm_smallareaemphas_fc": {
       "id": "wavelethll_glszm_smallareaemphas_fc",
       "type": "number"
     },
     "wavelethll_ngtdm_busyness_mm": {
       "id": "wavelethll_ngtdm_busyness_mm",
       "type": "number"
     },
     "waveletlhh_firstorder_kurtosis_fc": {
       "id": "waveletlhh_firstorder_kurtosis_fc",
       "type": "number"
     },
     "waveletlhh_firstorder_maximum_fc": {
       "id": "waveletlhh_firstorder_maximum_fc",
       "type": "number"
     },
     "waveletlhh_firstorder_maximum_mm": {
       "id": "waveletlhh_firstorder_maximum_mm",
       "type": "number"
     },
     "waveletlhh_firstorder_mean_fc": {
       "id": "waveletlhh_firstorder_mean_fc",
       "type": "number"
     },
     "waveletlhh_firstorder_median_fc": {
       "id": "waveletlhh_firstorder_median_fc",
       "type": "number"
     },
     "waveletlhh_firstorder_median_lm": {
       "id": "waveletlhh_firstorder_median_lm",
       "type": "number"
     },
     "waveletlhh_glszm_largearealowgra_fc": {
       "id": "waveletlhh_glszm_largearealowgra_fc",
       "type": "number"
     },
     "waveletlhh_glszm_smallareaemphas_fc": {
       "id": "waveletlhh_glszm_smallareaemphas_fc",
       "type": "number"
     },
     "waveletlhh_glszm_smallareaemphas_mm": {
       "id": "waveletlhh_glszm_smallareaemphas_mm",
       "type": "number"
     },
     "waveletlhl_firstorder_minimum_tc": {
       "id": "waveletlhl_firstorder_minimum_tc",
       "type": "number"
     },
     "waveletlhl_firstorder_skewness_fc": {
       "id": "waveletlhl_firstorder_skewness_fc",
       "type": "number"
     },
     "waveletlhl_firstorder_skewness_tc": {
       "id": "waveletlhl_firstorder_skewness_tc",
       "type": "number"
     },
     "waveletlhl_glcm_clustershade_fc": {
       "id": "waveletlhl_glcm_clustershade_fc",
       "type": "number"
     },
     "waveletlhl_glcm_imc1_fc": {
       "id": "waveletlhl_glcm_imc1_fc",
       "type": "number"
     },
     "waveletlhl_glszm_smallarealowgra_fc": {
       "id": "waveletlhl_glszm_smallarealowgra_fc",
       "type": "number"
     },
     "waveletlhl_glszm_zoneentropy_lm": {
       "id": "waveletlhl_glszm_zoneentropy_lm",
       "type": "number"
     },
     "waveletlhl_glszm_zoneentropy_mm": {
       "id": "waveletlhl_glszm_zoneentropy_mm",
       "type": "number"
     },
     "waveletllh_firstorder_minimum_fc": {
       "id": "waveletllh_firstorder_minimum_fc",
       "type": "number"
     },
     "waveletllh_glcm_correlation_mm": {
       "id": "waveletllh_glcm_correlation_mm",
       "type": "number"
     },
     "waveletllh_glcm_imc1_mm": {
       "id": "waveletllh_glcm_imc1_mm",
       "type": "number"
     },
     "waveletllh_gldm_smalldependencel_mm": {
       "id": "waveletllh_gldm_smalldependencel_mm",
       "type": "number"
     },
     "waveletllh_glszm_smallarealowgra_fc": {
       "id": "waveletllh_glszm_smallarealowgra_fc",
       "type": "number"
     },
     "waveletllh_glszm_zoneentropy_fc": {
       "id": "waveletllh_glszm_zoneentropy_fc",
       "type": "number"
     },
     "waveletlll_glcm_clustershade_lm": {
       "id": "waveletlll_glcm_clustershade_lm",
       "type": "number"
     },
     "waveletlll_glcm_idn_fc": {
       "id": "waveletlll_glcm_idn_fc",
       "type": "number"
     },
     "waveletlll_glcm_imc2_fc": {
       "id": "waveletlll_glcm_imc2_fc",
       "type": "number"
     },
     "waveletlll_gldm_largedependenceh_lm": {
       "id": "waveletlll_gldm_largedependenceh_lm",
       "type": "number"
     },
     "waveletlll_glszm_graylevelnonuni_fc": {
       "id": "waveletlll_glszm_graylevelnonuni_fc",
       "type": "number"
     },
     "waveletlll_glszm_graylevelvarian_mm": {
       "id": "waveletlll_glszm_graylevelvarian_mm",
       "type": "number"
     },
     "waveletlll_ngtdm_busyness_tc": {
       "id": "waveletlll_ngtdm_busyness_tc",
       "type": "number"
     },
     "Naive Prob Case": {
       "id": "Naive Prob Case",
       "type": "number"
     },
     "Naive Prob Control": {
       "id": "Naive Prob Control",
       "type": "number"
     }   },
   "additionalProperties": false,
  };
};

var getOutputMetadata = function() {
    return {
   "$schema": "http://json-schema.org/draft-04/schema#",
   "id": "/",
   "type": "object",
   "properties": {
     "Naive Prob Case,!Naive Prob Case": {
       "id": "Naive Prob Case,!Naive Prob Case",
       "type": "number"
     },
     "Naive Prob Control,!Naive Prob Control": {
       "id": "Naive Prob Control,!Naive Prob Control",
       "type": "number"
     },
     "Naive Predicted Formula itype1,!Naive Predicted Formula itype1": {
       "id": "Naive Predicted Formula itype1,!Naive Predicted Formula itype1",
       "type": "string"
     }   },
   "additionalProperties": false,
  };
};

var score = function(indata, outdata) {
    // Original name was: 'Naive Score Control'
    var Naive_Score_Control;
    // Original name was: 'Naive Score Case'
    var Naive_Score_Case;
    // Original name was: 'Naive Score Case,!Naive Score Case'
    var Naive_Score_Case_Naive_Score_Case;
    // Original name was: 'Naive Score Control,!Naive Score Control'
    var Naive_Score_Control_Naive_Score_Control;
    // Original name was: 'Naive Score Sum_1'
    var Naive_Score_Sum_1;
    var _temp_0 = undefined;
    var _temp_1 = undefined;
    var _temp_2 = undefined;
    var _temp_3 = undefined;
    var _temp_4 = undefined;
    var _temp_5 = undefined;
    var _temp_6 = undefined;
    var _temp_7 = undefined;
    var _temp_8 = undefined;
    var _temp_9 = undefined;
    var _temp_10 = undefined;
    var _temp_11 = undefined;
    var _temp_12 = undefined;
    var _temp_13 = undefined;
    var _temp_14 = undefined;
    var _temp_15 = undefined;
    var _temp_16 = undefined;
    var _temp_17 = undefined;
    var _temp_18 = undefined;
    var _temp_19 = undefined;
    var _temp_20 = undefined;
    var _temp_21 = undefined;
    var _temp_22 = undefined;
    var _temp_23 = undefined;
    var _temp_24 = undefined;
    var _temp_25 = undefined;
    var _temp_26 = undefined;
    var _temp_27 = undefined;
    var _temp_28 = undefined;
    var _temp_29 = undefined;
    var _temp_30 = undefined;
    var _temp_31 = undefined;
    var _temp_32 = undefined;
    var _temp_33 = undefined;
    var _temp_34 = undefined;
    var _temp_35 = undefined;
    var _temp_36 = undefined;
    var _temp_37 = undefined;
    var _temp_38 = undefined;
    var _temp_39 = undefined;
    var _temp_40 = undefined;
    var _temp_41 = undefined;
    var _temp_42 = undefined;
    var _temp_43 = undefined;
    var _temp_44 = undefined;
    var _temp_45 = undefined;
    var _temp_46 = undefined;
    var _temp_47 = undefined;
    var _temp_48 = undefined;
    var _temp_49 = undefined;
    var _temp_50 = undefined;
    var _temp_51 = undefined;
    var _temp_52;
    var _temp_53 = [];
    var _temp_54 = "";

    if (jmp.is_missing(indata["wavelethhl_glcm_clusterprominenc_fc"]))  {
        _temp_0 = 0;
    }
    else {
        _temp_0 = placeholder_Normal_Log_Density(((indata["wavelethhl_glcm_clusterprominenc_fc"] - 1.5099980010219) / 0.620417155236684)) - -0.477363196165406;
    }
    if (jmp.is_missing(indata["wavelethhl_glszm_largearealowgra_fc"]))  {
        _temp_1 = 0;
    }
    else {
        _temp_1 = placeholder_Normal_Log_Density(((indata["wavelethhl_glszm_largearealowgra_fc"] - 520507.831076642) / 495663.188700286)) - 13.113651920005;
    }
    if (jmp.is_missing(indata["waveletllh_glszm_zoneentropy_fc"]))  {
        _temp_2 = 0;
    }
    else {
        _temp_2 = placeholder_Normal_Log_Density(((indata["waveletllh_glszm_zoneentropy_fc"] - 5.88703548686131) / 0.156749597011016)) - -1.85310567037502;
    }
    if (jmp.is_missing(indata["original_glszm_smallareaemphasis_fc"]))  {
        _temp_3 = 0;
    }
    else {
        _temp_3 = placeholder_Normal_Log_Density(((indata["original_glszm_smallareaemphasis_fc"] - 0.590618415839416) / 0.0116283408893149)) - -4.45430998046867;
    }
    if (jmp.is_missing(indata["v620_fc"]))  {
        _temp_4 = 0;
    }
    else {
        _temp_4 = placeholder_Normal_Log_Density(((indata["v620_fc"] - 0.446815272992701) / 0.0237881008194811)) - -3.73856978889719;
    }
    if (jmp.is_missing(indata["wavelethll_glszm_graylevelnonuni_fc"]))  {
        _temp_5 = 0;
    }
    else {
        _temp_5 = placeholder_Normal_Log_Density(((indata["wavelethll_glszm_graylevelnonuni_fc"] - 795.55262379562) / 338.126175389902)) - 5.82341912579405;
    }
    if (jmp.is_missing(indata["waveletlll_glcm_imc2_fc"]))  {
        _temp_6 = 0;
    }
    else {
        _temp_6 = placeholder_Normal_Log_Density(((indata["waveletlll_glcm_imc2_fc"] - 0.843224175620438) / 0.0329402230864912)) - -3.41306078174522;
    }
    if (jmp.is_missing(indata["wavelethll_glszm_smallareaemphas_fc"]))  {
        _temp_7 = 0;
    }
    else {
        _temp_7 = placeholder_Normal_Log_Density(((indata["wavelethll_glszm_smallareaemphas_fc"] - 0.554854389087591) / 0.0207562665599597)) - -3.8749070750095;
    }
    if (jmp.is_missing(indata["waveletllh_firstorder_minimum_fc"]))  {
        _temp_8 = 0;
    }
    else {
        _temp_8 = placeholder_Normal_Log_Density(((indata["waveletllh_firstorder_minimum_fc"] - -244.210995291971) / 38.6231566521983)) - 3.65385200986414;
    }
    if (jmp.is_missing(indata["waveletlll_glszm_graylevelnonuni_fc"]))  {
        _temp_9 = 0;
    }
    else {
        _temp_9 = placeholder_Normal_Log_Density(((indata["waveletlll_glszm_graylevelnonuni_fc"] - 1360.58213474453) / 194.028601816155)) - 5.26800558023833;
    }
    if (jmp.is_missing(indata["v455_fc"]))  {
        _temp_10 = 0;
    }
    else {
        _temp_10 = placeholder_Normal_Log_Density(((indata["v455_fc"] - 0.0606783687591241) / 0.00159104700653119)) - -6.44336298478878;
    }
    if (jmp.is_missing(indata["wavelethhl_glszm_smallareaemphas_fc"]))  {
        _temp_11 = 0;
    }
    else {
        _temp_11 = placeholder_Normal_Log_Density(((indata["wavelethhl_glszm_smallareaemphas_fc"] - 0.717608574087591) / 0.0246112606050436)) - -3.70455119260605;
    }
    if (jmp.is_missing(indata["waveletlhh_firstorder_kurtosis_fc"]))  {
        _temp_12 = 0;
    }
    else {
        _temp_12 = placeholder_Normal_Log_Density(((indata["waveletlhh_firstorder_kurtosis_fc"] - 4.45406231751825) / 0.531279411152576)) - -0.632467198106385;
    }
    if (jmp.is_missing(indata["waveletlhh_glszm_largearealowgra_fc"]))  {
        _temp_13 = 0;
    }
    else {
        _temp_13 = placeholder_Normal_Log_Density(((indata["waveletlhh_glszm_largearealowgra_fc"] - 40776.2445751825) / 23391.4095420044)) - 10.0601241203535;
    }
    if (jmp.is_missing(indata["waveletlhh_firstorder_maximum_fc"]))  {
        _temp_14 = 0;
    }
    else {
        _temp_14 = placeholder_Normal_Log_Density(((indata["waveletlhh_firstorder_maximum_fc"] - 135.304948007299) / 27.2631864228882)) - 3.30553730949187;
    }
    if (jmp.is_missing(indata["wavelethhl_glcm_correlation_fc"]))  {
        _temp_15 = 0;
    }
    else {
        _temp_15 = placeholder_Normal_Log_Density(((indata["wavelethhl_glcm_correlation_fc"] - 0.0262412372627737) / 0.00940371431068138)) - -4.66665052831902;
    }
    if (jmp.is_missing(indata["wavelethhh_glszm_largeareahighgr_fc"]))  {
        _temp_16 = 0;
    }
    else {
        _temp_16 = placeholder_Normal_Log_Density(((indata["wavelethhh_glszm_largeareahighgr_fc"] - 205854428.653285) / 137041171.184661)) - 18.7357919582415;
    }
    if (jmp.is_missing(indata["waveletlll_glcm_idn_fc"]))  {
        _temp_17 = 0;
    }
    else {
        _temp_17 = placeholder_Normal_Log_Density(((indata["waveletlll_glcm_idn_fc"] - 0.938742039270073) / 0.00558203754863577)) - -5.18820141715545;
    }
    if (jmp.is_missing(indata["waveletllh_glszm_smallarealowgra_fc"]))  {
        _temp_18 = 0;
    }
    else {
        _temp_18 = placeholder_Normal_Log_Density(((indata["waveletllh_glszm_smallarealowgra_fc"] - 0.00734470105839416) / 0.00231595916367596)) - -6.06793135169111;
    }
    if (jmp.is_missing(indata["wavelethhl_gldm_smalldependencel_fc"]))  {
        _temp_19 = 0;
    }
    else {
        _temp_19 = placeholder_Normal_Log_Density(((indata["wavelethhl_gldm_smalldependencel_fc"] - 0.00207444587591241) / 0.000769253293764271)) - -7.17009026198478;
    }
    if (jmp.is_missing(indata["waveletlhl_firstorder_skewness_fc"]))  {
        _temp_20 = 0;
    }
    else {
        _temp_20 = placeholder_Normal_Log_Density(((indata["waveletlhl_firstorder_skewness_fc"] - -0.329775307554745) / 0.104575366317771)) - -2.25784725874085;
    }
    if (jmp.is_missing(indata["original_firstorder_minimum_fc"]))  {
        _temp_21 = 0;
    }
    else {
        _temp_21 = placeholder_Normal_Log_Density(((indata["original_firstorder_minimum_fc"] - 8.2956204379562) / 4.08654306584811)) - 1.40769939648407;
    }
    if (jmp.is_missing(indata["waveletlhl_glcm_clustershade_fc"]))  {
        _temp_22 = 0;
    }
    else {
        _temp_22 = placeholder_Normal_Log_Density(((indata["waveletlhl_glcm_clustershade_fc"] - -3.41646082456204) / 2.02045502939638)) - 0.703322748122837;
    }
    if (jmp.is_missing(indata["waveletlhl_glcm_imc1_fc"]))  {
        _temp_23 = 0;
    }
    else {
        _temp_23 = placeholder_Normal_Log_Density(((indata["waveletlhl_glcm_imc1_fc"] - -0.0613138172992701) / 0.00708073377884781)) - -4.95037773556667;
    }
    if (jmp.is_missing(indata["original_shape_flatness_fc"]))  {
        _temp_24 = 0;
    }
    else {
        _temp_24 = placeholder_Normal_Log_Density(((indata["original_shape_flatness_fc"] - 0.442544809416058) / 0.0160558629334783)) - -4.13168120430342;
    }
    if (jmp.is_missing(indata["waveletlhh_firstorder_mean_fc"]))  {
        _temp_25 = 0;
    }
    else {
        _temp_25 = placeholder_Normal_Log_Density(((indata["waveletlhh_firstorder_mean_fc"] - 0.202979843065693) / 0.167968485852312)) - -1.78397890138743;
    }
    if (jmp.is_missing(indata["wavelethhh_firstorder_skewness_fc"]))  {
        _temp_26 = 0;
    }
    else {
        _temp_26 = placeholder_Normal_Log_Density(((indata["wavelethhh_firstorder_skewness_fc"] - -0.0178236131386861) / 0.0381642269902967)) - -3.26585666835064;
    }
    if (jmp.is_missing(indata["wavelethhl_ngtdm_strength_fc"]))  {
        _temp_27 = 0;
    }
    else {
        _temp_27 = placeholder_Normal_Log_Density(((indata["wavelethhl_ngtdm_strength_fc"] - 0.000871780109489051) / 0.000408549071008122)) - -7.80289852601175;
    }
    if (jmp.is_missing(indata["wavelethhh_firstorder_range_fc"]))  {
        _temp_28 = 0;
    }
    else {
        _temp_28 = placeholder_Normal_Log_Density(((indata["wavelethhh_firstorder_range_fc"] - 112.635549076642) / 20.6398840300423)) - 3.02722532189808;
    }
    if (jmp.is_missing(indata["original_shape_sphericity_fc"]))  {
        _temp_29 = 0;
    }
    else {
        _temp_29 = placeholder_Normal_Log_Density(((indata["original_shape_sphericity_fc"] - 0.205068864087591) / 0.0109272955022363)) - -4.5164914454503;
    }
    if (jmp.is_missing(indata["waveletlhl_glszm_smallarealowgra_fc"]))  {
        _temp_30 = 0;
    }
    else {
        _temp_30 = placeholder_Normal_Log_Density(((indata["waveletlhl_glszm_smallarealowgra_fc"] - 0.00875705810218978) / 0.00317562594846545)) - -5.75225051694584;
    }
    if (jmp.is_missing(indata["waveletlhh_firstorder_median_fc"]))  {
        _temp_31 = 0;
    }
    else {
        _temp_31 = placeholder_Normal_Log_Density(((indata["waveletlhh_firstorder_median_fc"] - -0.00621641127737226) / 0.113587914218034)) - -2.17517816728054;
    }
    if (jmp.is_missing(indata["waveletlhh_glszm_smallareaemphas_fc"]))  {
        _temp_32 = 0;
    }
    else {
        _temp_32 = placeholder_Normal_Log_Density(((indata["waveletlhh_glszm_smallareaemphas_fc"] - 0.572621553430657) / 0.0154964299685857)) - -4.1671456061931;
    }
    if (jmp.is_missing(indata["wavelethhh_firstorder_minimum_fc"]))  {
        _temp_33 = 0;
    }
    else {
        _temp_33 = placeholder_Normal_Log_Density(((indata["wavelethhh_firstorder_minimum_fc"] - -53.8411539343066) / 9.97649361433198)) - 2.30023168733928;
    }
    if (jmp.is_missing(indata["wavelethlh_firstorder_median_fc"]))  {
        _temp_34 = 0;
    }
    else {
        _temp_34 = placeholder_Normal_Log_Density(((indata["wavelethlh_firstorder_median_fc"] - 0.0903708480656934) / 0.0683662691186856)) - -2.6828757175276;
    }
    Naive_Score_Control = Math.exp(((-0.694968674688336 + _temp_0 + _temp_1 + _temp_2 + _temp_3 + _temp_4 + _temp_5 + _temp_6 + _temp_7 + _temp_8 + _temp_9 + _temp_10 + _temp_11 + _temp_12 + _temp_13 + _temp_14 + _temp_15 + _temp_16 + _temp_17 + _temp_18 + _temp_19 + _temp_20 + _temp_21 + _temp_22 + _temp_23 + _temp_24 + _temp_25 + _temp_26 + _temp_27 + _temp_28 + _temp_29 + _temp_30 + _temp_31 + _temp_32 + _temp_33 + _temp_34) - -7.49466227243816));

    if (jmp.is_missing(indata["wavelethhl_glcm_clusterprominenc_fc"]))  {
        _temp_0 = 0;
    }
    else {
        _temp_0 = placeholder_Normal_Log_Density(((indata["wavelethhl_glcm_clusterprominenc_fc"] - 1.53370744654545) / 0.692281790055132)) - -0.367762195190062;
    }
    if (jmp.is_missing(indata["wavelethhl_glszm_largearealowgra_fc"]))  {
        _temp_1 = 0;
    }
    else {
        _temp_1 = placeholder_Normal_Log_Density(((indata["wavelethhl_glszm_largearealowgra_fc"] - 435831.096501818) / 289489.184638686)) - 12.5758732165363;
    }
    if (jmp.is_missing(indata["waveletllh_glszm_zoneentropy_fc"]))  {
        _temp_2 = 0;
    }
    else {
        _temp_2 = placeholder_Normal_Log_Density(((indata["waveletllh_glszm_zoneentropy_fc"] - 5.89292438145454) / 0.128295563061853)) - -2.05341859048501;
    }
    if (jmp.is_missing(indata["original_glszm_smallareaemphasis_fc"]))  {
        _temp_3 = 0;
    }
    else {
        _temp_3 = placeholder_Normal_Log_Density(((indata["original_glszm_smallareaemphasis_fc"] - 0.591560037090909) / 0.0117096794325402)) - -4.44733947727752;
    }
    if (jmp.is_missing(indata["v620_fc"]))  {
        _temp_4 = 0;
    }
    else {
        _temp_4 = placeholder_Normal_Log_Density(((indata["v620_fc"] - 0.450890965345455) / 0.0251941481153911)) - -3.68114352907466;
    }
    if (jmp.is_missing(indata["wavelethll_glszm_graylevelnonuni_fc"]))  {
        _temp_5 = 0;
    }
    else {
        _temp_5 = placeholder_Normal_Log_Density(((indata["wavelethll_glszm_graylevelnonuni_fc"] - 871.135807563636) / 355.519820025136)) - 5.87358100022121;
    }
    if (jmp.is_missing(indata["waveletlll_glcm_imc2_fc"]))  {
        _temp_6 = 0;
    }
    else {
        _temp_6 = placeholder_Normal_Log_Density(((indata["waveletlll_glcm_imc2_fc"] - 0.8452449484) / 0.0360281442132138)) - -3.32345486225934;
    }
    if (jmp.is_missing(indata["wavelethll_glszm_smallareaemphas_fc"]))  {
        _temp_7 = 0;
    }
    else {
        _temp_7 = placeholder_Normal_Log_Density(((indata["wavelethll_glszm_smallareaemphas_fc"] - 0.551383322545455) / 0.0209690704522463)) - -3.86470676255455;
    }
    if (jmp.is_missing(indata["waveletllh_firstorder_minimum_fc"]))  {
        _temp_8 = 0;
    }
    else {
        _temp_8 = placeholder_Normal_Log_Density(((indata["waveletllh_firstorder_minimum_fc"] - -241.728674472727) / 32.7280980953753)) - 3.48823397791469;
    }
    if (jmp.is_missing(indata["waveletlll_glszm_graylevelnonuni_fc"]))  {
        _temp_9 = 0;
    }
    else {
        _temp_9 = placeholder_Normal_Log_Density(((indata["waveletlll_glszm_graylevelnonuni_fc"] - 1346.58373396364) / 197.077286700149)) - 5.28359597007616;
    }
    if (jmp.is_missing(indata["v455_fc"]))  {
        _temp_10 = 0;
    }
    else {
        _temp_10 = placeholder_Normal_Log_Density(((indata["v455_fc"] - 0.0609839343272727) / 0.00168275251372007)) - -6.38732442525786;
    }
    if (jmp.is_missing(indata["wavelethhl_glszm_smallareaemphas_fc"]))  {
        _temp_11 = 0;
    }
    else {
        _temp_11 = placeholder_Normal_Log_Density(((indata["wavelethhl_glszm_smallareaemphas_fc"] - 0.722716696618182) / 0.0223382569334382)) - -3.80145451285076;
    }
    if (jmp.is_missing(indata["waveletlhh_firstorder_kurtosis_fc"]))  {
        _temp_12 = 0;
    }
    else {
        _temp_12 = placeholder_Normal_Log_Density(((indata["waveletlhh_firstorder_kurtosis_fc"] - 4.34137719236364) / 0.474644758237826)) - -0.745188632141356;
    }
    if (jmp.is_missing(indata["waveletlhh_glszm_largearealowgra_fc"]))  {
        _temp_13 = 0;
    }
    else {
        _temp_13 = placeholder_Normal_Log_Density(((indata["waveletlhh_glszm_largearealowgra_fc"] - 39528.4972134545) / 24455.4430298575)) - 10.1046080889352;
    }
    if (jmp.is_missing(indata["waveletlhh_firstorder_maximum_fc"]))  {
        _temp_14 = 0;
    }
    else {
        _temp_14 = placeholder_Normal_Log_Density(((indata["waveletlhh_firstorder_maximum_fc"] - 132.467985607273) / 24.0781164596771)) - 3.18130339726819;
    }
    if (jmp.is_missing(indata["wavelethhl_glcm_correlation_fc"]))  {
        _temp_15 = 0;
    }
    else {
        _temp_15 = placeholder_Normal_Log_Density(((indata["wavelethhl_glcm_correlation_fc"] - 0.0244852784727273) / 0.00902589721736605)) - -4.70765736503791;
    }
    if (jmp.is_missing(indata["wavelethhh_glszm_largeareahighgr_fc"]))  {
        _temp_16 = 0;
    }
    else {
        _temp_16 = placeholder_Normal_Log_Density(((indata["wavelethhh_glszm_largeareahighgr_fc"] - 191128638.163636) / 110900723.854824)) - 18.5241459793942;
    }
    if (jmp.is_missing(indata["waveletlll_glcm_idn_fc"]))  {
        _temp_17 = 0;
    }
    else {
        _temp_17 = placeholder_Normal_Log_Density(((indata["waveletlll_glcm_idn_fc"] - 0.939500618) / 0.00578693698794917)) - -5.15215214500179;
    }
    if (jmp.is_missing(indata["waveletllh_glszm_smallarealowgra_fc"]))  {
        _temp_18 = 0;
    }
    else {
        _temp_18 = placeholder_Normal_Log_Density(((indata["waveletllh_glszm_smallarealowgra_fc"] - 0.00724784949090909) / 0.00195471867768865)) - -6.23750899477973;
    }
    if (jmp.is_missing(indata["wavelethhl_gldm_smalldependencel_fc"]))  {
        _temp_19 = 0;
    }
    else {
        _temp_19 = placeholder_Normal_Log_Density(((indata["wavelethhl_gldm_smalldependencel_fc"] - 0.00214759850909091) / 0.000802514171775834)) - -7.12776104358228;
    }
    if (jmp.is_missing(indata["waveletlhl_firstorder_skewness_fc"]))  {
        _temp_20 = 0;
    }
    else {
        _temp_20 = placeholder_Normal_Log_Density(((indata["waveletlhl_firstorder_skewness_fc"] - -0.339615847163636) / 0.09638299569143)) - -2.33942548616718;
    }
    if (jmp.is_missing(indata["original_firstorder_minimum_fc"]))  {
        _temp_21 = 0;
    }
    else {
        _temp_21 = placeholder_Normal_Log_Density(((indata["original_firstorder_minimum_fc"] - 8.52363636363636) / 4.31454692821311)) - 1.46199231976722;
    }
    if (jmp.is_missing(indata["waveletlhl_glcm_clustershade_fc"]))  {
        _temp_22 = 0;
    }
    else {
        _temp_22 = placeholder_Normal_Log_Density(((indata["waveletlhl_glcm_clustershade_fc"] - -3.3466063148) / 1.83783206055149)) - 0.608586649003487;
    }
    if (jmp.is_missing(indata["waveletlhl_glcm_imc1_fc"]))  {
        _temp_23 = 0;
    }
    else {
        _temp_23 = placeholder_Normal_Log_Density(((indata["waveletlhl_glcm_imc1_fc"] - -0.0590549616) / 0.00671996680680565)) - -5.00267206392272;
    }
    if (jmp.is_missing(indata["original_shape_flatness_fc"]))  {
        _temp_24 = 0;
    }
    else {
        _temp_24 = placeholder_Normal_Log_Density(((indata["original_shape_flatness_fc"] - 0.4396873348) / 0.0165079851542963)) - -4.1039110663958;
    }
    if (jmp.is_missing(indata["waveletlhh_firstorder_mean_fc"]))  {
        _temp_25 = 0;
    }
    else {
        _temp_25 = placeholder_Normal_Log_Density(((indata["waveletlhh_firstorder_mean_fc"] - 0.169530623236364) / 0.150005476612963)) - -1.8970834747993;
    }
    if (jmp.is_missing(indata["wavelethhh_firstorder_skewness_fc"]))  {
        _temp_26 = 0;
    }
    else {
        _temp_26 = placeholder_Normal_Log_Density(((indata["wavelethhh_firstorder_skewness_fc"] - -0.0185773104363636) / 0.0334327282732479)) - -3.39821997035615;
    }
    if (jmp.is_missing(indata["wavelethhl_ngtdm_strength_fc"]))  {
        _temp_27 = 0;
    }
    else {
        _temp_27 = placeholder_Normal_Log_Density(((indata["wavelethhl_ngtdm_strength_fc"] - 0.000902342327272727) / 0.000553077155050143)) - -7.50001304528774;
    }
    if (jmp.is_missing(indata["wavelethhh_firstorder_range_fc"]))  {
        _temp_28 = 0;
    }
    else {
        _temp_28 = placeholder_Normal_Log_Density(((indata["wavelethhh_firstorder_range_fc"] - 111.555229138182) / 20.6485285942854)) - 3.02764406235429;
    }
    if (jmp.is_missing(indata["original_shape_sphericity_fc"]))  {
        _temp_29 = 0;
    }
    else {
        _temp_29 = placeholder_Normal_Log_Density(((indata["original_shape_sphericity_fc"] - 0.207054422218182) / 0.0121280070169652)) - -4.41223787150666;
    }
    if (jmp.is_missing(indata["waveletlhl_glszm_smallarealowgra_fc"]))  {
        _temp_30 = 0;
    }
    else {
        _temp_30 = placeholder_Normal_Log_Density(((indata["waveletlhl_glszm_smallarealowgra_fc"] - 0.00896182298181818) / 0.00342150755274895)) - -5.67767402013621;
    }
    if (jmp.is_missing(indata["waveletlhh_firstorder_median_fc"]))  {
        _temp_31 = 0;
    }
    else {
        _temp_31 = placeholder_Normal_Log_Density(((indata["waveletlhh_firstorder_median_fc"] - -0.0234545415272727) / 0.106435214348071)) - -2.24021879491245;
    }
    if (jmp.is_missing(indata["waveletlhh_glszm_smallareaemphas_fc"]))  {
        _temp_32 = 0;
    }
    else {
        _temp_32 = placeholder_Normal_Log_Density(((indata["waveletlhh_glszm_smallareaemphas_fc"] - 0.567934824218182) / 0.0136399988490822)) - -4.29474871094496;
    }
    if (jmp.is_missing(indata["wavelethhh_firstorder_minimum_fc"]))  {
        _temp_33 = 0;
    }
    else {
        _temp_33 = placeholder_Normal_Log_Density(((indata["wavelethhh_firstorder_minimum_fc"] - -53.8355072145454) / 9.74206999414073)) - 2.27645362013997;
    }
    if (jmp.is_missing(indata["wavelethlh_firstorder_median_fc"]))  {
        _temp_34 = 0;
    }
    else {
        _temp_34 = placeholder_Normal_Log_Density(((indata["wavelethlh_firstorder_median_fc"] - 0.0944522875636364) / 0.0649093872744584)) - -2.73476302359835;
    }
    Naive_Score_Case = Math.exp(((-0.691328998240887 + _temp_0 + _temp_1 + _temp_2 + _temp_3 + _temp_4 + _temp_5 + _temp_6 + _temp_7 + _temp_8 + _temp_9 + _temp_10 + _temp_11 + _temp_12 + _temp_13 + _temp_14 + _temp_15 + _temp_16 + _temp_17 + _temp_18 + _temp_19 + _temp_20 + _temp_21 + _temp_22 + _temp_23 + _temp_24 + _temp_25 + _temp_26 + _temp_27 + _temp_28 + _temp_29 + _temp_30 + _temp_31 + _temp_32 + _temp_33 + _temp_34) - -7.49466227243816));

    if (jmp.is_missing(indata["original_firstorder_minimum_fc"]))  {
        _temp_0 = 0;
    }
    else {
        _temp_0 = -1.46199231976722 + placeholder_Normal_Log_Density((-1.9755576901713 + 0.231774046415148 * indata["original_firstorder_minimum_fc"]));
    }
    if (jmp.is_missing(indata["original_glszm_smallareaemphasis_fc"]))  {
        _temp_1 = 0;
    }
    else {
        _temp_1 = 4.44733947727752 + placeholder_Normal_Log_Density((-50.5188925537118 + 85.3994343535215 * indata["original_glszm_smallareaemphasis_fc"]));
    }
    if (jmp.is_missing(indata["original_shape_elongation_lm"]))  {
        _temp_2 = 0;
    }
    else {
        _temp_2 = 3.44606835567658 + placeholder_Normal_Log_Density((-16.3323743578004 + 31.3767871151929 * indata["original_shape_elongation_lm"]));
    }
    if (jmp.is_missing(indata["original_shape_sphericity_mm"]))  {
        _temp_3 = 0;
    }
    else {
        _temp_3 = 4.11882837625468 + placeholder_Normal_Log_Density((-25.9855284131883 + 61.4871602292054 * indata["original_shape_sphericity_mm"]));
    }
    if (jmp.is_missing(indata["v455_fc"]))  {
        _temp_4 = 0;
    }
    else {
        _temp_4 = 6.38732442525786 + placeholder_Normal_Log_Density((-36.2405842986711 + 594.264451751907 * indata["v455_fc"]));
    }
    if (jmp.is_missing(indata["v620_fc"]))  {
        _temp_5 = 0;
    }
    else {
        _temp_5 = 3.68114352907466 + placeholder_Normal_Log_Density((-17.8966545437591 + 39.6917568087606 * indata["v620_fc"]));
    }
    if (jmp.is_missing(indata["v810_mm"]))  {
        _temp_6 = 0;
    }
    else {
        _temp_6 = 3.56963151869869 + placeholder_Normal_Log_Density((-11.035759352415 + 35.503508362064 * indata["v810_mm"]));
    }
    if (jmp.is_missing(indata["wavelethhh_firstorder_minimum_fc"]))  {
        _temp_7 = 0;
    }
    else {
        _temp_7 = -2.27645362013997 + placeholder_Normal_Log_Density((5.52608503602666 + 0.102647589331779 * indata["wavelethhh_firstorder_minimum_fc"]));
    }
    if (jmp.is_missing(indata["wavelethhh_glcm_clustershade_mm"]))  {
        _temp_8 = 0;
    }
    else {
        _temp_8 = 6.1117886359281 + placeholder_Normal_Log_Density((-0.0788389378000081 + 451.144927969037 * indata["wavelethhh_glcm_clustershade_mm"]));
    }
    if (jmp.is_missing(indata["wavelethhh_glcm_imc1_lm"]))  {
        _temp_9 = 0;
    }
    else {
        _temp_9 = 6.295915992492 + placeholder_Normal_Log_Density((4.94444526048274 + 542.352409669532 * indata["wavelethhh_glcm_imc1_lm"]));
    }
    if (jmp.is_missing(indata["wavelethhh_glrlm_runvariance_mm"]))  {
        _temp_10 = 0;
    }
    else {
        _temp_10 = 3.04311278910496 + placeholder_Normal_Log_Density((-27.1410210903542 + 20.9704182338587 * indata["wavelethhh_glrlm_runvariance_mm"]));
    }
    if (jmp.is_missing(indata["wavelethhh_glszm_largeareahighgr_fc"]))  {
        _temp_11 = 0;
    }
    else {
        _temp_11 = -18.5241459793942 + placeholder_Normal_Log_Density((-1.72342101584328 + 0.0000000090170736966 * indata["wavelethhh_glszm_largeareahighgr_fc"]));
    }
    if (jmp.is_missing(indata["wavelethhl_firstorder_mean_mm"]))  {
        _temp_12 = 0;
    }
    else {
        _temp_12 = 2.70956162763264 + placeholder_Normal_Log_Density((-1.88816576369727 + 15.0226885396677 * indata["wavelethhl_firstorder_mean_mm"]));
    }
    if (jmp.is_missing(indata["wavelethhl_glcm_clusterprominenc_fc"]))  {
        _temp_13 = 0;
    }
    else {
        _temp_13 = 0.367762195190062 + placeholder_Normal_Log_Density((-2.21543808977456 + 1.4444984894379 * indata["wavelethhl_glcm_clusterprominenc_fc"]));
    }
    if (jmp.is_missing(indata["wavelethhl_glcm_correlation_mm"]))  {
        _temp_14 = 0;
    }
    else {
        _temp_14 = 4.84443991609403 + placeholder_Normal_Log_Density((-0.275845411697392 + 127.032113423142 * indata["wavelethhl_glcm_correlation_mm"]));
    }
    if (jmp.is_missing(indata["wavelethhl_glcm_imc1_mm"]))  {
        _temp_15 = 0;
    }
    else {
        _temp_15 = 5.86572242567548 + placeholder_Normal_Log_Density((5.72088095581601 + 352.736890269601 * indata["wavelethhl_glcm_imc1_mm"]));
    }
    if (jmp.is_missing(indata["wavelethhl_glcm_imc1_tc"]))  {
        _temp_16 = 0;
    }
    else {
        _temp_16 = 5.09218436015282 + placeholder_Normal_Log_Density((3.71105453117404 + 162.744967695491 * indata["wavelethhl_glcm_imc1_tc"]));
    }
    if (jmp.is_missing(indata["wavelethhl_gldm_smalldependencel_fc"]))  {
        _temp_17 = 0;
    }
    else {
        _temp_17 = 7.12776104358228 + placeholder_Normal_Log_Density((-2.67608795535488 + 1246.08391374219 * indata["wavelethhl_gldm_smalldependencel_fc"]));
    }
    if (jmp.is_missing(indata["wavelethhl_gldm_smalldependencel_mm"]))  {
        _temp_18 = 0;
    }
    else {
        _temp_18 = 6.3638351761944 + placeholder_Normal_Log_Density((-2.0207817921301 + 580.468291086326 * indata["wavelethhl_gldm_smalldependencel_mm"]));
    }
    if (jmp.is_missing(indata["wavelethhl_glrlm_longrunhighgray_mm"]))  {
        _temp_19 = 0;
    }
    else {
        _temp_19 = -2.73928991543196 + placeholder_Normal_Log_Density((-2.7488918933564 + 0.0646162135827374 * indata["wavelethhl_glrlm_longrunhighgray_mm"]));
    }
    if (jmp.is_missing(indata["wavelethhl_glszm_graylevelvarian_mm"]))  {
        _temp_20 = 0;
    }
    else {
        _temp_20 = 2.1356673758417 + placeholder_Normal_Log_Density((-18.788215782918 + 8.46269241915558 * indata["wavelethhl_glszm_graylevelvarian_mm"]));
    }
    if (jmp.is_missing(indata["wavelethhl_glszm_largearealowgra_fc"]))  {
        _temp_21 = 0;
    }
    else {
        _temp_21 = -12.5758732165363 + placeholder_Normal_Log_Density((-1.5055177175126 + 0.0000034543604841338 * indata["wavelethhl_glszm_largearealowgra_fc"]));
    }
    if (jmp.is_missing(indata["wavelethhl_glszm_smallareaemphas_fc"]))  {
        _temp_22 = 0;
    }
    else {
        _temp_22 = 3.80145451285076 + placeholder_Normal_Log_Density((-32.3533164996569 + 44.766250248608 * indata["wavelethhl_glszm_smallareaemphas_fc"]));
    }
    if (jmp.is_missing(indata["wavelethlh_firstorder_median_lm"]))  {
        _temp_23 = 0;
    }
    else {
        _temp_23 = 2.54431537659471 + placeholder_Normal_Log_Density((0.696753750969046 + 12.7345067596116 * indata["wavelethlh_firstorder_median_lm"]));
    }
    if (jmp.is_missing(indata["wavelethlh_glszm_largeareahighgr_tc"]))  {
        _temp_24 = 0;
    }
    else {
        _temp_24 = -15.6127399919531 + placeholder_Normal_Log_Density((-1.7538547027387 + 0.0000001657574947094 * indata["wavelethlh_glszm_largeareahighgr_tc"]));
    }
    if (jmp.is_missing(indata["wavelethlh_glszm_zoneentropy_tc"]))  {
        _temp_25 = 0;
    }
    else {
        _temp_25 = 1.38869060606963 + placeholder_Normal_Log_Density((-10.1127947729786 + 4.00959647295699 * indata["wavelethlh_glszm_zoneentropy_tc"]));
    }
    if (jmp.is_missing(indata["wavelethll_firstorder_kurtosis_mm"]))  {
        _temp_26 = 0;
    }
    else {
        _temp_26 = -0.0630495017190976 + placeholder_Normal_Log_Density((-4.46076059360572 + 0.938896995523434 * indata["wavelethll_firstorder_kurtosis_mm"]));
    }
    if (jmp.is_missing(indata["wavelethll_firstorder_skewness_lm"]))  {
        _temp_27 = 0;
    }
    else {
        _temp_27 = 2.17979912130199 + placeholder_Normal_Log_Density((0.634984316004437 + 8.84452940270967 * indata["wavelethll_firstorder_skewness_lm"]));
    }
    if (jmp.is_missing(indata["wavelethll_glszm_graylevelnonuni_fc"]))  {
        _temp_28 = 0;
    }
    else {
        _temp_28 = -5.87358100022121 + placeholder_Normal_Log_Density((-2.45031573064491 + 0.0028127827020426 * indata["wavelethll_glszm_graylevelnonuni_fc"]));
    }
    if (jmp.is_missing(indata["wavelethll_glszm_largearealowgra_lm"]))  {
        _temp_29 = 0;
    }
    else {
        _temp_29 = -9.90527073944226 + placeholder_Normal_Log_Density((-1.57948624256684 + 0.0000499109201013525 * indata["wavelethll_glszm_largearealowgra_lm"]));
    }
    if (jmp.is_missing(indata["wavelethll_glszm_smallareaemphas_fc"]))  {
        _temp_30 = 0;
    }
    else {
        _temp_30 = 3.86470676255455 + placeholder_Normal_Log_Density((-26.2950770183705 + 47.6892860976999 * indata["wavelethll_glszm_smallareaemphas_fc"]));
    }
    if (jmp.is_missing(indata["wavelethll_ngtdm_busyness_mm"]))  {
        _temp_31 = 0;
    }
    else {
        _temp_31 = -3.88411860577591 + placeholder_Normal_Log_Density((-2.00735674322587 + 0.0205659474827135 * indata["wavelethll_ngtdm_busyness_mm"]));
    }
    if (jmp.is_missing(indata["waveletlhh_firstorder_maximum_mm"]))  {
        _temp_32 = 0;
    }
    else {
        _temp_32 = -2.85313131418634 + placeholder_Normal_Log_Density((-5.26317888432478 + 0.0576634754220173 * indata["waveletlhh_firstorder_maximum_mm"]));
    }
    if (jmp.is_missing(indata["waveletlhh_firstorder_median_lm"]))  {
        _temp_33 = 0;
    }
    else {
        _temp_33 = 1.60255743076681 + placeholder_Normal_Log_Density((0.241663288374739 + 4.96571567325887 * indata["waveletlhh_firstorder_median_lm"]));
    }
    if (jmp.is_missing(indata["waveletlhh_glszm_smallareaemphas_mm"]))  {
        _temp_34 = 0;
    }
    else {
        _temp_34 = 3.45355496537128 + placeholder_Normal_Log_Density((-17.6669343323075 + 31.612574396161 * indata["waveletlhh_glszm_smallareaemphas_mm"]));
    }
    if (jmp.is_missing(indata["waveletlhl_firstorder_minimum_tc"]))  {
        _temp_35 = 0;
    }
    else {
        _temp_35 = -3.52185911077717 + placeholder_Normal_Log_Density((6.00317821857708 + 0.0295444576594472 * indata["waveletlhl_firstorder_minimum_tc"]));
    }
    if (jmp.is_missing(indata["waveletlhl_firstorder_skewness_fc"]))  {
        _temp_36 = 0;
    }
    else {
        _temp_36 = 2.33942548616718 + placeholder_Normal_Log_Density((3.52360750698096 + 10.3752741116441 * indata["waveletlhl_firstorder_skewness_fc"]));
    }
    if (jmp.is_missing(indata["waveletlhl_firstorder_skewness_tc"]))  {
        _temp_37 = 0;
    }
    else {
        _temp_37 = 2.15458993069675 + placeholder_Normal_Log_Density((-0.748984058622632 + 8.62435287137472 * indata["waveletlhl_firstorder_skewness_tc"]));
    }
    if (jmp.is_missing(indata["waveletlhl_glcm_clustershade_fc"]))  {
        _temp_38 = 0;
    }
    else {
        _temp_38 = -0.608586649003487 + placeholder_Normal_Log_Density((1.82095327785052 + 0.544119357510786 * indata["waveletlhl_glcm_clustershade_fc"]));
    }
    if (jmp.is_missing(indata["waveletlhl_glszm_zoneentropy_lm"]))  {
        _temp_39 = 0;
    }
    else {
        _temp_39 = 1.53342352773912 + placeholder_Normal_Log_Density((-27.4458050888349 + 4.63401437343416 * indata["waveletlhl_glszm_zoneentropy_lm"]));
    }
    if (jmp.is_missing(indata["waveletlhl_glszm_zoneentropy_mm"]))  {
        _temp_40 = 0;
    }
    else {
        _temp_40 = 1.57517275864608 + placeholder_Normal_Log_Density((-28.3237248589311 + 4.83157624258399 * indata["waveletlhl_glszm_zoneentropy_mm"]));
    }
    if (jmp.is_missing(indata["waveletllh_firstorder_minimum_fc"]))  {
        _temp_41 = 0;
    }
    else {
        _temp_41 = -3.48823397791469 + placeholder_Normal_Log_Density((7.38596767121293 + 0.0305547849766836 * indata["waveletllh_firstorder_minimum_fc"]));
    }
    if (jmp.is_missing(indata["waveletllh_glcm_correlation_mm"]))  {
        _temp_42 = 0;
    }
    else {
        _temp_42 = 3.75103276771794 + placeholder_Normal_Log_Density((-3.92855619151554 + 42.5650190853807 * indata["waveletllh_glcm_correlation_mm"]));
    }
    if (jmp.is_missing(indata["waveletllh_glcm_imc1_mm"]))  {
        _temp_43 = 0;
    }
    else {
        _temp_43 = 4.94210163225806 + placeholder_Normal_Log_Density((7.76436756015755 + 140.064304114231 * indata["waveletllh_glcm_imc1_mm"]));
    }
    if (jmp.is_missing(indata["waveletllh_gldm_smalldependencel_mm"]))  {
        _temp_44 = 0;
    }
    else {
        _temp_44 = 7.74926382754169 + placeholder_Normal_Log_Density((-2.63404145559744 + 2319.86396587305 * indata["waveletllh_gldm_smalldependencel_mm"]));
    }
    if (jmp.is_missing(indata["waveletllh_glszm_zoneentropy_fc"]))  {
        _temp_45 = 0;
    }
    else {
        _temp_45 = 2.05341859048501 + placeholder_Normal_Log_Density((-45.9324098263123 + 7.79450182168719 * indata["waveletllh_glszm_zoneentropy_fc"]));
    }
    if (jmp.is_missing(indata["waveletlll_glcm_clustershade_lm"]))  {
        _temp_46 = 0;
    }
    else {
        _temp_46 = -4.74202851674432 + placeholder_Normal_Log_Density((-1.8898965163899 + 0.0087209376624535 * indata["waveletlll_glcm_clustershade_lm"]));
    }
    if (jmp.is_missing(indata["waveletlll_glcm_idn_fc"]))  {
        _temp_47 = 0;
    }
    else {
        _temp_47 = 5.15215214500179 + placeholder_Normal_Log_Density((-162.348513549816 + 172.802987501405 * indata["waveletlll_glcm_idn_fc"]));
    }
    if (jmp.is_missing(indata["waveletlll_gldm_largedependenceh_lm"]))  {
        _temp_48 = 0;
    }
    else {
        _temp_48 = -7.25370444027467 + placeholder_Normal_Log_Density((-2.86683160373856 + 0.000707548457041187 * indata["waveletlll_gldm_largedependenceh_lm"]));
    }
    if (jmp.is_missing(indata["waveletlll_glszm_graylevelnonuni_fc"]))  {
        _temp_49 = 0;
    }
    else {
        _temp_49 = -5.28359597007616 + placeholder_Normal_Log_Density((-6.8327698057486 + 0.00507415144963656 * indata["waveletlll_glszm_graylevelnonuni_fc"]));
    }
    if (jmp.is_missing(indata["waveletlll_glszm_graylevelvarian_mm"]))  {
        _temp_50 = 0;
    }
    else {
        _temp_50 = -1.37760604528278 + placeholder_Normal_Log_Density((-4.65455358418508 + 0.252181542199976 * indata["waveletlll_glszm_graylevelvarian_mm"]));
    }
    if (jmp.is_missing(indata["waveletlll_ngtdm_busyness_tc"]))  {
        _temp_51 = 0;
    }
    else {
        _temp_51 = -0.612493937893744 + placeholder_Normal_Log_Density((-2.92924790845785 + 0.541997474095507 * indata["waveletlll_ngtdm_busyness_tc"]));
    }
    Naive_Score_Case_Naive_Score_Case = Math.exp((34.6277711877936 + _temp_0 + _temp_1 + _temp_2 + _temp_3 + _temp_4 + _temp_5 + _temp_6 + _temp_7 + _temp_8 + _temp_9 + _temp_10 + _temp_11 + _temp_12 + _temp_13 + _temp_14 + _temp_15 + _temp_16 + _temp_17 + _temp_18 + _temp_19 + _temp_20 + _temp_21 + _temp_22 + _temp_23 + _temp_24 + _temp_25 + _temp_26 + _temp_27 + _temp_28 + _temp_29 + _temp_30 + _temp_31 + _temp_32 + _temp_33 + _temp_34 + _temp_35 + _temp_36 + _temp_37 + _temp_38 + _temp_39 + _temp_40 + _temp_41 + _temp_42 + _temp_43 + _temp_44 + _temp_45 + _temp_46 + _temp_47 + _temp_48 + _temp_49 + _temp_50 + _temp_51));

    if (jmp.is_missing(indata["original_firstorder_minimum_fc"]))  {
        _temp_0 = 0;
    }
    else {
        _temp_0 = -1.40769939648407 + placeholder_Normal_Log_Density((-2.02998483174789 + 0.244705606642729 * indata["original_firstorder_minimum_fc"]));
    }
    if (jmp.is_missing(indata["original_glszm_smallareaemphasis_fc"]))  {
        _temp_1 = 0;
    }
    else {
        _temp_1 = 4.45430998046867 + placeholder_Normal_Log_Density((-50.7912884100366 + 85.996790902379 * indata["original_glszm_smallareaemphasis_fc"]));
    }
    if (jmp.is_missing(indata["original_shape_elongation_lm"]))  {
        _temp_2 = 0;
    }
    else {
        _temp_2 = 3.41891935472661 + placeholder_Normal_Log_Density((-15.7454626160224 + 30.5363981701623 * indata["original_shape_elongation_lm"]));
    }
    if (jmp.is_missing(indata["original_shape_sphericity_mm"]))  {
        _temp_3 = 0;
    }
    else {
        _temp_3 = 4.26831338745469 + placeholder_Normal_Log_Density((-30.1338872963532 + 71.4011080015905 * indata["original_shape_sphericity_mm"]));
    }
    if (jmp.is_missing(indata["v455_fc"]))  {
        _temp_4 = 0;
    }
    else {
        _temp_4 = 6.44336298478878 + placeholder_Normal_Log_Density((-38.1373828114704 + 628.51694255106 * indata["v455_fc"]));
    }
    if (jmp.is_missing(indata["v620_fc"]))  {
        _temp_5 = 0;
    }
    else {
        _temp_5 = 3.73856978889719 + placeholder_Normal_Log_Density((-18.7831418902843 + 42.0378241873373 * indata["v620_fc"]));
    }
    if (jmp.is_missing(indata["v810_mm"]))  {
        _temp_6 = 0;
    }
    else {
        _temp_6 = 3.47763123013267 + placeholder_Normal_Log_Density((-10.3087075302152 + 32.3829234593432 * indata["v810_mm"]));
    }
    if (jmp.is_missing(indata["wavelethhh_firstorder_minimum_fc"]))  {
        _temp_7 = 0;
    }
    else {
        _temp_7 = -2.30023168733928 + placeholder_Normal_Log_Density((5.3968013227573 + 0.100235617708753 * indata["wavelethhh_firstorder_minimum_fc"]));
    }
    if (jmp.is_missing(indata["wavelethhh_glcm_clustershade_mm"]))  {
        _temp_8 = 0;
    }
    else {
        _temp_8 = 6.04272594054893 + placeholder_Normal_Log_Density((0.0155069812939703 + 421.039199815673 * indata["wavelethhh_glcm_clustershade_mm"]));
    }
    if (jmp.is_missing(indata["wavelethhh_glcm_imc1_lm"]))  {
        _temp_9 = 0;
    }
    else {
        _temp_9 = 6.25214962802694 + placeholder_Normal_Log_Density((4.80194358381409 + 519.127557255513 * indata["wavelethhh_glcm_imc1_lm"]));
    }
    if (jmp.is_missing(indata["wavelethhh_glrlm_runvariance_mm"]))  {
        _temp_10 = 0;
    }
    else {
        _temp_10 = 3.10710652673805 + placeholder_Normal_Log_Density((-28.9277681041586 + 22.3562634744034 * indata["wavelethhh_glrlm_runvariance_mm"]));
    }
    if (jmp.is_missing(indata["wavelethhh_glszm_largeareahighgr_fc"]))  {
        _temp_11 = 0;
    }
    else {
        _temp_11 = -18.7357919582415 + placeholder_Normal_Log_Density((-1.50213564926338 + 0.0000000072970771583 * indata["wavelethhh_glszm_largeareahighgr_fc"]));
    }
    if (jmp.is_missing(indata["wavelethhl_firstorder_mean_mm"]))  {
        _temp_12 = 0;
    }
    else {
        _temp_12 = 2.70525857133555 + placeholder_Normal_Log_Density((-2.12059138194688 + 14.9581839481244 * indata["wavelethhl_firstorder_mean_mm"]));
    }
    if (jmp.is_missing(indata["wavelethhl_glcm_clusterprominenc_fc"]))  {
        _temp_13 = 0;
    }
    else {
        _temp_13 = 0.477363196165406 + placeholder_Normal_Log_Density((-2.43384308166953 + 1.61181874414564 * indata["wavelethhl_glcm_clusterprominenc_fc"]));
    }
    if (jmp.is_missing(indata["wavelethhl_glcm_correlation_mm"]))  {
        _temp_14 = 0;
    }
    else {
        _temp_14 = 4.86411657208708 + placeholder_Normal_Log_Density((-0.295777372538498 + 129.556434270757 * indata["wavelethhl_glcm_correlation_mm"]));
    }
    if (jmp.is_missing(indata["wavelethhl_glcm_imc1_mm"]))  {
        _temp_15 = 0;
    }
    else {
        _temp_15 = 5.81907677801971 + placeholder_Normal_Log_Density((5.54296132822202 + 336.661097186414 * indata["wavelethhl_glcm_imc1_mm"]));
    }
    if (jmp.is_missing(indata["wavelethhl_glcm_imc1_tc"]))  {
        _temp_16 = 0;
    }
    else {
        _temp_16 = 5.19405641049375 + placeholder_Normal_Log_Density((4.07020668327406 + 180.198029581348 * indata["wavelethhl_glcm_imc1_tc"]));
    }
    if (jmp.is_missing(indata["wavelethhl_gldm_smalldependencel_fc"]))  {
        _temp_17 = 0;
    }
    else {
        _temp_17 = 7.17009026198478 + placeholder_Normal_Log_Density((-2.69670067418405 + 1299.96193465301 * indata["wavelethhl_gldm_smalldependencel_fc"]));
    }
    if (jmp.is_missing(indata["wavelethhl_gldm_smalldependencel_mm"]))  {
        _temp_18 = 0;
    }
    else {
        _temp_18 = 6.52352511955377 + placeholder_Normal_Log_Density((-2.11527818503904 + 680.974676399154 * indata["wavelethhl_gldm_smalldependencel_mm"]));
    }
    if (jmp.is_missing(indata["wavelethhl_glrlm_longrunhighgray_mm"]))  {
        _temp_19 = 0;
    }
    else {
        _temp_19 = -2.63485330816982 + placeholder_Normal_Log_Density((-3.1085272491587 + 0.0717294907671517 * indata["wavelethhl_glrlm_longrunhighgray_mm"]));
    }
    if (jmp.is_missing(indata["wavelethhl_glszm_graylevelvarian_mm"]))  {
        _temp_20 = 0;
    }
    else {
        _temp_20 = 2.16538277287389 + placeholder_Normal_Log_Density((-19.4114310922896 + 8.71793826856346 * indata["wavelethhl_glszm_graylevelvarian_mm"]));
    }
    if (jmp.is_missing(indata["wavelethhl_glszm_largearealowgra_fc"]))  {
        _temp_21 = 0;
    }
    else {
        _temp_21 = -13.113651920005 + placeholder_Normal_Log_Density((-1.05012404177422 + 0.0000020174990251388 * indata["wavelethhl_glszm_largearealowgra_fc"]));
    }
    if (jmp.is_missing(indata["wavelethhl_glszm_smallareaemphas_fc"]))  {
        _temp_22 = 0;
    }
    else {
        _temp_22 = 3.70455119260605 + placeholder_Normal_Log_Density((-29.1577333483085 + 40.6318073684966 * indata["wavelethhl_glszm_smallareaemphas_fc"]));
    }
    if (jmp.is_missing(indata["wavelethlh_firstorder_median_lm"]))  {
        _temp_23 = 0;
    }
    else {
        _temp_23 = 2.58086805713443 + placeholder_Normal_Log_Density((0.837757219289228 + 13.2085990032057 * indata["wavelethlh_firstorder_median_lm"]));
    }
    if (jmp.is_missing(indata["wavelethlh_glszm_largeareahighgr_tc"]))  {
        _temp_24 = 0;
    }
    else {
        _temp_24 = -16.2484481795929 + placeholder_Normal_Log_Density((-1.17265243053341 + 0.0000000877785931694 * indata["wavelethlh_glszm_largeareahighgr_tc"]));
    }
    if (jmp.is_missing(indata["wavelethlh_glszm_zoneentropy_tc"]))  {
        _temp_25 = 0;
    }
    else {
        _temp_25 = 1.23494870747774 + placeholder_Normal_Log_Density((-8.69895433060391 + 3.4382021621213 * indata["wavelethlh_glszm_zoneentropy_tc"]));
    }
    if (jmp.is_missing(indata["wavelethll_firstorder_kurtosis_mm"]))  {
        _temp_26 = 0;
    }
    else {
        _temp_26 = -0.0159978298628314 + placeholder_Normal_Log_Density((-4.81561495058514 + 0.984129455748878 * indata["wavelethll_firstorder_kurtosis_mm"]));
    }
    if (jmp.is_missing(indata["wavelethll_firstorder_skewness_lm"]))  {
        _temp_27 = 0;
    }
    else {
        _temp_27 = 2.22294791043496 + placeholder_Normal_Log_Density((0.515044759253306 + 9.23451329862348 * indata["wavelethll_firstorder_skewness_lm"]));
    }
    if (jmp.is_missing(indata["wavelethll_glszm_graylevelnonuni_fc"]))  {
        _temp_28 = 0;
    }
    else {
        _temp_28 = -5.82341912579405 + placeholder_Normal_Log_Density((-2.35282767705945 + 0.00295747585600811 * indata["wavelethll_glszm_graylevelnonuni_fc"]));
    }
    if (jmp.is_missing(indata["wavelethll_glszm_largearealowgra_lm"]))  {
        _temp_29 = 0;
    }
    else {
        _temp_29 = -10.3949557796378 + placeholder_Normal_Log_Density((-1.11407733298584 + 0.0000305863789751379 * indata["wavelethll_glszm_largearealowgra_lm"]));
    }
    if (jmp.is_missing(indata["wavelethll_glszm_smallareaemphas_fc"]))  {
        _temp_30 = 0;
    }
    else {
        _temp_30 = 3.8749070750095 + placeholder_Normal_Log_Density((-26.7318974481636 + 48.1782211223414 * indata["wavelethll_glszm_smallareaemphas_fc"]));
    }
    if (jmp.is_missing(indata["wavelethll_ngtdm_busyness_mm"]))  {
        _temp_31 = 0;
    }
    else {
        _temp_31 = -3.76084689092138 + placeholder_Normal_Log_Density((-2.19706924493361 + 0.0232640299340326 * indata["wavelethll_ngtdm_busyness_mm"]));
    }
    if (jmp.is_missing(indata["waveletlhh_firstorder_maximum_mm"]))  {
        _temp_32 = 0;
    }
    else {
        _temp_32 = -2.91278319745801 + placeholder_Normal_Log_Density((-5.01659041948738 + 0.0543243239503139 * indata["waveletlhh_firstorder_maximum_mm"]));
    }
    if (jmp.is_missing(indata["waveletlhh_firstorder_median_lm"]))  {
        _temp_33 = 0;
    }
    else {
        _temp_33 = 1.5722574761603 + placeholder_Normal_Log_Density((0.407573385724469 + 4.81751134452207 * indata["waveletlhh_firstorder_median_lm"]));
    }
    if (jmp.is_missing(indata["waveletlhh_glszm_smallareaemphas_mm"]))  {
        _temp_34 = 0;
    }
    else {
        _temp_34 = 3.44307652207182 + placeholder_Normal_Log_Density((-17.5525558544917 + 31.2830532770337 * indata["waveletlhh_glszm_smallareaemphas_mm"]));
    }
    if (jmp.is_missing(indata["waveletlhl_firstorder_minimum_tc"]))  {
        _temp_35 = 0;
    }
    else {
        _temp_35 = -3.68257473265745 + placeholder_Normal_Log_Density((5.20345585743795 + 0.0251581159511748 * indata["waveletlhl_firstorder_minimum_tc"]));
    }
    if (jmp.is_missing(indata["waveletlhl_firstorder_skewness_fc"]))  {
        _temp_36 = 0;
    }
    else {
        _temp_36 = 2.25784725874086 + placeholder_Normal_Log_Density((3.15347025945541 + 9.56248144483017 * indata["waveletlhl_firstorder_skewness_fc"]));
    }
    if (jmp.is_missing(indata["waveletlhl_firstorder_skewness_tc"]))  {
        _temp_37 = 0;
    }
    else {
        _temp_37 = 2.109042275387 + placeholder_Normal_Log_Density((-0.514565252040332 + 8.24034552252078 * indata["waveletlhl_firstorder_skewness_tc"]));
    }
    if (jmp.is_missing(indata["waveletlhl_glcm_clustershade_fc"]))  {
        _temp_38 = 0;
    }
    else {
        _temp_38 = -0.703322748122837 + placeholder_Normal_Log_Density((1.69093633605036 + 0.494938014185228 * indata["waveletlhl_glcm_clustershade_fc"]));
    }
    if (jmp.is_missing(indata["waveletlhl_glszm_zoneentropy_lm"]))  {
        _temp_39 = 0;
    }
    else {
        _temp_39 = 1.44425080952749 + placeholder_Normal_Log_Density((-25.0463198498251 + 4.23867537775889 * indata["waveletlhl_glszm_zoneentropy_lm"]));
    }
    if (jmp.is_missing(indata["waveletlhl_glszm_zoneentropy_mm"]))  {
        _temp_40 = 0;
    }
    else {
        _temp_40 = 1.51688970045589 + placeholder_Normal_Log_Density((-26.7306182631875 + 4.55802629806035 * indata["waveletlhl_glszm_zoneentropy_mm"]));
    }
    if (jmp.is_missing(indata["waveletllh_firstorder_minimum_fc"]))  {
        _temp_41 = 0;
    }
    else {
        _temp_41 = -3.65385200986414 + placeholder_Normal_Log_Density((6.32291652106771 + 0.0258912032748904 * indata["waveletllh_firstorder_minimum_fc"]));
    }
    if (jmp.is_missing(indata["waveletllh_glcm_correlation_mm"]))  {
        _temp_42 = 0;
    }
    else {
        _temp_42 = 3.67331648930703 + placeholder_Normal_Log_Density((-3.73706487462513 + 39.3823004930548 * indata["waveletllh_glcm_correlation_mm"]));
    }
    if (jmp.is_missing(indata["waveletllh_glcm_imc1_mm"]))  {
        _temp_43 = 0;
    }
    else {
        _temp_43 = 4.82020658287596 + placeholder_Normal_Log_Density((7.08084043453635 + 123.990702490175 * indata["waveletllh_glcm_imc1_mm"]));
    }
    if (jmp.is_missing(indata["waveletllh_gldm_smalldependencel_mm"]))  {
        _temp_44 = 0;
    }
    else {
        _temp_44 = 7.70860795755376 + placeholder_Normal_Log_Density((-2.50253215920226 + 2227.43940883419 * indata["waveletllh_gldm_smalldependencel_mm"]));
    }
    if (jmp.is_missing(indata["waveletllh_glszm_zoneentropy_fc"]))  {
        _temp_45 = 0;
    }
    else {
        _temp_45 = 1.85310567037502 + placeholder_Normal_Log_Density((-37.556941766476 + 6.37960172828846 * indata["waveletllh_glszm_zoneentropy_fc"]));
    }
    if (jmp.is_missing(indata["waveletlll_glcm_clustershade_lm"]))  {
        _temp_46 = 0;
    }
    else {
        _temp_46 = -4.88425952849476 + placeholder_Normal_Log_Density((-1.80265854756653 + 0.00756472315062989 * indata["waveletlll_glcm_clustershade_lm"]));
    }
    if (jmp.is_missing(indata["waveletlll_glcm_idn_fc"]))  {
        _temp_47 = 0;
    }
    else {
        _temp_47 = 5.18820141715545 + placeholder_Normal_Log_Density((-168.171932039314 + 179.146053978873 * indata["waveletlll_glcm_idn_fc"]));
    }
    if (jmp.is_missing(indata["waveletlll_gldm_largedependenceh_lm"]))  {
        _temp_48 = 0;
    }
    else {
        _temp_48 = -7.14533406406757 + placeholder_Normal_Log_Density((-3.0719515851703 + 0.000788534763755032 * indata["waveletlll_gldm_largedependenceh_lm"]));
    }
    if (jmp.is_missing(indata["waveletlll_glszm_graylevelnonuni_fc"]))  {
        _temp_49 = 0;
    }
    else {
        _temp_49 = -5.26800558023833 + placeholder_Normal_Log_Density((-7.01227613871948 + 0.00515387932830395 * indata["waveletlll_glszm_graylevelnonuni_fc"]));
    }
    if (jmp.is_missing(indata["waveletlll_glszm_graylevelvarian_mm"]))  {
        _temp_50 = 0;
    }
    else {
        _temp_50 = -1.54685845808043 + placeholder_Normal_Log_Density((-4.02302556113297 + 0.212915808199448 * indata["waveletlll_glszm_graylevelvarian_mm"]));
    }
    if (jmp.is_missing(indata["waveletlll_ngtdm_busyness_tc"]))  {
        _temp_51 = 0;
    }
    else {
        _temp_51 = -0.552643489650962 + placeholder_Normal_Log_Density((-3.04057959159261 + 0.575426663625947 * indata["waveletlll_ngtdm_busyness_tc"]));
    }
    Naive_Score_Control_Naive_Score_Control = Math.exp((34.6241315113461 + _temp_0 + _temp_1 + _temp_2 + _temp_3 + _temp_4 + _temp_5 + _temp_6 + _temp_7 + _temp_8 + _temp_9 + _temp_10 + _temp_11 + _temp_12 + _temp_13 + _temp_14 + _temp_15 + _temp_16 + _temp_17 + _temp_18 + _temp_19 + _temp_20 + _temp_21 + _temp_22 + _temp_23 + _temp_24 + _temp_25 + _temp_26 + _temp_27 + _temp_28 + _temp_29 + _temp_30 + _temp_31 + _temp_32 + _temp_33 + _temp_34 + _temp_35 + _temp_36 + _temp_37 + _temp_38 + _temp_39 + _temp_40 + _temp_41 + _temp_42 + _temp_43 + _temp_44 + _temp_45 + _temp_46 + _temp_47 + _temp_48 + _temp_49 + _temp_50 + _temp_51));

    Naive_Score_Sum_1 = Naive_Score_Case + Naive_Score_Control;

    outdata["Naive Prob Case,!Naive Prob Case"] = Naive_Score_Case / Naive_Score_Sum_1;

    outdata["Naive Prob Control,!Naive Prob Control"] = Naive_Score_Control / Naive_Score_Sum_1;

    _temp_53[0] = indata["Naive Prob Case"];
    _temp_53[1] = indata["Naive Prob Control"];
    _temp_52 = jmp.max_array(2, _temp_53);
    switch (_temp_52) {
        case 0: {
            _temp_54 = "Case";
        }
        break;
        case 1: {
            _temp_54 = "Control";
        }
    }
    outdata["Naive Predicted Formula itype1,!Naive Predicted Formula itype1"] = _temp_54;

    return outdata["Naive Predicted Formula itype1,!Naive Predicted Formula itype1"];
};


module.exports = {
  getInputMetadata: getInputMetadata,
  getOutputMetadata : getOutputMetadata,
  getModelMetadata : getModelMetadata,
  score : score
};



