#include "jmp_score.h"
#include "jmp_lib.h"


/* ==================================================================
 Copyright(C) 2018 SAS Institute Inc.All rights reserved.
 
 Notice:
 The following permissions are granted provided that the
 above copyright and this notice appear in the score code and
 any related documentation. Permission to copy, modify
 and distribute the score code generated using
 JMP(R) software is limited to customers of SAS Institute Inc. ("SAS")
 and successive third parties, all without any warranty, express or
 implied, or any other obligation by SAS. SAS and all other SAS
 Institute Inc. product and service names are registered
 trademarks or trademarks of SAS Institute Inc. in the USA
 and other countries. Except as contained in this notice,
 the name of the SAS Institute Inc. and JMP shall not be used in
 the advertising or promotion of products or services without
 prior written authorization from SAS Institute Inc.
 ================================================================== */

/* C code generated by JMP v16.2.0 */

JMP_SCORE_API void fillMetadataCounts(COUNTS *mc) {
	mc->creatorLen       = 12;
	mc->modelNameLen     = 1;
	mc->predictedLen     = 7;
	mc->tableNameLen     = 17;
	mc->versionLen       = 7;
	mc->timestampLen     = 21;
	mc->maxInputNameLen  = 36;
	mc->maxOutputNameLen = 63;
	mc->numInputs        = 71;
	mc->numOutputs       = 3;
}

JMP_SCORE_API void fillModelMetadata(MODELMD *mm) {
	strcpy_safe(mm->creator,   "Naive Bayes"); 
	strcpy_safe(mm->modelName, ""); 
	strcpy_safe(mm->predicted, "itype1"); 
	strcpy_safe(mm->tableName, "final-2022-11-18"); 
	strcpy_safe(mm->version,   "16.2.0");
    strcpy_safe(mm->timestamp, "2023-02-13T04:45:32Z");
}

JMP_SCORE_API void fillInputMetadata(FIELDMD *fd) {
    strcpy_safe(fd[0].name, "original_firstorder_minimum_fc");
    fd[0].type = fnum_type;
    fd[0].datalen = 0;        

    strcpy_safe(fd[1].name, "original_glszm_smallareaemphasis_fc");
    fd[1].type = fnum_type;
    fd[1].datalen = 0;        

    strcpy_safe(fd[2].name, "original_shape_elongation_lm");
    fd[2].type = fnum_type;
    fd[2].datalen = 0;        

    strcpy_safe(fd[3].name, "original_shape_flatness_fc");
    fd[3].type = fnum_type;
    fd[3].datalen = 0;        

    strcpy_safe(fd[4].name, "original_shape_sphericity_fc");
    fd[4].type = fnum_type;
    fd[4].datalen = 0;        

    strcpy_safe(fd[5].name, "original_shape_sphericity_mm");
    fd[5].type = fnum_type;
    fd[5].datalen = 0;        

    strcpy_safe(fd[6].name, "v455_fc");
    fd[6].type = fnum_type;
    fd[6].datalen = 0;        

    strcpy_safe(fd[7].name, "v620_fc");
    fd[7].type = fnum_type;
    fd[7].datalen = 0;        

    strcpy_safe(fd[8].name, "v810_mm");
    fd[8].type = fnum_type;
    fd[8].datalen = 0;        

    strcpy_safe(fd[9].name, "wavelethhh_firstorder_minimum_fc");
    fd[9].type = fnum_type;
    fd[9].datalen = 0;        

    strcpy_safe(fd[10].name, "wavelethhh_firstorder_range_fc");
    fd[10].type = fnum_type;
    fd[10].datalen = 0;        

    strcpy_safe(fd[11].name, "wavelethhh_firstorder_skewness_fc");
    fd[11].type = fnum_type;
    fd[11].datalen = 0;        

    strcpy_safe(fd[12].name, "wavelethhh_glcm_clustershade_mm");
    fd[12].type = fnum_type;
    fd[12].datalen = 0;        

    strcpy_safe(fd[13].name, "wavelethhh_glcm_imc1_lm");
    fd[13].type = fnum_type;
    fd[13].datalen = 0;        

    strcpy_safe(fd[14].name, "wavelethhh_glrlm_runvariance_mm");
    fd[14].type = fnum_type;
    fd[14].datalen = 0;        

    strcpy_safe(fd[15].name, "wavelethhh_glszm_largeareahighgr_fc");
    fd[15].type = fnum_type;
    fd[15].datalen = 0;        

    strcpy_safe(fd[16].name, "wavelethhl_firstorder_mean_mm");
    fd[16].type = fnum_type;
    fd[16].datalen = 0;        

    strcpy_safe(fd[17].name, "wavelethhl_glcm_clusterprominenc_fc");
    fd[17].type = fnum_type;
    fd[17].datalen = 0;        

    strcpy_safe(fd[18].name, "wavelethhl_glcm_correlation_fc");
    fd[18].type = fnum_type;
    fd[18].datalen = 0;        

    strcpy_safe(fd[19].name, "wavelethhl_glcm_correlation_mm");
    fd[19].type = fnum_type;
    fd[19].datalen = 0;        

    strcpy_safe(fd[20].name, "wavelethhl_glcm_imc1_mm");
    fd[20].type = fnum_type;
    fd[20].datalen = 0;        

    strcpy_safe(fd[21].name, "wavelethhl_glcm_imc1_tc");
    fd[21].type = fnum_type;
    fd[21].datalen = 0;        

    strcpy_safe(fd[22].name, "wavelethhl_gldm_smalldependencel_fc");
    fd[22].type = fnum_type;
    fd[22].datalen = 0;        

    strcpy_safe(fd[23].name, "wavelethhl_gldm_smalldependencel_mm");
    fd[23].type = fnum_type;
    fd[23].datalen = 0;        

    strcpy_safe(fd[24].name, "wavelethhl_glrlm_longrunhighgray_mm");
    fd[24].type = fnum_type;
    fd[24].datalen = 0;        

    strcpy_safe(fd[25].name, "wavelethhl_glszm_graylevelvarian_mm");
    fd[25].type = fnum_type;
    fd[25].datalen = 0;        

    strcpy_safe(fd[26].name, "wavelethhl_glszm_largearealowgra_fc");
    fd[26].type = fnum_type;
    fd[26].datalen = 0;        

    strcpy_safe(fd[27].name, "wavelethhl_glszm_smallareaemphas_fc");
    fd[27].type = fnum_type;
    fd[27].datalen = 0;        

    strcpy_safe(fd[28].name, "wavelethhl_ngtdm_strength_fc");
    fd[28].type = fnum_type;
    fd[28].datalen = 0;        

    strcpy_safe(fd[29].name, "wavelethlh_firstorder_median_fc");
    fd[29].type = fnum_type;
    fd[29].datalen = 0;        

    strcpy_safe(fd[30].name, "wavelethlh_firstorder_median_lm");
    fd[30].type = fnum_type;
    fd[30].datalen = 0;        

    strcpy_safe(fd[31].name, "wavelethlh_glszm_largeareahighgr_tc");
    fd[31].type = fnum_type;
    fd[31].datalen = 0;        

    strcpy_safe(fd[32].name, "wavelethlh_glszm_zoneentropy_tc");
    fd[32].type = fnum_type;
    fd[32].datalen = 0;        

    strcpy_safe(fd[33].name, "wavelethll_firstorder_kurtosis_mm");
    fd[33].type = fnum_type;
    fd[33].datalen = 0;        

    strcpy_safe(fd[34].name, "wavelethll_firstorder_skewness_lm");
    fd[34].type = fnum_type;
    fd[34].datalen = 0;        

    strcpy_safe(fd[35].name, "wavelethll_glszm_graylevelnonuni_fc");
    fd[35].type = fnum_type;
    fd[35].datalen = 0;        

    strcpy_safe(fd[36].name, "wavelethll_glszm_largearealowgra_lm");
    fd[36].type = fnum_type;
    fd[36].datalen = 0;        

    strcpy_safe(fd[37].name, "wavelethll_glszm_smallareaemphas_fc");
    fd[37].type = fnum_type;
    fd[37].datalen = 0;        

    strcpy_safe(fd[38].name, "wavelethll_ngtdm_busyness_mm");
    fd[38].type = fnum_type;
    fd[38].datalen = 0;        

    strcpy_safe(fd[39].name, "waveletlhh_firstorder_kurtosis_fc");
    fd[39].type = fnum_type;
    fd[39].datalen = 0;        

    strcpy_safe(fd[40].name, "waveletlhh_firstorder_maximum_fc");
    fd[40].type = fnum_type;
    fd[40].datalen = 0;        

    strcpy_safe(fd[41].name, "waveletlhh_firstorder_maximum_mm");
    fd[41].type = fnum_type;
    fd[41].datalen = 0;        

    strcpy_safe(fd[42].name, "waveletlhh_firstorder_mean_fc");
    fd[42].type = fnum_type;
    fd[42].datalen = 0;        

    strcpy_safe(fd[43].name, "waveletlhh_firstorder_median_fc");
    fd[43].type = fnum_type;
    fd[43].datalen = 0;        

    strcpy_safe(fd[44].name, "waveletlhh_firstorder_median_lm");
    fd[44].type = fnum_type;
    fd[44].datalen = 0;        

    strcpy_safe(fd[45].name, "waveletlhh_glszm_largearealowgra_fc");
    fd[45].type = fnum_type;
    fd[45].datalen = 0;        

    strcpy_safe(fd[46].name, "waveletlhh_glszm_smallareaemphas_fc");
    fd[46].type = fnum_type;
    fd[46].datalen = 0;        

    strcpy_safe(fd[47].name, "waveletlhh_glszm_smallareaemphas_mm");
    fd[47].type = fnum_type;
    fd[47].datalen = 0;        

    strcpy_safe(fd[48].name, "waveletlhl_firstorder_minimum_tc");
    fd[48].type = fnum_type;
    fd[48].datalen = 0;        

    strcpy_safe(fd[49].name, "waveletlhl_firstorder_skewness_fc");
    fd[49].type = fnum_type;
    fd[49].datalen = 0;        

    strcpy_safe(fd[50].name, "waveletlhl_firstorder_skewness_tc");
    fd[50].type = fnum_type;
    fd[50].datalen = 0;        

    strcpy_safe(fd[51].name, "waveletlhl_glcm_clustershade_fc");
    fd[51].type = fnum_type;
    fd[51].datalen = 0;        

    strcpy_safe(fd[52].name, "waveletlhl_glcm_imc1_fc");
    fd[52].type = fnum_type;
    fd[52].datalen = 0;        

    strcpy_safe(fd[53].name, "waveletlhl_glszm_smallarealowgra_fc");
    fd[53].type = fnum_type;
    fd[53].datalen = 0;        

    strcpy_safe(fd[54].name, "waveletlhl_glszm_zoneentropy_lm");
    fd[54].type = fnum_type;
    fd[54].datalen = 0;        

    strcpy_safe(fd[55].name, "waveletlhl_glszm_zoneentropy_mm");
    fd[55].type = fnum_type;
    fd[55].datalen = 0;        

    strcpy_safe(fd[56].name, "waveletllh_firstorder_minimum_fc");
    fd[56].type = fnum_type;
    fd[56].datalen = 0;        

    strcpy_safe(fd[57].name, "waveletllh_glcm_correlation_mm");
    fd[57].type = fnum_type;
    fd[57].datalen = 0;        

    strcpy_safe(fd[58].name, "waveletllh_glcm_imc1_mm");
    fd[58].type = fnum_type;
    fd[58].datalen = 0;        

    strcpy_safe(fd[59].name, "waveletllh_gldm_smalldependencel_mm");
    fd[59].type = fnum_type;
    fd[59].datalen = 0;        

    strcpy_safe(fd[60].name, "waveletllh_glszm_smallarealowgra_fc");
    fd[60].type = fnum_type;
    fd[60].datalen = 0;        

    strcpy_safe(fd[61].name, "waveletllh_glszm_zoneentropy_fc");
    fd[61].type = fnum_type;
    fd[61].datalen = 0;        

    strcpy_safe(fd[62].name, "waveletlll_glcm_clustershade_lm");
    fd[62].type = fnum_type;
    fd[62].datalen = 0;        

    strcpy_safe(fd[63].name, "waveletlll_glcm_idn_fc");
    fd[63].type = fnum_type;
    fd[63].datalen = 0;        

    strcpy_safe(fd[64].name, "waveletlll_glcm_imc2_fc");
    fd[64].type = fnum_type;
    fd[64].datalen = 0;        

    strcpy_safe(fd[65].name, "waveletlll_gldm_largedependenceh_lm");
    fd[65].type = fnum_type;
    fd[65].datalen = 0;        

    strcpy_safe(fd[66].name, "waveletlll_glszm_graylevelnonuni_fc");
    fd[66].type = fnum_type;
    fd[66].datalen = 0;        

    strcpy_safe(fd[67].name, "waveletlll_glszm_graylevelvarian_mm");
    fd[67].type = fnum_type;
    fd[67].datalen = 0;        

    strcpy_safe(fd[68].name, "waveletlll_ngtdm_busyness_tc");
    fd[68].type = fnum_type;
    fd[68].datalen = 0;        

    strcpy_safe(fd[69].name, "Naive Prob Case");
    fd[69].type = fnum_type;
    fd[69].datalen = 0;        

    strcpy_safe(fd[70].name, "Naive Prob Control");
    fd[70].type = fnum_type;
    fd[70].datalen = 0;        
}

JMP_SCORE_API void fillOutputMetadata(FIELDMD *fd) {
    strcpy_safe(fd[0].name, "Naive Prob Case,!Naive Prob Case");
    fd[0].type = fnum_type;
    fd[0].datalen = 0;        

    strcpy_safe(fd[1].name, "Naive Prob Control,!Naive Prob Control");
    fd[1].type = fnum_type;
    fd[1].datalen = 0;        

    strcpy_safe(fd[2].name, "Naive Predicted Formula itype1,!Naive Predicted Formula itype1");
    fd[2].type = char_type;
    fd[2].datalen = 8;        
}

// Original name was: 'original_firstorder_minimum_fc'
#define ORIGINAL_FIRSTORDER_MINIMUM_FC      indata[0].data.fnum
// Original name was: 'original_glszm_smallareaemphasis_fc'
#define ORIGINAL_GLSZM_SMALLAREAEMPHASIS_FC indata[1].data.fnum
// Original name was: 'original_shape_elongation_lm'
#define ORIGINAL_SHAPE_ELONGATION_LM        indata[2].data.fnum
// Original name was: 'original_shape_flatness_fc'
#define ORIGINAL_SHAPE_FLATNESS_FC          indata[3].data.fnum
// Original name was: 'original_shape_sphericity_fc'
#define ORIGINAL_SHAPE_SPHERICITY_FC        indata[4].data.fnum
// Original name was: 'original_shape_sphericity_mm'
#define ORIGINAL_SHAPE_SPHERICITY_MM        indata[5].data.fnum
// Original name was: 'v455_fc'
#define V455_FC                             indata[6].data.fnum
// Original name was: 'v620_fc'
#define V620_FC                             indata[7].data.fnum
// Original name was: 'v810_mm'
#define V810_MM                             indata[8].data.fnum
// Original name was: 'wavelethhh_firstorder_minimum_fc'
#define WAVELETHHH_FIRSTORDER_MINIMUM_FC    indata[9].data.fnum
// Original name was: 'wavelethhh_firstorder_range_fc'
#define WAVELETHHH_FIRSTORDER_RANGE_FC      indata[10].data.fnum
// Original name was: 'wavelethhh_firstorder_skewness_fc'
#define WAVELETHHH_FIRSTORDER_SKEWNESS_FC   indata[11].data.fnum
// Original name was: 'wavelethhh_glcm_clustershade_mm'
#define WAVELETHHH_GLCM_CLUSTERSHADE_MM     indata[12].data.fnum
// Original name was: 'wavelethhh_glcm_imc1_lm'
#define WAVELETHHH_GLCM_IMC1_LM             indata[13].data.fnum
// Original name was: 'wavelethhh_glrlm_runvariance_mm'
#define WAVELETHHH_GLRLM_RUNVARIANCE_MM     indata[14].data.fnum
// Original name was: 'wavelethhh_glszm_largeareahighgr_fc'
#define WAVELETHHH_GLSZM_LARGEAREAHIGHGR_FC indata[15].data.fnum
// Original name was: 'wavelethhl_firstorder_mean_mm'
#define WAVELETHHL_FIRSTORDER_MEAN_MM       indata[16].data.fnum
// Original name was: 'wavelethhl_glcm_clusterprominenc_fc'
#define WAVELETHHL_GLCM_CLUSTERPROMINENC_FC indata[17].data.fnum
// Original name was: 'wavelethhl_glcm_correlation_fc'
#define WAVELETHHL_GLCM_CORRELATION_FC      indata[18].data.fnum
// Original name was: 'wavelethhl_glcm_correlation_mm'
#define WAVELETHHL_GLCM_CORRELATION_MM      indata[19].data.fnum
// Original name was: 'wavelethhl_glcm_imc1_mm'
#define WAVELETHHL_GLCM_IMC1_MM             indata[20].data.fnum
// Original name was: 'wavelethhl_glcm_imc1_tc'
#define WAVELETHHL_GLCM_IMC1_TC             indata[21].data.fnum
// Original name was: 'wavelethhl_gldm_smalldependencel_fc'
#define WAVELETHHL_GLDM_SMALLDEPENDENCEL_FC indata[22].data.fnum
// Original name was: 'wavelethhl_gldm_smalldependencel_mm'
#define WAVELETHHL_GLDM_SMALLDEPENDENCEL_MM indata[23].data.fnum
// Original name was: 'wavelethhl_glrlm_longrunhighgray_mm'
#define WAVELETHHL_GLRLM_LONGRUNHIGHGRAY_MM indata[24].data.fnum
// Original name was: 'wavelethhl_glszm_graylevelvarian_mm'
#define WAVELETHHL_GLSZM_GRAYLEVELVARIAN_MM indata[25].data.fnum
// Original name was: 'wavelethhl_glszm_largearealowgra_fc'
#define WAVELETHHL_GLSZM_LARGEAREALOWGRA_FC indata[26].data.fnum
// Original name was: 'wavelethhl_glszm_smallareaemphas_fc'
#define WAVELETHHL_GLSZM_SMALLAREAEMPHAS_FC indata[27].data.fnum
// Original name was: 'wavelethhl_ngtdm_strength_fc'
#define WAVELETHHL_NGTDM_STRENGTH_FC        indata[28].data.fnum
// Original name was: 'wavelethlh_firstorder_median_fc'
#define WAVELETHLH_FIRSTORDER_MEDIAN_FC     indata[29].data.fnum
// Original name was: 'wavelethlh_firstorder_median_lm'
#define WAVELETHLH_FIRSTORDER_MEDIAN_LM     indata[30].data.fnum
// Original name was: 'wavelethlh_glszm_largeareahighgr_tc'
#define WAVELETHLH_GLSZM_LARGEAREAHIGHGR_TC indata[31].data.fnum
// Original name was: 'wavelethlh_glszm_zoneentropy_tc'
#define WAVELETHLH_GLSZM_ZONEENTROPY_TC     indata[32].data.fnum
// Original name was: 'wavelethll_firstorder_kurtosis_mm'
#define WAVELETHLL_FIRSTORDER_KURTOSIS_MM   indata[33].data.fnum
// Original name was: 'wavelethll_firstorder_skewness_lm'
#define WAVELETHLL_FIRSTORDER_SKEWNESS_LM   indata[34].data.fnum
// Original name was: 'wavelethll_glszm_graylevelnonuni_fc'
#define WAVELETHLL_GLSZM_GRAYLEVELNONUNI_FC indata[35].data.fnum
// Original name was: 'wavelethll_glszm_largearealowgra_lm'
#define WAVELETHLL_GLSZM_LARGEAREALOWGRA_LM indata[36].data.fnum
// Original name was: 'wavelethll_glszm_smallareaemphas_fc'
#define WAVELETHLL_GLSZM_SMALLAREAEMPHAS_FC indata[37].data.fnum
// Original name was: 'wavelethll_ngtdm_busyness_mm'
#define WAVELETHLL_NGTDM_BUSYNESS_MM        indata[38].data.fnum
// Original name was: 'waveletlhh_firstorder_kurtosis_fc'
#define WAVELETLHH_FIRSTORDER_KURTOSIS_FC   indata[39].data.fnum
// Original name was: 'waveletlhh_firstorder_maximum_fc'
#define WAVELETLHH_FIRSTORDER_MAXIMUM_FC    indata[40].data.fnum
// Original name was: 'waveletlhh_firstorder_maximum_mm'
#define WAVELETLHH_FIRSTORDER_MAXIMUM_MM    indata[41].data.fnum
// Original name was: 'waveletlhh_firstorder_mean_fc'
#define WAVELETLHH_FIRSTORDER_MEAN_FC       indata[42].data.fnum
// Original name was: 'waveletlhh_firstorder_median_fc'
#define WAVELETLHH_FIRSTORDER_MEDIAN_FC     indata[43].data.fnum
// Original name was: 'waveletlhh_firstorder_median_lm'
#define WAVELETLHH_FIRSTORDER_MEDIAN_LM     indata[44].data.fnum
// Original name was: 'waveletlhh_glszm_largearealowgra_fc'
#define WAVELETLHH_GLSZM_LARGEAREALOWGRA_FC indata[45].data.fnum
// Original name was: 'waveletlhh_glszm_smallareaemphas_fc'
#define WAVELETLHH_GLSZM_SMALLAREAEMPHAS_FC indata[46].data.fnum
// Original name was: 'waveletlhh_glszm_smallareaemphas_mm'
#define WAVELETLHH_GLSZM_SMALLAREAEMPHAS_MM indata[47].data.fnum
// Original name was: 'waveletlhl_firstorder_minimum_tc'
#define WAVELETLHL_FIRSTORDER_MINIMUM_TC    indata[48].data.fnum
// Original name was: 'waveletlhl_firstorder_skewness_fc'
#define WAVELETLHL_FIRSTORDER_SKEWNESS_FC   indata[49].data.fnum
// Original name was: 'waveletlhl_firstorder_skewness_tc'
#define WAVELETLHL_FIRSTORDER_SKEWNESS_TC   indata[50].data.fnum
// Original name was: 'waveletlhl_glcm_clustershade_fc'
#define WAVELETLHL_GLCM_CLUSTERSHADE_FC     indata[51].data.fnum
// Original name was: 'waveletlhl_glcm_imc1_fc'
#define WAVELETLHL_GLCM_IMC1_FC             indata[52].data.fnum
// Original name was: 'waveletlhl_glszm_smallarealowgra_fc'
#define WAVELETLHL_GLSZM_SMALLAREALOWGRA_FC indata[53].data.fnum
// Original name was: 'waveletlhl_glszm_zoneentropy_lm'
#define WAVELETLHL_GLSZM_ZONEENTROPY_LM     indata[54].data.fnum
// Original name was: 'waveletlhl_glszm_zoneentropy_mm'
#define WAVELETLHL_GLSZM_ZONEENTROPY_MM     indata[55].data.fnum
// Original name was: 'waveletllh_firstorder_minimum_fc'
#define WAVELETLLH_FIRSTORDER_MINIMUM_FC    indata[56].data.fnum
// Original name was: 'waveletllh_glcm_correlation_mm'
#define WAVELETLLH_GLCM_CORRELATION_MM      indata[57].data.fnum
// Original name was: 'waveletllh_glcm_imc1_mm'
#define WAVELETLLH_GLCM_IMC1_MM             indata[58].data.fnum
// Original name was: 'waveletllh_gldm_smalldependencel_mm'
#define WAVELETLLH_GLDM_SMALLDEPENDENCEL_MM indata[59].data.fnum
// Original name was: 'waveletllh_glszm_smallarealowgra_fc'
#define WAVELETLLH_GLSZM_SMALLAREALOWGRA_FC indata[60].data.fnum
// Original name was: 'waveletllh_glszm_zoneentropy_fc'
#define WAVELETLLH_GLSZM_ZONEENTROPY_FC     indata[61].data.fnum
// Original name was: 'waveletlll_glcm_clustershade_lm'
#define WAVELETLLL_GLCM_CLUSTERSHADE_LM     indata[62].data.fnum
// Original name was: 'waveletlll_glcm_idn_fc'
#define WAVELETLLL_GLCM_IDN_FC              indata[63].data.fnum
// Original name was: 'waveletlll_glcm_imc2_fc'
#define WAVELETLLL_GLCM_IMC2_FC             indata[64].data.fnum
// Original name was: 'waveletlll_gldm_largedependenceh_lm'
#define WAVELETLLL_GLDM_LARGEDEPENDENCEH_LM indata[65].data.fnum
// Original name was: 'waveletlll_glszm_graylevelnonuni_fc'
#define WAVELETLLL_GLSZM_GRAYLEVELNONUNI_FC indata[66].data.fnum
// Original name was: 'waveletlll_glszm_graylevelvarian_mm'
#define WAVELETLLL_GLSZM_GRAYLEVELVARIAN_MM indata[67].data.fnum
// Original name was: 'waveletlll_ngtdm_busyness_tc'
#define WAVELETLLL_NGTDM_BUSYNESS_TC        indata[68].data.fnum
// Original name was: 'Naive Prob Case'
#define NAIVE_PROB_CASE                     indata[69].data.fnum
// Original name was: 'Naive Prob Control'
#define NAIVE_PROB_CONTROL                  indata[70].data.fnum

// Original name was: 'Naive Prob Case,!Naive Prob Case'
#define NAIVE_PROB_CASE_NAIVE_PROB_CASE                                outdata[0].data.fnum
// Original name was: 'Naive Prob Control,!Naive Prob Control'
#define NAIVE_PROB_CONTROL_NAIVE_PROB_CONTROL                          outdata[1].data.fnum
// Original name was: 'Naive Predicted Formula itype1,!Naive Predicted Formula itype1'
#define NAIVE_PREDICTED_FORMULA_ITYPE1_NAIVE_PREDICTED_FORMULA_ITYPE1  outdata[2].data.str  // max string length: 7

JMP_SCORE_API void score(PARM *indata, PARM *outdata) {
    // Original name was: 'Naive Score Control'
    double Naive_Score_Control;
    // Original name was: 'Naive Score Case'
    double Naive_Score_Case;
    // Original name was: 'Naive Score Case,!Naive Score Case'
    double Naive_Score_Case_Naive_Score_Case;
    // Original name was: 'Naive Score Control,!Naive Score Control'
    double Naive_Score_Control_Naive_Score_Control;
    // Original name was: 'Naive Score Sum_1'
    double Naive_Score_Sum_1;
    double _temp_0 = MISSING;
    double _temp_1 = MISSING;
    double _temp_2 = MISSING;
    double _temp_3 = MISSING;
    double _temp_4 = MISSING;
    double _temp_5 = MISSING;
    double _temp_6 = MISSING;
    double _temp_7 = MISSING;
    double _temp_8 = MISSING;
    double _temp_9 = MISSING;
    double _temp_10 = MISSING;
    double _temp_11 = MISSING;
    double _temp_12 = MISSING;
    double _temp_13 = MISSING;
    double _temp_14 = MISSING;
    double _temp_15 = MISSING;
    double _temp_16 = MISSING;
    double _temp_17 = MISSING;
    double _temp_18 = MISSING;
    double _temp_19 = MISSING;
    double _temp_20 = MISSING;
    double _temp_21 = MISSING;
    double _temp_22 = MISSING;
    double _temp_23 = MISSING;
    double _temp_24 = MISSING;
    double _temp_25 = MISSING;
    double _temp_26 = MISSING;
    double _temp_27 = MISSING;
    double _temp_28 = MISSING;
    double _temp_29 = MISSING;
    double _temp_30 = MISSING;
    double _temp_31 = MISSING;
    double _temp_32 = MISSING;
    double _temp_33 = MISSING;
    double _temp_34 = MISSING;
    double _temp_35 = MISSING;
    double _temp_36 = MISSING;
    double _temp_37 = MISSING;
    double _temp_38 = MISSING;
    double _temp_39 = MISSING;
    double _temp_40 = MISSING;
    double _temp_41 = MISSING;
    double _temp_42 = MISSING;
    double _temp_43 = MISSING;
    double _temp_44 = MISSING;
    double _temp_45 = MISSING;
    double _temp_46 = MISSING;
    double _temp_47 = MISSING;
    double _temp_48 = MISSING;
    double _temp_49 = MISSING;
    double _temp_50 = MISSING;
    double _temp_51 = MISSING;
    int _temp_52;
    double _temp_53[2];
    char * _temp_54 = "";

    if (jmp_is_missing(WAVELETHHL_GLCM_CLUSTERPROMINENC_FC))  {
        _temp_0 = 0;
    }
    else {
        _temp_0 = placeholder_Normal_Log_Density(((WAVELETHHL_GLCM_CLUSTERPROMINENC_FC - 1.5099980010219) / 0.620417155236684)) - -0.477363196165406;
    }
    if (jmp_is_missing(WAVELETHHL_GLSZM_LARGEAREALOWGRA_FC))  {
        _temp_1 = 0;
    }
    else {
        _temp_1 = placeholder_Normal_Log_Density(((WAVELETHHL_GLSZM_LARGEAREALOWGRA_FC - 520507.831076642) / 495663.188700286)) - 13.113651920005;
    }
    if (jmp_is_missing(WAVELETLLH_GLSZM_ZONEENTROPY_FC))  {
        _temp_2 = 0;
    }
    else {
        _temp_2 = placeholder_Normal_Log_Density(((WAVELETLLH_GLSZM_ZONEENTROPY_FC - 5.88703548686131) / 0.156749597011016)) - -1.85310567037502;
    }
    if (jmp_is_missing(ORIGINAL_GLSZM_SMALLAREAEMPHASIS_FC))  {
        _temp_3 = 0;
    }
    else {
        _temp_3 = placeholder_Normal_Log_Density(((ORIGINAL_GLSZM_SMALLAREAEMPHASIS_FC - 0.590618415839416) / 0.0116283408893149)) - -4.45430998046867;
    }
    if (jmp_is_missing(V620_FC))  {
        _temp_4 = 0;
    }
    else {
        _temp_4 = placeholder_Normal_Log_Density(((V620_FC - 0.446815272992701) / 0.0237881008194811)) - -3.73856978889719;
    }
    if (jmp_is_missing(WAVELETHLL_GLSZM_GRAYLEVELNONUNI_FC))  {
        _temp_5 = 0;
    }
    else {
        _temp_5 = placeholder_Normal_Log_Density(((WAVELETHLL_GLSZM_GRAYLEVELNONUNI_FC - 795.55262379562) / 338.126175389902)) - 5.82341912579405;
    }
    if (jmp_is_missing(WAVELETLLL_GLCM_IMC2_FC))  {
        _temp_6 = 0;
    }
    else {
        _temp_6 = placeholder_Normal_Log_Density(((WAVELETLLL_GLCM_IMC2_FC - 0.843224175620438) / 0.0329402230864912)) - -3.41306078174522;
    }
    if (jmp_is_missing(WAVELETHLL_GLSZM_SMALLAREAEMPHAS_FC))  {
        _temp_7 = 0;
    }
    else {
        _temp_7 = placeholder_Normal_Log_Density(((WAVELETHLL_GLSZM_SMALLAREAEMPHAS_FC - 0.554854389087591) / 0.0207562665599597)) - -3.8749070750095;
    }
    if (jmp_is_missing(WAVELETLLH_FIRSTORDER_MINIMUM_FC))  {
        _temp_8 = 0;
    }
    else {
        _temp_8 = placeholder_Normal_Log_Density(((WAVELETLLH_FIRSTORDER_MINIMUM_FC - -244.210995291971) / 38.6231566521983)) - 3.65385200986414;
    }
    if (jmp_is_missing(WAVELETLLL_GLSZM_GRAYLEVELNONUNI_FC))  {
        _temp_9 = 0;
    }
    else {
        _temp_9 = placeholder_Normal_Log_Density(((WAVELETLLL_GLSZM_GRAYLEVELNONUNI_FC - 1360.58213474453) / 194.028601816155)) - 5.26800558023833;
    }
    if (jmp_is_missing(V455_FC))  {
        _temp_10 = 0;
    }
    else {
        _temp_10 = placeholder_Normal_Log_Density(((V455_FC - 0.0606783687591241) / 0.00159104700653119)) - -6.44336298478878;
    }
    if (jmp_is_missing(WAVELETHHL_GLSZM_SMALLAREAEMPHAS_FC))  {
        _temp_11 = 0;
    }
    else {
        _temp_11 = placeholder_Normal_Log_Density(((WAVELETHHL_GLSZM_SMALLAREAEMPHAS_FC - 0.717608574087591) / 0.0246112606050436)) - -3.70455119260605;
    }
    if (jmp_is_missing(WAVELETLHH_FIRSTORDER_KURTOSIS_FC))  {
        _temp_12 = 0;
    }
    else {
        _temp_12 = placeholder_Normal_Log_Density(((WAVELETLHH_FIRSTORDER_KURTOSIS_FC - 4.45406231751825) / 0.531279411152576)) - -0.632467198106385;
    }
    if (jmp_is_missing(WAVELETLHH_GLSZM_LARGEAREALOWGRA_FC))  {
        _temp_13 = 0;
    }
    else {
        _temp_13 = placeholder_Normal_Log_Density(((WAVELETLHH_GLSZM_LARGEAREALOWGRA_FC - 40776.2445751825) / 23391.4095420044)) - 10.0601241203535;
    }
    if (jmp_is_missing(WAVELETLHH_FIRSTORDER_MAXIMUM_FC))  {
        _temp_14 = 0;
    }
    else {
        _temp_14 = placeholder_Normal_Log_Density(((WAVELETLHH_FIRSTORDER_MAXIMUM_FC - 135.304948007299) / 27.2631864228882)) - 3.30553730949187;
    }
    if (jmp_is_missing(WAVELETHHL_GLCM_CORRELATION_FC))  {
        _temp_15 = 0;
    }
    else {
        _temp_15 = placeholder_Normal_Log_Density(((WAVELETHHL_GLCM_CORRELATION_FC - 0.0262412372627737) / 0.00940371431068138)) - -4.66665052831902;
    }
    if (jmp_is_missing(WAVELETHHH_GLSZM_LARGEAREAHIGHGR_FC))  {
        _temp_16 = 0;
    }
    else {
        _temp_16 = placeholder_Normal_Log_Density(((WAVELETHHH_GLSZM_LARGEAREAHIGHGR_FC - 205854428.653285) / 137041171.184661)) - 18.7357919582415;
    }
    if (jmp_is_missing(WAVELETLLL_GLCM_IDN_FC))  {
        _temp_17 = 0;
    }
    else {
        _temp_17 = placeholder_Normal_Log_Density(((WAVELETLLL_GLCM_IDN_FC - 0.938742039270073) / 0.00558203754863577)) - -5.18820141715545;
    }
    if (jmp_is_missing(WAVELETLLH_GLSZM_SMALLAREALOWGRA_FC))  {
        _temp_18 = 0;
    }
    else {
        _temp_18 = placeholder_Normal_Log_Density(((WAVELETLLH_GLSZM_SMALLAREALOWGRA_FC - 0.00734470105839416) / 0.00231595916367596)) - -6.06793135169111;
    }
    if (jmp_is_missing(WAVELETHHL_GLDM_SMALLDEPENDENCEL_FC))  {
        _temp_19 = 0;
    }
    else {
        _temp_19 = placeholder_Normal_Log_Density(((WAVELETHHL_GLDM_SMALLDEPENDENCEL_FC - 0.00207444587591241) / 0.000769253293764271)) - -7.17009026198478;
    }
    if (jmp_is_missing(WAVELETLHL_FIRSTORDER_SKEWNESS_FC))  {
        _temp_20 = 0;
    }
    else {
        _temp_20 = placeholder_Normal_Log_Density(((WAVELETLHL_FIRSTORDER_SKEWNESS_FC - -0.329775307554745) / 0.104575366317771)) - -2.25784725874085;
    }
    if (jmp_is_missing(ORIGINAL_FIRSTORDER_MINIMUM_FC))  {
        _temp_21 = 0;
    }
    else {
        _temp_21 = placeholder_Normal_Log_Density(((ORIGINAL_FIRSTORDER_MINIMUM_FC - 8.2956204379562) / 4.08654306584811)) - 1.40769939648407;
    }
    if (jmp_is_missing(WAVELETLHL_GLCM_CLUSTERSHADE_FC))  {
        _temp_22 = 0;
    }
    else {
        _temp_22 = placeholder_Normal_Log_Density(((WAVELETLHL_GLCM_CLUSTERSHADE_FC - -3.41646082456204) / 2.02045502939638)) - 0.703322748122837;
    }
    if (jmp_is_missing(WAVELETLHL_GLCM_IMC1_FC))  {
        _temp_23 = 0;
    }
    else {
        _temp_23 = placeholder_Normal_Log_Density(((WAVELETLHL_GLCM_IMC1_FC - -0.0613138172992701) / 0.00708073377884781)) - -4.95037773556667;
    }
    if (jmp_is_missing(ORIGINAL_SHAPE_FLATNESS_FC))  {
        _temp_24 = 0;
    }
    else {
        _temp_24 = placeholder_Normal_Log_Density(((ORIGINAL_SHAPE_FLATNESS_FC - 0.442544809416058) / 0.0160558629334783)) - -4.13168120430342;
    }
    if (jmp_is_missing(WAVELETLHH_FIRSTORDER_MEAN_FC))  {
        _temp_25 = 0;
    }
    else {
        _temp_25 = placeholder_Normal_Log_Density(((WAVELETLHH_FIRSTORDER_MEAN_FC - 0.202979843065693) / 0.167968485852312)) - -1.78397890138743;
    }
    if (jmp_is_missing(WAVELETHHH_FIRSTORDER_SKEWNESS_FC))  {
        _temp_26 = 0;
    }
    else {
        _temp_26 = placeholder_Normal_Log_Density(((WAVELETHHH_FIRSTORDER_SKEWNESS_FC - -0.0178236131386861) / 0.0381642269902967)) - -3.26585666835064;
    }
    if (jmp_is_missing(WAVELETHHL_NGTDM_STRENGTH_FC))  {
        _temp_27 = 0;
    }
    else {
        _temp_27 = placeholder_Normal_Log_Density(((WAVELETHHL_NGTDM_STRENGTH_FC - 0.000871780109489051) / 0.000408549071008122)) - -7.80289852601175;
    }
    if (jmp_is_missing(WAVELETHHH_FIRSTORDER_RANGE_FC))  {
        _temp_28 = 0;
    }
    else {
        _temp_28 = placeholder_Normal_Log_Density(((WAVELETHHH_FIRSTORDER_RANGE_FC - 112.635549076642) / 20.6398840300423)) - 3.02722532189808;
    }
    if (jmp_is_missing(ORIGINAL_SHAPE_SPHERICITY_FC))  {
        _temp_29 = 0;
    }
    else {
        _temp_29 = placeholder_Normal_Log_Density(((ORIGINAL_SHAPE_SPHERICITY_FC - 0.205068864087591) / 0.0109272955022363)) - -4.5164914454503;
    }
    if (jmp_is_missing(WAVELETLHL_GLSZM_SMALLAREALOWGRA_FC))  {
        _temp_30 = 0;
    }
    else {
        _temp_30 = placeholder_Normal_Log_Density(((WAVELETLHL_GLSZM_SMALLAREALOWGRA_FC - 0.00875705810218978) / 0.00317562594846545)) - -5.75225051694584;
    }
    if (jmp_is_missing(WAVELETLHH_FIRSTORDER_MEDIAN_FC))  {
        _temp_31 = 0;
    }
    else {
        _temp_31 = placeholder_Normal_Log_Density(((WAVELETLHH_FIRSTORDER_MEDIAN_FC - -0.00621641127737226) / 0.113587914218034)) - -2.17517816728054;
    }
    if (jmp_is_missing(WAVELETLHH_GLSZM_SMALLAREAEMPHAS_FC))  {
        _temp_32 = 0;
    }
    else {
        _temp_32 = placeholder_Normal_Log_Density(((WAVELETLHH_GLSZM_SMALLAREAEMPHAS_FC - 0.572621553430657) / 0.0154964299685857)) - -4.1671456061931;
    }
    if (jmp_is_missing(WAVELETHHH_FIRSTORDER_MINIMUM_FC))  {
        _temp_33 = 0;
    }
    else {
        _temp_33 = placeholder_Normal_Log_Density(((WAVELETHHH_FIRSTORDER_MINIMUM_FC - -53.8411539343066) / 9.97649361433198)) - 2.30023168733928;
    }
    if (jmp_is_missing(WAVELETHLH_FIRSTORDER_MEDIAN_FC))  {
        _temp_34 = 0;
    }
    else {
        _temp_34 = placeholder_Normal_Log_Density(((WAVELETHLH_FIRSTORDER_MEDIAN_FC - 0.0903708480656934) / 0.0683662691186856)) - -2.6828757175276;
    }
    Naive_Score_Control = exp(((-0.694968674688336 + _temp_0 + _temp_1 + _temp_2 + _temp_3 + _temp_4 + _temp_5 + _temp_6 + _temp_7 + _temp_8 + _temp_9 + _temp_10 + _temp_11 + _temp_12 + _temp_13 + _temp_14 + _temp_15 + _temp_16 + _temp_17 + _temp_18 + _temp_19 + _temp_20 + _temp_21 + _temp_22 + _temp_23 + _temp_24 + _temp_25 + _temp_26 + _temp_27 + _temp_28 + _temp_29 + _temp_30 + _temp_31 + _temp_32 + _temp_33 + _temp_34) - -7.49466227243816));

    if (jmp_is_missing(WAVELETHHL_GLCM_CLUSTERPROMINENC_FC))  {
        _temp_0 = 0;
    }
    else {
        _temp_0 = placeholder_Normal_Log_Density(((WAVELETHHL_GLCM_CLUSTERPROMINENC_FC - 1.53370744654545) / 0.692281790055132)) - -0.367762195190062;
    }
    if (jmp_is_missing(WAVELETHHL_GLSZM_LARGEAREALOWGRA_FC))  {
        _temp_1 = 0;
    }
    else {
        _temp_1 = placeholder_Normal_Log_Density(((WAVELETHHL_GLSZM_LARGEAREALOWGRA_FC - 435831.096501818) / 289489.184638686)) - 12.5758732165363;
    }
    if (jmp_is_missing(WAVELETLLH_GLSZM_ZONEENTROPY_FC))  {
        _temp_2 = 0;
    }
    else {
        _temp_2 = placeholder_Normal_Log_Density(((WAVELETLLH_GLSZM_ZONEENTROPY_FC - 5.89292438145454) / 0.128295563061853)) - -2.05341859048501;
    }
    if (jmp_is_missing(ORIGINAL_GLSZM_SMALLAREAEMPHASIS_FC))  {
        _temp_3 = 0;
    }
    else {
        _temp_3 = placeholder_Normal_Log_Density(((ORIGINAL_GLSZM_SMALLAREAEMPHASIS_FC - 0.591560037090909) / 0.0117096794325402)) - -4.44733947727752;
    }
    if (jmp_is_missing(V620_FC))  {
        _temp_4 = 0;
    }
    else {
        _temp_4 = placeholder_Normal_Log_Density(((V620_FC - 0.450890965345455) / 0.0251941481153911)) - -3.68114352907466;
    }
    if (jmp_is_missing(WAVELETHLL_GLSZM_GRAYLEVELNONUNI_FC))  {
        _temp_5 = 0;
    }
    else {
        _temp_5 = placeholder_Normal_Log_Density(((WAVELETHLL_GLSZM_GRAYLEVELNONUNI_FC - 871.135807563636) / 355.519820025136)) - 5.87358100022121;
    }
    if (jmp_is_missing(WAVELETLLL_GLCM_IMC2_FC))  {
        _temp_6 = 0;
    }
    else {
        _temp_6 = placeholder_Normal_Log_Density(((WAVELETLLL_GLCM_IMC2_FC - 0.8452449484) / 0.0360281442132138)) - -3.32345486225934;
    }
    if (jmp_is_missing(WAVELETHLL_GLSZM_SMALLAREAEMPHAS_FC))  {
        _temp_7 = 0;
    }
    else {
        _temp_7 = placeholder_Normal_Log_Density(((WAVELETHLL_GLSZM_SMALLAREAEMPHAS_FC - 0.551383322545455) / 0.0209690704522463)) - -3.86470676255455;
    }
    if (jmp_is_missing(WAVELETLLH_FIRSTORDER_MINIMUM_FC))  {
        _temp_8 = 0;
    }
    else {
        _temp_8 = placeholder_Normal_Log_Density(((WAVELETLLH_FIRSTORDER_MINIMUM_FC - -241.728674472727) / 32.7280980953753)) - 3.48823397791469;
    }
    if (jmp_is_missing(WAVELETLLL_GLSZM_GRAYLEVELNONUNI_FC))  {
        _temp_9 = 0;
    }
    else {
        _temp_9 = placeholder_Normal_Log_Density(((WAVELETLLL_GLSZM_GRAYLEVELNONUNI_FC - 1346.58373396364) / 197.077286700149)) - 5.28359597007616;
    }
    if (jmp_is_missing(V455_FC))  {
        _temp_10 = 0;
    }
    else {
        _temp_10 = placeholder_Normal_Log_Density(((V455_FC - 0.0609839343272727) / 0.00168275251372007)) - -6.38732442525786;
    }
    if (jmp_is_missing(WAVELETHHL_GLSZM_SMALLAREAEMPHAS_FC))  {
        _temp_11 = 0;
    }
    else {
        _temp_11 = placeholder_Normal_Log_Density(((WAVELETHHL_GLSZM_SMALLAREAEMPHAS_FC - 0.722716696618182) / 0.0223382569334382)) - -3.80145451285076;
    }
    if (jmp_is_missing(WAVELETLHH_FIRSTORDER_KURTOSIS_FC))  {
        _temp_12 = 0;
    }
    else {
        _temp_12 = placeholder_Normal_Log_Density(((WAVELETLHH_FIRSTORDER_KURTOSIS_FC - 4.34137719236364) / 0.474644758237826)) - -0.745188632141356;
    }
    if (jmp_is_missing(WAVELETLHH_GLSZM_LARGEAREALOWGRA_FC))  {
        _temp_13 = 0;
    }
    else {
        _temp_13 = placeholder_Normal_Log_Density(((WAVELETLHH_GLSZM_LARGEAREALOWGRA_FC - 39528.4972134545) / 24455.4430298575)) - 10.1046080889352;
    }
    if (jmp_is_missing(WAVELETLHH_FIRSTORDER_MAXIMUM_FC))  {
        _temp_14 = 0;
    }
    else {
        _temp_14 = placeholder_Normal_Log_Density(((WAVELETLHH_FIRSTORDER_MAXIMUM_FC - 132.467985607273) / 24.0781164596771)) - 3.18130339726819;
    }
    if (jmp_is_missing(WAVELETHHL_GLCM_CORRELATION_FC))  {
        _temp_15 = 0;
    }
    else {
        _temp_15 = placeholder_Normal_Log_Density(((WAVELETHHL_GLCM_CORRELATION_FC - 0.0244852784727273) / 0.00902589721736605)) - -4.70765736503791;
    }
    if (jmp_is_missing(WAVELETHHH_GLSZM_LARGEAREAHIGHGR_FC))  {
        _temp_16 = 0;
    }
    else {
        _temp_16 = placeholder_Normal_Log_Density(((WAVELETHHH_GLSZM_LARGEAREAHIGHGR_FC - 191128638.163636) / 110900723.854824)) - 18.5241459793942;
    }
    if (jmp_is_missing(WAVELETLLL_GLCM_IDN_FC))  {
        _temp_17 = 0;
    }
    else {
        _temp_17 = placeholder_Normal_Log_Density(((WAVELETLLL_GLCM_IDN_FC - 0.939500618) / 0.00578693698794917)) - -5.15215214500179;
    }
    if (jmp_is_missing(WAVELETLLH_GLSZM_SMALLAREALOWGRA_FC))  {
        _temp_18 = 0;
    }
    else {
        _temp_18 = placeholder_Normal_Log_Density(((WAVELETLLH_GLSZM_SMALLAREALOWGRA_FC - 0.00724784949090909) / 0.00195471867768865)) - -6.23750899477973;
    }
    if (jmp_is_missing(WAVELETHHL_GLDM_SMALLDEPENDENCEL_FC))  {
        _temp_19 = 0;
    }
    else {
        _temp_19 = placeholder_Normal_Log_Density(((WAVELETHHL_GLDM_SMALLDEPENDENCEL_FC - 0.00214759850909091) / 0.000802514171775834)) - -7.12776104358228;
    }
    if (jmp_is_missing(WAVELETLHL_FIRSTORDER_SKEWNESS_FC))  {
        _temp_20 = 0;
    }
    else {
        _temp_20 = placeholder_Normal_Log_Density(((WAVELETLHL_FIRSTORDER_SKEWNESS_FC - -0.339615847163636) / 0.09638299569143)) - -2.33942548616718;
    }
    if (jmp_is_missing(ORIGINAL_FIRSTORDER_MINIMUM_FC))  {
        _temp_21 = 0;
    }
    else {
        _temp_21 = placeholder_Normal_Log_Density(((ORIGINAL_FIRSTORDER_MINIMUM_FC - 8.52363636363636) / 4.31454692821311)) - 1.46199231976722;
    }
    if (jmp_is_missing(WAVELETLHL_GLCM_CLUSTERSHADE_FC))  {
        _temp_22 = 0;
    }
    else {
        _temp_22 = placeholder_Normal_Log_Density(((WAVELETLHL_GLCM_CLUSTERSHADE_FC - -3.3466063148) / 1.83783206055149)) - 0.608586649003487;
    }
    if (jmp_is_missing(WAVELETLHL_GLCM_IMC1_FC))  {
        _temp_23 = 0;
    }
    else {
        _temp_23 = placeholder_Normal_Log_Density(((WAVELETLHL_GLCM_IMC1_FC - -0.0590549616) / 0.00671996680680565)) - -5.00267206392272;
    }
    if (jmp_is_missing(ORIGINAL_SHAPE_FLATNESS_FC))  {
        _temp_24 = 0;
    }
    else {
        _temp_24 = placeholder_Normal_Log_Density(((ORIGINAL_SHAPE_FLATNESS_FC - 0.4396873348) / 0.0165079851542963)) - -4.1039110663958;
    }
    if (jmp_is_missing(WAVELETLHH_FIRSTORDER_MEAN_FC))  {
        _temp_25 = 0;
    }
    else {
        _temp_25 = placeholder_Normal_Log_Density(((WAVELETLHH_FIRSTORDER_MEAN_FC - 0.169530623236364) / 0.150005476612963)) - -1.8970834747993;
    }
    if (jmp_is_missing(WAVELETHHH_FIRSTORDER_SKEWNESS_FC))  {
        _temp_26 = 0;
    }
    else {
        _temp_26 = placeholder_Normal_Log_Density(((WAVELETHHH_FIRSTORDER_SKEWNESS_FC - -0.0185773104363636) / 0.0334327282732479)) - -3.39821997035615;
    }
    if (jmp_is_missing(WAVELETHHL_NGTDM_STRENGTH_FC))  {
        _temp_27 = 0;
    }
    else {
        _temp_27 = placeholder_Normal_Log_Density(((WAVELETHHL_NGTDM_STRENGTH_FC - 0.000902342327272727) / 0.000553077155050143)) - -7.50001304528774;
    }
    if (jmp_is_missing(WAVELETHHH_FIRSTORDER_RANGE_FC))  {
        _temp_28 = 0;
    }
    else {
        _temp_28 = placeholder_Normal_Log_Density(((WAVELETHHH_FIRSTORDER_RANGE_FC - 111.555229138182) / 20.6485285942854)) - 3.02764406235429;
    }
    if (jmp_is_missing(ORIGINAL_SHAPE_SPHERICITY_FC))  {
        _temp_29 = 0;
    }
    else {
        _temp_29 = placeholder_Normal_Log_Density(((ORIGINAL_SHAPE_SPHERICITY_FC - 0.207054422218182) / 0.0121280070169652)) - -4.41223787150666;
    }
    if (jmp_is_missing(WAVELETLHL_GLSZM_SMALLAREALOWGRA_FC))  {
        _temp_30 = 0;
    }
    else {
        _temp_30 = placeholder_Normal_Log_Density(((WAVELETLHL_GLSZM_SMALLAREALOWGRA_FC - 0.00896182298181818) / 0.00342150755274895)) - -5.67767402013621;
    }
    if (jmp_is_missing(WAVELETLHH_FIRSTORDER_MEDIAN_FC))  {
        _temp_31 = 0;
    }
    else {
        _temp_31 = placeholder_Normal_Log_Density(((WAVELETLHH_FIRSTORDER_MEDIAN_FC - -0.0234545415272727) / 0.106435214348071)) - -2.24021879491245;
    }
    if (jmp_is_missing(WAVELETLHH_GLSZM_SMALLAREAEMPHAS_FC))  {
        _temp_32 = 0;
    }
    else {
        _temp_32 = placeholder_Normal_Log_Density(((WAVELETLHH_GLSZM_SMALLAREAEMPHAS_FC - 0.567934824218182) / 0.0136399988490822)) - -4.29474871094496;
    }
    if (jmp_is_missing(WAVELETHHH_FIRSTORDER_MINIMUM_FC))  {
        _temp_33 = 0;
    }
    else {
        _temp_33 = placeholder_Normal_Log_Density(((WAVELETHHH_FIRSTORDER_MINIMUM_FC - -53.8355072145454) / 9.74206999414073)) - 2.27645362013997;
    }
    if (jmp_is_missing(WAVELETHLH_FIRSTORDER_MEDIAN_FC))  {
        _temp_34 = 0;
    }
    else {
        _temp_34 = placeholder_Normal_Log_Density(((WAVELETHLH_FIRSTORDER_MEDIAN_FC - 0.0944522875636364) / 0.0649093872744584)) - -2.73476302359835;
    }
    Naive_Score_Case = exp(((-0.691328998240887 + _temp_0 + _temp_1 + _temp_2 + _temp_3 + _temp_4 + _temp_5 + _temp_6 + _temp_7 + _temp_8 + _temp_9 + _temp_10 + _temp_11 + _temp_12 + _temp_13 + _temp_14 + _temp_15 + _temp_16 + _temp_17 + _temp_18 + _temp_19 + _temp_20 + _temp_21 + _temp_22 + _temp_23 + _temp_24 + _temp_25 + _temp_26 + _temp_27 + _temp_28 + _temp_29 + _temp_30 + _temp_31 + _temp_32 + _temp_33 + _temp_34) - -7.49466227243816));

    if (jmp_is_missing(ORIGINAL_FIRSTORDER_MINIMUM_FC))  {
        _temp_0 = 0;
    }
    else {
        _temp_0 = -1.46199231976722 + placeholder_Normal_Log_Density((-1.9755576901713 + 0.231774046415148 * ORIGINAL_FIRSTORDER_MINIMUM_FC));
    }
    if (jmp_is_missing(ORIGINAL_GLSZM_SMALLAREAEMPHASIS_FC))  {
        _temp_1 = 0;
    }
    else {
        _temp_1 = 4.44733947727752 + placeholder_Normal_Log_Density((-50.5188925537118 + 85.3994343535215 * ORIGINAL_GLSZM_SMALLAREAEMPHASIS_FC));
    }
    if (jmp_is_missing(ORIGINAL_SHAPE_ELONGATION_LM))  {
        _temp_2 = 0;
    }
    else {
        _temp_2 = 3.44606835567658 + placeholder_Normal_Log_Density((-16.3323743578004 + 31.3767871151929 * ORIGINAL_SHAPE_ELONGATION_LM));
    }
    if (jmp_is_missing(ORIGINAL_SHAPE_SPHERICITY_MM))  {
        _temp_3 = 0;
    }
    else {
        _temp_3 = 4.11882837625468 + placeholder_Normal_Log_Density((-25.9855284131883 + 61.4871602292054 * ORIGINAL_SHAPE_SPHERICITY_MM));
    }
    if (jmp_is_missing(V455_FC))  {
        _temp_4 = 0;
    }
    else {
        _temp_4 = 6.38732442525786 + placeholder_Normal_Log_Density((-36.2405842986711 + 594.264451751907 * V455_FC));
    }
    if (jmp_is_missing(V620_FC))  {
        _temp_5 = 0;
    }
    else {
        _temp_5 = 3.68114352907466 + placeholder_Normal_Log_Density((-17.8966545437591 + 39.6917568087606 * V620_FC));
    }
    if (jmp_is_missing(V810_MM))  {
        _temp_6 = 0;
    }
    else {
        _temp_6 = 3.56963151869869 + placeholder_Normal_Log_Density((-11.035759352415 + 35.503508362064 * V810_MM));
    }
    if (jmp_is_missing(WAVELETHHH_FIRSTORDER_MINIMUM_FC))  {
        _temp_7 = 0;
    }
    else {
        _temp_7 = -2.27645362013997 + placeholder_Normal_Log_Density((5.52608503602666 + 0.102647589331779 * WAVELETHHH_FIRSTORDER_MINIMUM_FC));
    }
    if (jmp_is_missing(WAVELETHHH_GLCM_CLUSTERSHADE_MM))  {
        _temp_8 = 0;
    }
    else {
        _temp_8 = 6.1117886359281 + placeholder_Normal_Log_Density((-0.0788389378000081 + 451.144927969037 * WAVELETHHH_GLCM_CLUSTERSHADE_MM));
    }
    if (jmp_is_missing(WAVELETHHH_GLCM_IMC1_LM))  {
        _temp_9 = 0;
    }
    else {
        _temp_9 = 6.295915992492 + placeholder_Normal_Log_Density((4.94444526048274 + 542.352409669532 * WAVELETHHH_GLCM_IMC1_LM));
    }
    if (jmp_is_missing(WAVELETHHH_GLRLM_RUNVARIANCE_MM))  {
        _temp_10 = 0;
    }
    else {
        _temp_10 = 3.04311278910496 + placeholder_Normal_Log_Density((-27.1410210903542 + 20.9704182338587 * WAVELETHHH_GLRLM_RUNVARIANCE_MM));
    }
    if (jmp_is_missing(WAVELETHHH_GLSZM_LARGEAREAHIGHGR_FC))  {
        _temp_11 = 0;
    }
    else {
        _temp_11 = -18.5241459793942 + placeholder_Normal_Log_Density((-1.72342101584328 + 0.0000000090170736966 * WAVELETHHH_GLSZM_LARGEAREAHIGHGR_FC));
    }
    if (jmp_is_missing(WAVELETHHL_FIRSTORDER_MEAN_MM))  {
        _temp_12 = 0;
    }
    else {
        _temp_12 = 2.70956162763264 + placeholder_Normal_Log_Density((-1.88816576369727 + 15.0226885396677 * WAVELETHHL_FIRSTORDER_MEAN_MM));
    }
    if (jmp_is_missing(WAVELETHHL_GLCM_CLUSTERPROMINENC_FC))  {
        _temp_13 = 0;
    }
    else {
        _temp_13 = 0.367762195190062 + placeholder_Normal_Log_Density((-2.21543808977456 + 1.4444984894379 * WAVELETHHL_GLCM_CLUSTERPROMINENC_FC));
    }
    if (jmp_is_missing(WAVELETHHL_GLCM_CORRELATION_MM))  {
        _temp_14 = 0;
    }
    else {
        _temp_14 = 4.84443991609403 + placeholder_Normal_Log_Density((-0.275845411697392 + 127.032113423142 * WAVELETHHL_GLCM_CORRELATION_MM));
    }
    if (jmp_is_missing(WAVELETHHL_GLCM_IMC1_MM))  {
        _temp_15 = 0;
    }
    else {
        _temp_15 = 5.86572242567548 + placeholder_Normal_Log_Density((5.72088095581601 + 352.736890269601 * WAVELETHHL_GLCM_IMC1_MM));
    }
    if (jmp_is_missing(WAVELETHHL_GLCM_IMC1_TC))  {
        _temp_16 = 0;
    }
    else {
        _temp_16 = 5.09218436015282 + placeholder_Normal_Log_Density((3.71105453117404 + 162.744967695491 * WAVELETHHL_GLCM_IMC1_TC));
    }
    if (jmp_is_missing(WAVELETHHL_GLDM_SMALLDEPENDENCEL_FC))  {
        _temp_17 = 0;
    }
    else {
        _temp_17 = 7.12776104358228 + placeholder_Normal_Log_Density((-2.67608795535488 + 1246.08391374219 * WAVELETHHL_GLDM_SMALLDEPENDENCEL_FC));
    }
    if (jmp_is_missing(WAVELETHHL_GLDM_SMALLDEPENDENCEL_MM))  {
        _temp_18 = 0;
    }
    else {
        _temp_18 = 6.3638351761944 + placeholder_Normal_Log_Density((-2.0207817921301 + 580.468291086326 * WAVELETHHL_GLDM_SMALLDEPENDENCEL_MM));
    }
    if (jmp_is_missing(WAVELETHHL_GLRLM_LONGRUNHIGHGRAY_MM))  {
        _temp_19 = 0;
    }
    else {
        _temp_19 = -2.73928991543196 + placeholder_Normal_Log_Density((-2.7488918933564 + 0.0646162135827374 * WAVELETHHL_GLRLM_LONGRUNHIGHGRAY_MM));
    }
    if (jmp_is_missing(WAVELETHHL_GLSZM_GRAYLEVELVARIAN_MM))  {
        _temp_20 = 0;
    }
    else {
        _temp_20 = 2.1356673758417 + placeholder_Normal_Log_Density((-18.788215782918 + 8.46269241915558 * WAVELETHHL_GLSZM_GRAYLEVELVARIAN_MM));
    }
    if (jmp_is_missing(WAVELETHHL_GLSZM_LARGEAREALOWGRA_FC))  {
        _temp_21 = 0;
    }
    else {
        _temp_21 = -12.5758732165363 + placeholder_Normal_Log_Density((-1.5055177175126 + 0.0000034543604841338 * WAVELETHHL_GLSZM_LARGEAREALOWGRA_FC));
    }
    if (jmp_is_missing(WAVELETHHL_GLSZM_SMALLAREAEMPHAS_FC))  {
        _temp_22 = 0;
    }
    else {
        _temp_22 = 3.80145451285076 + placeholder_Normal_Log_Density((-32.3533164996569 + 44.766250248608 * WAVELETHHL_GLSZM_SMALLAREAEMPHAS_FC));
    }
    if (jmp_is_missing(WAVELETHLH_FIRSTORDER_MEDIAN_LM))  {
        _temp_23 = 0;
    }
    else {
        _temp_23 = 2.54431537659471 + placeholder_Normal_Log_Density((0.696753750969046 + 12.7345067596116 * WAVELETHLH_FIRSTORDER_MEDIAN_LM));
    }
    if (jmp_is_missing(WAVELETHLH_GLSZM_LARGEAREAHIGHGR_TC))  {
        _temp_24 = 0;
    }
    else {
        _temp_24 = -15.6127399919531 + placeholder_Normal_Log_Density((-1.7538547027387 + 0.0000001657574947094 * WAVELETHLH_GLSZM_LARGEAREAHIGHGR_TC));
    }
    if (jmp_is_missing(WAVELETHLH_GLSZM_ZONEENTROPY_TC))  {
        _temp_25 = 0;
    }
    else {
        _temp_25 = 1.38869060606963 + placeholder_Normal_Log_Density((-10.1127947729786 + 4.00959647295699 * WAVELETHLH_GLSZM_ZONEENTROPY_TC));
    }
    if (jmp_is_missing(WAVELETHLL_FIRSTORDER_KURTOSIS_MM))  {
        _temp_26 = 0;
    }
    else {
        _temp_26 = -0.0630495017190976 + placeholder_Normal_Log_Density((-4.46076059360572 + 0.938896995523434 * WAVELETHLL_FIRSTORDER_KURTOSIS_MM));
    }
    if (jmp_is_missing(WAVELETHLL_FIRSTORDER_SKEWNESS_LM))  {
        _temp_27 = 0;
    }
    else {
        _temp_27 = 2.17979912130199 + placeholder_Normal_Log_Density((0.634984316004437 + 8.84452940270967 * WAVELETHLL_FIRSTORDER_SKEWNESS_LM));
    }
    if (jmp_is_missing(WAVELETHLL_GLSZM_GRAYLEVELNONUNI_FC))  {
        _temp_28 = 0;
    }
    else {
        _temp_28 = -5.87358100022121 + placeholder_Normal_Log_Density((-2.45031573064491 + 0.0028127827020426 * WAVELETHLL_GLSZM_GRAYLEVELNONUNI_FC));
    }
    if (jmp_is_missing(WAVELETHLL_GLSZM_LARGEAREALOWGRA_LM))  {
        _temp_29 = 0;
    }
    else {
        _temp_29 = -9.90527073944226 + placeholder_Normal_Log_Density((-1.57948624256684 + 0.0000499109201013525 * WAVELETHLL_GLSZM_LARGEAREALOWGRA_LM));
    }
    if (jmp_is_missing(WAVELETHLL_GLSZM_SMALLAREAEMPHAS_FC))  {
        _temp_30 = 0;
    }
    else {
        _temp_30 = 3.86470676255455 + placeholder_Normal_Log_Density((-26.2950770183705 + 47.6892860976999 * WAVELETHLL_GLSZM_SMALLAREAEMPHAS_FC));
    }
    if (jmp_is_missing(WAVELETHLL_NGTDM_BUSYNESS_MM))  {
        _temp_31 = 0;
    }
    else {
        _temp_31 = -3.88411860577591 + placeholder_Normal_Log_Density((-2.00735674322587 + 0.0205659474827135 * WAVELETHLL_NGTDM_BUSYNESS_MM));
    }
    if (jmp_is_missing(WAVELETLHH_FIRSTORDER_MAXIMUM_MM))  {
        _temp_32 = 0;
    }
    else {
        _temp_32 = -2.85313131418634 + placeholder_Normal_Log_Density((-5.26317888432478 + 0.0576634754220173 * WAVELETLHH_FIRSTORDER_MAXIMUM_MM));
    }
    if (jmp_is_missing(WAVELETLHH_FIRSTORDER_MEDIAN_LM))  {
        _temp_33 = 0;
    }
    else {
        _temp_33 = 1.60255743076681 + placeholder_Normal_Log_Density((0.241663288374739 + 4.96571567325887 * WAVELETLHH_FIRSTORDER_MEDIAN_LM));
    }
    if (jmp_is_missing(WAVELETLHH_GLSZM_SMALLAREAEMPHAS_MM))  {
        _temp_34 = 0;
    }
    else {
        _temp_34 = 3.45355496537128 + placeholder_Normal_Log_Density((-17.6669343323075 + 31.612574396161 * WAVELETLHH_GLSZM_SMALLAREAEMPHAS_MM));
    }
    if (jmp_is_missing(WAVELETLHL_FIRSTORDER_MINIMUM_TC))  {
        _temp_35 = 0;
    }
    else {
        _temp_35 = -3.52185911077717 + placeholder_Normal_Log_Density((6.00317821857708 + 0.0295444576594472 * WAVELETLHL_FIRSTORDER_MINIMUM_TC));
    }
    if (jmp_is_missing(WAVELETLHL_FIRSTORDER_SKEWNESS_FC))  {
        _temp_36 = 0;
    }
    else {
        _temp_36 = 2.33942548616718 + placeholder_Normal_Log_Density((3.52360750698096 + 10.3752741116441 * WAVELETLHL_FIRSTORDER_SKEWNESS_FC));
    }
    if (jmp_is_missing(WAVELETLHL_FIRSTORDER_SKEWNESS_TC))  {
        _temp_37 = 0;
    }
    else {
        _temp_37 = 2.15458993069675 + placeholder_Normal_Log_Density((-0.748984058622632 + 8.62435287137472 * WAVELETLHL_FIRSTORDER_SKEWNESS_TC));
    }
    if (jmp_is_missing(WAVELETLHL_GLCM_CLUSTERSHADE_FC))  {
        _temp_38 = 0;
    }
    else {
        _temp_38 = -0.608586649003487 + placeholder_Normal_Log_Density((1.82095327785052 + 0.544119357510786 * WAVELETLHL_GLCM_CLUSTERSHADE_FC));
    }
    if (jmp_is_missing(WAVELETLHL_GLSZM_ZONEENTROPY_LM))  {
        _temp_39 = 0;
    }
    else {
        _temp_39 = 1.53342352773912 + placeholder_Normal_Log_Density((-27.4458050888349 + 4.63401437343416 * WAVELETLHL_GLSZM_ZONEENTROPY_LM));
    }
    if (jmp_is_missing(WAVELETLHL_GLSZM_ZONEENTROPY_MM))  {
        _temp_40 = 0;
    }
    else {
        _temp_40 = 1.57517275864608 + placeholder_Normal_Log_Density((-28.3237248589311 + 4.83157624258399 * WAVELETLHL_GLSZM_ZONEENTROPY_MM));
    }
    if (jmp_is_missing(WAVELETLLH_FIRSTORDER_MINIMUM_FC))  {
        _temp_41 = 0;
    }
    else {
        _temp_41 = -3.48823397791469 + placeholder_Normal_Log_Density((7.38596767121293 + 0.0305547849766836 * WAVELETLLH_FIRSTORDER_MINIMUM_FC));
    }
    if (jmp_is_missing(WAVELETLLH_GLCM_CORRELATION_MM))  {
        _temp_42 = 0;
    }
    else {
        _temp_42 = 3.75103276771794 + placeholder_Normal_Log_Density((-3.92855619151554 + 42.5650190853807 * WAVELETLLH_GLCM_CORRELATION_MM));
    }
    if (jmp_is_missing(WAVELETLLH_GLCM_IMC1_MM))  {
        _temp_43 = 0;
    }
    else {
        _temp_43 = 4.94210163225806 + placeholder_Normal_Log_Density((7.76436756015755 + 140.064304114231 * WAVELETLLH_GLCM_IMC1_MM));
    }
    if (jmp_is_missing(WAVELETLLH_GLDM_SMALLDEPENDENCEL_MM))  {
        _temp_44 = 0;
    }
    else {
        _temp_44 = 7.74926382754169 + placeholder_Normal_Log_Density((-2.63404145559744 + 2319.86396587305 * WAVELETLLH_GLDM_SMALLDEPENDENCEL_MM));
    }
    if (jmp_is_missing(WAVELETLLH_GLSZM_ZONEENTROPY_FC))  {
        _temp_45 = 0;
    }
    else {
        _temp_45 = 2.05341859048501 + placeholder_Normal_Log_Density((-45.9324098263123 + 7.79450182168719 * WAVELETLLH_GLSZM_ZONEENTROPY_FC));
    }
    if (jmp_is_missing(WAVELETLLL_GLCM_CLUSTERSHADE_LM))  {
        _temp_46 = 0;
    }
    else {
        _temp_46 = -4.74202851674432 + placeholder_Normal_Log_Density((-1.8898965163899 + 0.0087209376624535 * WAVELETLLL_GLCM_CLUSTERSHADE_LM));
    }
    if (jmp_is_missing(WAVELETLLL_GLCM_IDN_FC))  {
        _temp_47 = 0;
    }
    else {
        _temp_47 = 5.15215214500179 + placeholder_Normal_Log_Density((-162.348513549816 + 172.802987501405 * WAVELETLLL_GLCM_IDN_FC));
    }
    if (jmp_is_missing(WAVELETLLL_GLDM_LARGEDEPENDENCEH_LM))  {
        _temp_48 = 0;
    }
    else {
        _temp_48 = -7.25370444027467 + placeholder_Normal_Log_Density((-2.86683160373856 + 0.000707548457041187 * WAVELETLLL_GLDM_LARGEDEPENDENCEH_LM));
    }
    if (jmp_is_missing(WAVELETLLL_GLSZM_GRAYLEVELNONUNI_FC))  {
        _temp_49 = 0;
    }
    else {
        _temp_49 = -5.28359597007616 + placeholder_Normal_Log_Density((-6.8327698057486 + 0.00507415144963656 * WAVELETLLL_GLSZM_GRAYLEVELNONUNI_FC));
    }
    if (jmp_is_missing(WAVELETLLL_GLSZM_GRAYLEVELVARIAN_MM))  {
        _temp_50 = 0;
    }
    else {
        _temp_50 = -1.37760604528278 + placeholder_Normal_Log_Density((-4.65455358418508 + 0.252181542199976 * WAVELETLLL_GLSZM_GRAYLEVELVARIAN_MM));
    }
    if (jmp_is_missing(WAVELETLLL_NGTDM_BUSYNESS_TC))  {
        _temp_51 = 0;
    }
    else {
        _temp_51 = -0.612493937893744 + placeholder_Normal_Log_Density((-2.92924790845785 + 0.541997474095507 * WAVELETLLL_NGTDM_BUSYNESS_TC));
    }
    Naive_Score_Case_Naive_Score_Case = exp((34.6277711877936 + _temp_0 + _temp_1 + _temp_2 + _temp_3 + _temp_4 + _temp_5 + _temp_6 + _temp_7 + _temp_8 + _temp_9 + _temp_10 + _temp_11 + _temp_12 + _temp_13 + _temp_14 + _temp_15 + _temp_16 + _temp_17 + _temp_18 + _temp_19 + _temp_20 + _temp_21 + _temp_22 + _temp_23 + _temp_24 + _temp_25 + _temp_26 + _temp_27 + _temp_28 + _temp_29 + _temp_30 + _temp_31 + _temp_32 + _temp_33 + _temp_34 + _temp_35 + _temp_36 + _temp_37 + _temp_38 + _temp_39 + _temp_40 + _temp_41 + _temp_42 + _temp_43 + _temp_44 + _temp_45 + _temp_46 + _temp_47 + _temp_48 + _temp_49 + _temp_50 + _temp_51));

    if (jmp_is_missing(ORIGINAL_FIRSTORDER_MINIMUM_FC))  {
        _temp_0 = 0;
    }
    else {
        _temp_0 = -1.40769939648407 + placeholder_Normal_Log_Density((-2.02998483174789 + 0.244705606642729 * ORIGINAL_FIRSTORDER_MINIMUM_FC));
    }
    if (jmp_is_missing(ORIGINAL_GLSZM_SMALLAREAEMPHASIS_FC))  {
        _temp_1 = 0;
    }
    else {
        _temp_1 = 4.45430998046867 + placeholder_Normal_Log_Density((-50.7912884100366 + 85.996790902379 * ORIGINAL_GLSZM_SMALLAREAEMPHASIS_FC));
    }
    if (jmp_is_missing(ORIGINAL_SHAPE_ELONGATION_LM))  {
        _temp_2 = 0;
    }
    else {
        _temp_2 = 3.41891935472661 + placeholder_Normal_Log_Density((-15.7454626160224 + 30.5363981701623 * ORIGINAL_SHAPE_ELONGATION_LM));
    }
    if (jmp_is_missing(ORIGINAL_SHAPE_SPHERICITY_MM))  {
        _temp_3 = 0;
    }
    else {
        _temp_3 = 4.26831338745469 + placeholder_Normal_Log_Density((-30.1338872963532 + 71.4011080015905 * ORIGINAL_SHAPE_SPHERICITY_MM));
    }
    if (jmp_is_missing(V455_FC))  {
        _temp_4 = 0;
    }
    else {
        _temp_4 = 6.44336298478878 + placeholder_Normal_Log_Density((-38.1373828114704 + 628.51694255106 * V455_FC));
    }
    if (jmp_is_missing(V620_FC))  {
        _temp_5 = 0;
    }
    else {
        _temp_5 = 3.73856978889719 + placeholder_Normal_Log_Density((-18.7831418902843 + 42.0378241873373 * V620_FC));
    }
    if (jmp_is_missing(V810_MM))  {
        _temp_6 = 0;
    }
    else {
        _temp_6 = 3.47763123013267 + placeholder_Normal_Log_Density((-10.3087075302152 + 32.3829234593432 * V810_MM));
    }
    if (jmp_is_missing(WAVELETHHH_FIRSTORDER_MINIMUM_FC))  {
        _temp_7 = 0;
    }
    else {
        _temp_7 = -2.30023168733928 + placeholder_Normal_Log_Density((5.3968013227573 + 0.100235617708753 * WAVELETHHH_FIRSTORDER_MINIMUM_FC));
    }
    if (jmp_is_missing(WAVELETHHH_GLCM_CLUSTERSHADE_MM))  {
        _temp_8 = 0;
    }
    else {
        _temp_8 = 6.04272594054893 + placeholder_Normal_Log_Density((0.0155069812939703 + 421.039199815673 * WAVELETHHH_GLCM_CLUSTERSHADE_MM));
    }
    if (jmp_is_missing(WAVELETHHH_GLCM_IMC1_LM))  {
        _temp_9 = 0;
    }
    else {
        _temp_9 = 6.25214962802694 + placeholder_Normal_Log_Density((4.80194358381409 + 519.127557255513 * WAVELETHHH_GLCM_IMC1_LM));
    }
    if (jmp_is_missing(WAVELETHHH_GLRLM_RUNVARIANCE_MM))  {
        _temp_10 = 0;
    }
    else {
        _temp_10 = 3.10710652673805 + placeholder_Normal_Log_Density((-28.9277681041586 + 22.3562634744034 * WAVELETHHH_GLRLM_RUNVARIANCE_MM));
    }
    if (jmp_is_missing(WAVELETHHH_GLSZM_LARGEAREAHIGHGR_FC))  {
        _temp_11 = 0;
    }
    else {
        _temp_11 = -18.7357919582415 + placeholder_Normal_Log_Density((-1.50213564926338 + 0.0000000072970771583 * WAVELETHHH_GLSZM_LARGEAREAHIGHGR_FC));
    }
    if (jmp_is_missing(WAVELETHHL_FIRSTORDER_MEAN_MM))  {
        _temp_12 = 0;
    }
    else {
        _temp_12 = 2.70525857133555 + placeholder_Normal_Log_Density((-2.12059138194688 + 14.9581839481244 * WAVELETHHL_FIRSTORDER_MEAN_MM));
    }
    if (jmp_is_missing(WAVELETHHL_GLCM_CLUSTERPROMINENC_FC))  {
        _temp_13 = 0;
    }
    else {
        _temp_13 = 0.477363196165406 + placeholder_Normal_Log_Density((-2.43384308166953 + 1.61181874414564 * WAVELETHHL_GLCM_CLUSTERPROMINENC_FC));
    }
    if (jmp_is_missing(WAVELETHHL_GLCM_CORRELATION_MM))  {
        _temp_14 = 0;
    }
    else {
        _temp_14 = 4.86411657208708 + placeholder_Normal_Log_Density((-0.295777372538498 + 129.556434270757 * WAVELETHHL_GLCM_CORRELATION_MM));
    }
    if (jmp_is_missing(WAVELETHHL_GLCM_IMC1_MM))  {
        _temp_15 = 0;
    }
    else {
        _temp_15 = 5.81907677801971 + placeholder_Normal_Log_Density((5.54296132822202 + 336.661097186414 * WAVELETHHL_GLCM_IMC1_MM));
    }
    if (jmp_is_missing(WAVELETHHL_GLCM_IMC1_TC))  {
        _temp_16 = 0;
    }
    else {
        _temp_16 = 5.19405641049375 + placeholder_Normal_Log_Density((4.07020668327406 + 180.198029581348 * WAVELETHHL_GLCM_IMC1_TC));
    }
    if (jmp_is_missing(WAVELETHHL_GLDM_SMALLDEPENDENCEL_FC))  {
        _temp_17 = 0;
    }
    else {
        _temp_17 = 7.17009026198478 + placeholder_Normal_Log_Density((-2.69670067418405 + 1299.96193465301 * WAVELETHHL_GLDM_SMALLDEPENDENCEL_FC));
    }
    if (jmp_is_missing(WAVELETHHL_GLDM_SMALLDEPENDENCEL_MM))  {
        _temp_18 = 0;
    }
    else {
        _temp_18 = 6.52352511955377 + placeholder_Normal_Log_Density((-2.11527818503904 + 680.974676399154 * WAVELETHHL_GLDM_SMALLDEPENDENCEL_MM));
    }
    if (jmp_is_missing(WAVELETHHL_GLRLM_LONGRUNHIGHGRAY_MM))  {
        _temp_19 = 0;
    }
    else {
        _temp_19 = -2.63485330816982 + placeholder_Normal_Log_Density((-3.1085272491587 + 0.0717294907671517 * WAVELETHHL_GLRLM_LONGRUNHIGHGRAY_MM));
    }
    if (jmp_is_missing(WAVELETHHL_GLSZM_GRAYLEVELVARIAN_MM))  {
        _temp_20 = 0;
    }
    else {
        _temp_20 = 2.16538277287389 + placeholder_Normal_Log_Density((-19.4114310922896 + 8.71793826856346 * WAVELETHHL_GLSZM_GRAYLEVELVARIAN_MM));
    }
    if (jmp_is_missing(WAVELETHHL_GLSZM_LARGEAREALOWGRA_FC))  {
        _temp_21 = 0;
    }
    else {
        _temp_21 = -13.113651920005 + placeholder_Normal_Log_Density((-1.05012404177422 + 0.0000020174990251388 * WAVELETHHL_GLSZM_LARGEAREALOWGRA_FC));
    }
    if (jmp_is_missing(WAVELETHHL_GLSZM_SMALLAREAEMPHAS_FC))  {
        _temp_22 = 0;
    }
    else {
        _temp_22 = 3.70455119260605 + placeholder_Normal_Log_Density((-29.1577333483085 + 40.6318073684966 * WAVELETHHL_GLSZM_SMALLAREAEMPHAS_FC));
    }
    if (jmp_is_missing(WAVELETHLH_FIRSTORDER_MEDIAN_LM))  {
        _temp_23 = 0;
    }
    else {
        _temp_23 = 2.58086805713443 + placeholder_Normal_Log_Density((0.837757219289228 + 13.2085990032057 * WAVELETHLH_FIRSTORDER_MEDIAN_LM));
    }
    if (jmp_is_missing(WAVELETHLH_GLSZM_LARGEAREAHIGHGR_TC))  {
        _temp_24 = 0;
    }
    else {
        _temp_24 = -16.2484481795929 + placeholder_Normal_Log_Density((-1.17265243053341 + 0.0000000877785931694 * WAVELETHLH_GLSZM_LARGEAREAHIGHGR_TC));
    }
    if (jmp_is_missing(WAVELETHLH_GLSZM_ZONEENTROPY_TC))  {
        _temp_25 = 0;
    }
    else {
        _temp_25 = 1.23494870747774 + placeholder_Normal_Log_Density((-8.69895433060391 + 3.4382021621213 * WAVELETHLH_GLSZM_ZONEENTROPY_TC));
    }
    if (jmp_is_missing(WAVELETHLL_FIRSTORDER_KURTOSIS_MM))  {
        _temp_26 = 0;
    }
    else {
        _temp_26 = -0.0159978298628314 + placeholder_Normal_Log_Density((-4.81561495058514 + 0.984129455748878 * WAVELETHLL_FIRSTORDER_KURTOSIS_MM));
    }
    if (jmp_is_missing(WAVELETHLL_FIRSTORDER_SKEWNESS_LM))  {
        _temp_27 = 0;
    }
    else {
        _temp_27 = 2.22294791043496 + placeholder_Normal_Log_Density((0.515044759253306 + 9.23451329862348 * WAVELETHLL_FIRSTORDER_SKEWNESS_LM));
    }
    if (jmp_is_missing(WAVELETHLL_GLSZM_GRAYLEVELNONUNI_FC))  {
        _temp_28 = 0;
    }
    else {
        _temp_28 = -5.82341912579405 + placeholder_Normal_Log_Density((-2.35282767705945 + 0.00295747585600811 * WAVELETHLL_GLSZM_GRAYLEVELNONUNI_FC));
    }
    if (jmp_is_missing(WAVELETHLL_GLSZM_LARGEAREALOWGRA_LM))  {
        _temp_29 = 0;
    }
    else {
        _temp_29 = -10.3949557796378 + placeholder_Normal_Log_Density((-1.11407733298584 + 0.0000305863789751379 * WAVELETHLL_GLSZM_LARGEAREALOWGRA_LM));
    }
    if (jmp_is_missing(WAVELETHLL_GLSZM_SMALLAREAEMPHAS_FC))  {
        _temp_30 = 0;
    }
    else {
        _temp_30 = 3.8749070750095 + placeholder_Normal_Log_Density((-26.7318974481636 + 48.1782211223414 * WAVELETHLL_GLSZM_SMALLAREAEMPHAS_FC));
    }
    if (jmp_is_missing(WAVELETHLL_NGTDM_BUSYNESS_MM))  {
        _temp_31 = 0;
    }
    else {
        _temp_31 = -3.76084689092138 + placeholder_Normal_Log_Density((-2.19706924493361 + 0.0232640299340326 * WAVELETHLL_NGTDM_BUSYNESS_MM));
    }
    if (jmp_is_missing(WAVELETLHH_FIRSTORDER_MAXIMUM_MM))  {
        _temp_32 = 0;
    }
    else {
        _temp_32 = -2.91278319745801 + placeholder_Normal_Log_Density((-5.01659041948738 + 0.0543243239503139 * WAVELETLHH_FIRSTORDER_MAXIMUM_MM));
    }
    if (jmp_is_missing(WAVELETLHH_FIRSTORDER_MEDIAN_LM))  {
        _temp_33 = 0;
    }
    else {
        _temp_33 = 1.5722574761603 + placeholder_Normal_Log_Density((0.407573385724469 + 4.81751134452207 * WAVELETLHH_FIRSTORDER_MEDIAN_LM));
    }
    if (jmp_is_missing(WAVELETLHH_GLSZM_SMALLAREAEMPHAS_MM))  {
        _temp_34 = 0;
    }
    else {
        _temp_34 = 3.44307652207182 + placeholder_Normal_Log_Density((-17.5525558544917 + 31.2830532770337 * WAVELETLHH_GLSZM_SMALLAREAEMPHAS_MM));
    }
    if (jmp_is_missing(WAVELETLHL_FIRSTORDER_MINIMUM_TC))  {
        _temp_35 = 0;
    }
    else {
        _temp_35 = -3.68257473265745 + placeholder_Normal_Log_Density((5.20345585743795 + 0.0251581159511748 * WAVELETLHL_FIRSTORDER_MINIMUM_TC));
    }
    if (jmp_is_missing(WAVELETLHL_FIRSTORDER_SKEWNESS_FC))  {
        _temp_36 = 0;
    }
    else {
        _temp_36 = 2.25784725874086 + placeholder_Normal_Log_Density((3.15347025945541 + 9.56248144483017 * WAVELETLHL_FIRSTORDER_SKEWNESS_FC));
    }
    if (jmp_is_missing(WAVELETLHL_FIRSTORDER_SKEWNESS_TC))  {
        _temp_37 = 0;
    }
    else {
        _temp_37 = 2.109042275387 + placeholder_Normal_Log_Density((-0.514565252040332 + 8.24034552252078 * WAVELETLHL_FIRSTORDER_SKEWNESS_TC));
    }
    if (jmp_is_missing(WAVELETLHL_GLCM_CLUSTERSHADE_FC))  {
        _temp_38 = 0;
    }
    else {
        _temp_38 = -0.703322748122837 + placeholder_Normal_Log_Density((1.69093633605036 + 0.494938014185228 * WAVELETLHL_GLCM_CLUSTERSHADE_FC));
    }
    if (jmp_is_missing(WAVELETLHL_GLSZM_ZONEENTROPY_LM))  {
        _temp_39 = 0;
    }
    else {
        _temp_39 = 1.44425080952749 + placeholder_Normal_Log_Density((-25.0463198498251 + 4.23867537775889 * WAVELETLHL_GLSZM_ZONEENTROPY_LM));
    }
    if (jmp_is_missing(WAVELETLHL_GLSZM_ZONEENTROPY_MM))  {
        _temp_40 = 0;
    }
    else {
        _temp_40 = 1.51688970045589 + placeholder_Normal_Log_Density((-26.7306182631875 + 4.55802629806035 * WAVELETLHL_GLSZM_ZONEENTROPY_MM));
    }
    if (jmp_is_missing(WAVELETLLH_FIRSTORDER_MINIMUM_FC))  {
        _temp_41 = 0;
    }
    else {
        _temp_41 = -3.65385200986414 + placeholder_Normal_Log_Density((6.32291652106771 + 0.0258912032748904 * WAVELETLLH_FIRSTORDER_MINIMUM_FC));
    }
    if (jmp_is_missing(WAVELETLLH_GLCM_CORRELATION_MM))  {
        _temp_42 = 0;
    }
    else {
        _temp_42 = 3.67331648930703 + placeholder_Normal_Log_Density((-3.73706487462513 + 39.3823004930548 * WAVELETLLH_GLCM_CORRELATION_MM));
    }
    if (jmp_is_missing(WAVELETLLH_GLCM_IMC1_MM))  {
        _temp_43 = 0;
    }
    else {
        _temp_43 = 4.82020658287596 + placeholder_Normal_Log_Density((7.08084043453635 + 123.990702490175 * WAVELETLLH_GLCM_IMC1_MM));
    }
    if (jmp_is_missing(WAVELETLLH_GLDM_SMALLDEPENDENCEL_MM))  {
        _temp_44 = 0;
    }
    else {
        _temp_44 = 7.70860795755376 + placeholder_Normal_Log_Density((-2.50253215920226 + 2227.43940883419 * WAVELETLLH_GLDM_SMALLDEPENDENCEL_MM));
    }
    if (jmp_is_missing(WAVELETLLH_GLSZM_ZONEENTROPY_FC))  {
        _temp_45 = 0;
    }
    else {
        _temp_45 = 1.85310567037502 + placeholder_Normal_Log_Density((-37.556941766476 + 6.37960172828846 * WAVELETLLH_GLSZM_ZONEENTROPY_FC));
    }
    if (jmp_is_missing(WAVELETLLL_GLCM_CLUSTERSHADE_LM))  {
        _temp_46 = 0;
    }
    else {
        _temp_46 = -4.88425952849476 + placeholder_Normal_Log_Density((-1.80265854756653 + 0.00756472315062989 * WAVELETLLL_GLCM_CLUSTERSHADE_LM));
    }
    if (jmp_is_missing(WAVELETLLL_GLCM_IDN_FC))  {
        _temp_47 = 0;
    }
    else {
        _temp_47 = 5.18820141715545 + placeholder_Normal_Log_Density((-168.171932039314 + 179.146053978873 * WAVELETLLL_GLCM_IDN_FC));
    }
    if (jmp_is_missing(WAVELETLLL_GLDM_LARGEDEPENDENCEH_LM))  {
        _temp_48 = 0;
    }
    else {
        _temp_48 = -7.14533406406757 + placeholder_Normal_Log_Density((-3.0719515851703 + 0.000788534763755032 * WAVELETLLL_GLDM_LARGEDEPENDENCEH_LM));
    }
    if (jmp_is_missing(WAVELETLLL_GLSZM_GRAYLEVELNONUNI_FC))  {
        _temp_49 = 0;
    }
    else {
        _temp_49 = -5.26800558023833 + placeholder_Normal_Log_Density((-7.01227613871948 + 0.00515387932830395 * WAVELETLLL_GLSZM_GRAYLEVELNONUNI_FC));
    }
    if (jmp_is_missing(WAVELETLLL_GLSZM_GRAYLEVELVARIAN_MM))  {
        _temp_50 = 0;
    }
    else {
        _temp_50 = -1.54685845808043 + placeholder_Normal_Log_Density((-4.02302556113297 + 0.212915808199448 * WAVELETLLL_GLSZM_GRAYLEVELVARIAN_MM));
    }
    if (jmp_is_missing(WAVELETLLL_NGTDM_BUSYNESS_TC))  {
        _temp_51 = 0;
    }
    else {
        _temp_51 = -0.552643489650962 + placeholder_Normal_Log_Density((-3.04057959159261 + 0.575426663625947 * WAVELETLLL_NGTDM_BUSYNESS_TC));
    }
    Naive_Score_Control_Naive_Score_Control = exp((34.6241315113461 + _temp_0 + _temp_1 + _temp_2 + _temp_3 + _temp_4 + _temp_5 + _temp_6 + _temp_7 + _temp_8 + _temp_9 + _temp_10 + _temp_11 + _temp_12 + _temp_13 + _temp_14 + _temp_15 + _temp_16 + _temp_17 + _temp_18 + _temp_19 + _temp_20 + _temp_21 + _temp_22 + _temp_23 + _temp_24 + _temp_25 + _temp_26 + _temp_27 + _temp_28 + _temp_29 + _temp_30 + _temp_31 + _temp_32 + _temp_33 + _temp_34 + _temp_35 + _temp_36 + _temp_37 + _temp_38 + _temp_39 + _temp_40 + _temp_41 + _temp_42 + _temp_43 + _temp_44 + _temp_45 + _temp_46 + _temp_47 + _temp_48 + _temp_49 + _temp_50 + _temp_51));

    Naive_Score_Sum_1 = Naive_Score_Case + Naive_Score_Control;

    NAIVE_PROB_CASE_NAIVE_PROB_CASE = Naive_Score_Case / Naive_Score_Sum_1;

    NAIVE_PROB_CONTROL_NAIVE_PROB_CONTROL = Naive_Score_Control / Naive_Score_Sum_1;

    _temp_53[0] = NAIVE_PROB_CASE;
    _temp_53[1] = NAIVE_PROB_CONTROL;
    _temp_52 = jmp_max_array(2, _temp_53);
    switch (_temp_52) {
        case 0: {
            _temp_54 = "Case";
        }
        break;
        case 1: {
            _temp_54 = "Control";
        }
    }
    strcpy_safe(NAIVE_PREDICTED_FORMULA_ITYPE1_NAIVE_PREDICTED_FORMULA_ITYPE1, _temp_54);

}


