/* 
 * SAS code generated by JMP v16.2.0
 * From the following model(s): 
 *   Naive Bayes - itype1
 * Variable name mapping: 
 *   Naive Predicted Formula itype1,!Naive Predicted Formula itype1 => Naive_Predicted_Formula_itype1_
 *   Naive Prob Case => Naive_Prob_Case
 *   Naive Prob Case,!Naive Prob Case => Naive_Prob_Case_Naive_Prob_Case
 *   Naive Prob Control => Naive_Prob_Control
 *   Naive Prob Control,!Naive Prob Control => Naive_Prob_Control_Naive_Prob_C
 *   Naive Score Case => Naive_Score_Case
 *   Naive Score Case,!Naive Score Case => Naive_Score_Case_Naive_Score_Ca
 *   Naive Score Control => Naive_Score_Control
 *   Naive Score Control,!Naive Score Control => Naive_Score_Control_Naive_Score
 *   Naive Score Sum_1 => Naive_Score_Sum_1
 *   original_firstorder_minimum_fc => original_firstorder_minimum_fc
 *   original_glszm_smallareaemphasis_fc => original_glszm_smallareaemphasis
 *   original_shape_elongation_lm => original_shape_elongation_lm
 *   original_shape_flatness_fc => original_shape_flatness_fc
 *   original_shape_sphericity_fc => original_shape_sphericity_fc
 *   original_shape_sphericity_mm => original_shape_sphericity_mm
 *   v455_fc => v455_fc
 *   v620_fc => v620_fc
 *   v810_mm => v810_mm
 *   wavelethhh_firstorder_minimum_fc => wavelethhh_firstorder_minimum_fc
 *   wavelethhh_firstorder_range_fc => wavelethhh_firstorder_range_fc
 *   wavelethhh_firstorder_skewness_fc => wavelethhh_firstorder_skewness_f
 *   wavelethhh_glcm_clustershade_mm => wavelethhh_glcm_clustershade_mm
 *   wavelethhh_glcm_imc1_lm => wavelethhh_glcm_imc1_lm
 *   wavelethhh_glrlm_runvariance_mm => wavelethhh_glrlm_runvariance_mm
 *   wavelethhh_glszm_largeareahighgr_fc => wavelethhh_glszm_largeareahighgr
 *   wavelethhl_firstorder_mean_mm => wavelethhl_firstorder_mean_mm
 *   wavelethhl_glcm_clusterprominenc_fc => wavelethhl_glcm_clusterprominenc
 *   wavelethhl_glcm_correlation_fc => wavelethhl_glcm_correlation_fc
 *   wavelethhl_glcm_correlation_mm => wavelethhl_glcm_correlation_mm
 *   wavelethhl_glcm_imc1_mm => wavelethhl_glcm_imc1_mm
 *   wavelethhl_glcm_imc1_tc => wavelethhl_glcm_imc1_tc
 *   wavelethhl_gldm_smalldependencel_fc => wavelethhl_gldm_smalldependencel
 *   wavelethhl_gldm_smalldependencel_mm => wavelethhl_gldm_smalldependence2
 *   wavelethhl_glrlm_longrunhighgray_mm => wavelethhl_glrlm_longrunhighgray
 *   wavelethhl_glszm_graylevelvarian_mm => wavelethhl_glszm_graylevelvarian
 *   wavelethhl_glszm_largearealowgra_fc => wavelethhl_glszm_largearealowgra
 *   wavelethhl_glszm_smallareaemphas_fc => wavelethhl_glszm_smallareaemphas
 *   wavelethhl_ngtdm_strength_fc => wavelethhl_ngtdm_strength_fc
 *   wavelethlh_firstorder_median_fc => wavelethlh_firstorder_median_fc
 *   wavelethlh_firstorder_median_lm => wavelethlh_firstorder_median_lm
 *   wavelethlh_glszm_largeareahighgr_tc => wavelethlh_glszm_largeareahighgr
 *   wavelethlh_glszm_zoneentropy_tc => wavelethlh_glszm_zoneentropy_tc
 *   wavelethll_firstorder_kurtosis_mm => wavelethll_firstorder_kurtosis_m
 *   wavelethll_firstorder_skewness_lm => wavelethll_firstorder_skewness_l
 *   wavelethll_glszm_graylevelnonuni_fc => wavelethll_glszm_graylevelnonuni
 *   wavelethll_glszm_largearealowgra_lm => wavelethll_glszm_largearealowgra
 *   wavelethll_glszm_smallareaemphas_fc => wavelethll_glszm_smallareaemphas
 *   wavelethll_ngtdm_busyness_mm => wavelethll_ngtdm_busyness_mm
 *   waveletlhh_firstorder_kurtosis_fc => waveletlhh_firstorder_kurtosis_f
 *   waveletlhh_firstorder_maximum_fc => waveletlhh_firstorder_maximum_fc
 *   waveletlhh_firstorder_maximum_mm => waveletlhh_firstorder_maximum_mm
 *   waveletlhh_firstorder_mean_fc => waveletlhh_firstorder_mean_fc
 *   waveletlhh_firstorder_median_fc => waveletlhh_firstorder_median_fc
 *   waveletlhh_firstorder_median_lm => waveletlhh_firstorder_median_lm
 *   waveletlhh_glszm_largearealowgra_fc => waveletlhh_glszm_largearealowgra
 *   waveletlhh_glszm_smallareaemphas_fc => waveletlhh_glszm_smallareaemphas
 *   waveletlhh_glszm_smallareaemphas_mm => waveletlhh_glszm_smallareaempha2
 *   waveletlhl_firstorder_minimum_tc => waveletlhl_firstorder_minimum_tc
 *   waveletlhl_firstorder_skewness_fc => waveletlhl_firstorder_skewness_f
 *   waveletlhl_firstorder_skewness_tc => waveletlhl_firstorder_skewness_t
 *   waveletlhl_glcm_clustershade_fc => waveletlhl_glcm_clustershade_fc
 *   waveletlhl_glcm_imc1_fc => waveletlhl_glcm_imc1_fc
 *   waveletlhl_glszm_smallarealowgra_fc => waveletlhl_glszm_smallarealowgra
 *   waveletlhl_glszm_zoneentropy_lm => waveletlhl_glszm_zoneentropy_lm
 *   waveletlhl_glszm_zoneentropy_mm => waveletlhl_glszm_zoneentropy_mm
 *   waveletllh_firstorder_minimum_fc => waveletllh_firstorder_minimum_fc
 *   waveletllh_glcm_correlation_mm => waveletllh_glcm_correlation_mm
 *   waveletllh_glcm_imc1_mm => waveletllh_glcm_imc1_mm
 *   waveletllh_gldm_smalldependencel_mm => waveletllh_gldm_smalldependencel
 *   waveletllh_glszm_smallarealowgra_fc => waveletllh_glszm_smallarealowgra
 *   waveletllh_glszm_zoneentropy_fc => waveletllh_glszm_zoneentropy_fc
 *   waveletlll_glcm_clustershade_lm => waveletlll_glcm_clustershade_lm
 *   waveletlll_glcm_idn_fc => waveletlll_glcm_idn_fc
 *   waveletlll_glcm_imc2_fc => waveletlll_glcm_imc2_fc
 *   waveletlll_gldm_largedependenceh_lm => waveletlll_gldm_largedependenceh
 *   waveletlll_glszm_graylevelnonuni_fc => waveletlll_glszm_graylevelnonuni
 *   waveletlll_glszm_graylevelvarian_mm => waveletlll_glszm_graylevelvarian
 *   waveletlll_ngtdm_busyness_tc => waveletlll_ngtdm_busyness_tc
 */
DECLARE int idx_max;
DECLARE double val_max;
DECLARE double acc_max;
idx_max = 0;
acc_max = .;

Naive_Score_Control = Exp(((-0.694968674688336 + ( IF (wavelethhl_glcm_clusterprominenc=.) THEN 0 ELSE Unhandled operator: Normal Log Density - 
  -0.477363196165406) + ( IF (wavelethhl_glszm_largearealowgra=.) THEN 0 ELSE Unhandled operator: Normal Log Density - 13.113651920005) + 
  ( IF (waveletllh_glszm_zoneentropy_fc=.) THEN 0 ELSE Unhandled operator: Normal Log Density - -1.85310567037502) + ( IF (
  original_glszm_smallareaemphasis=.) THEN 0 ELSE Unhandled operator: Normal Log Density - -4.45430998046867) + ( IF (v620_fc=.) THEN 
  0 ELSE Unhandled operator: Normal Log Density - -3.73856978889719) + ( IF (wavelethll_glszm_graylevelnonuni=.) THEN 0 ELSE 
  Unhandled operator: Normal Log Density - 5.82341912579405) + ( IF (waveletlll_glcm_imc2_fc=.) THEN 0 ELSE Unhandled operator: Normal Log Density - 
  -3.41306078174522) + ( IF (wavelethll_glszm_smallareaemphas=.) THEN 0 ELSE Unhandled operator: Normal Log Density - -3.8749070750095) + 
  ( IF (waveletllh_firstorder_minimum_fc=.) THEN 0 ELSE Unhandled operator: Normal Log Density - 3.65385200986414) + ( IF (
  waveletlll_glszm_graylevelnonuni=.) THEN 0 ELSE Unhandled operator: Normal Log Density - 5.26800558023833) + ( IF (v455_fc=.) THEN 
  0 ELSE Unhandled operator: Normal Log Density - -6.44336298478878) + ( IF (wavelethhl_glszm_smallareaemphas=.) THEN 0 ELSE 
  Unhandled operator: Normal Log Density - -3.70455119260605) + ( IF (waveletlhh_firstorder_kurtosis_f=.) THEN 0 ELSE Unhandled operator: Normal Log Density - 
  -0.632467198106385) + ( IF (waveletlhh_glszm_largearealowgra=.) THEN 0 ELSE Unhandled operator: Normal Log Density - 10.0601241203535) + 
  ( IF (waveletlhh_firstorder_maximum_fc=.) THEN 0 ELSE Unhandled operator: Normal Log Density - 3.30553730949187) + ( IF (
  wavelethhl_glcm_correlation_fc=.) THEN 0 ELSE Unhandled operator: Normal Log Density - -4.66665052831902) + ( IF (wavelethhh_glszm_largeareahighgr=.) THEN 
  0 ELSE Unhandled operator: Normal Log Density - 18.7357919582415) + ( IF (waveletlll_glcm_idn_fc=.) THEN 0 ELSE Unhandled operator: Normal Log Density - 
  -5.18820141715545) + ( IF (waveletllh_glszm_smallarealowgra=.) THEN 0 ELSE Unhandled operator: Normal Log Density - -6.06793135169111) + 
  ( IF (wavelethhl_gldm_smalldependencel=.) THEN 0 ELSE Unhandled operator: Normal Log Density - -7.17009026198478) + ( IF 
  (waveletlhl_firstorder_skewness_f=.) THEN 0 ELSE Unhandled operator: Normal Log Density - -2.25784725874085) + ( IF (original_firstorder_minimum_fc=.) THEN 
  0 ELSE Unhandled operator: Normal Log Density - 1.40769939648407) + ( IF (waveletlhl_glcm_clustershade_fc=.) THEN 0 ELSE 
  Unhandled operator: Normal Log Density - 0.703322748122837) + ( IF (waveletlhl_glcm_imc1_fc=.) THEN 0 ELSE Unhandled operator: Normal Log Density - 
  -4.95037773556667) + ( IF (original_shape_flatness_fc=.) THEN 0 ELSE Unhandled operator: Normal Log Density - -4.13168120430342) + 
  ( IF (waveletlhh_firstorder_mean_fc=.) THEN 0 ELSE Unhandled operator: Normal Log Density - -1.78397890138743) + ( IF (wavelethhh_firstorder_skewness_f=.) THEN 
  0 ELSE Unhandled operator: Normal Log Density - -3.26585666835064) + ( IF (wavelethhl_ngtdm_strength_fc=.) THEN 0 ELSE Unhandled operator: Normal Log Density - 
  -7.80289852601175) + ( IF (wavelethhh_firstorder_range_fc=.) THEN 0 ELSE Unhandled operator: Normal Log Density - 3.02722532189808) + 
  ( IF (original_shape_sphericity_fc=.) THEN 0 ELSE Unhandled operator: Normal Log Density - -4.5164914454503) + ( IF (waveletlhl_glszm_smallarealowgra=.) THEN 
  0 ELSE Unhandled operator: Normal Log Density - -5.75225051694584) + ( IF (waveletlhh_firstorder_median_fc=.) THEN 0 ELSE 
  Unhandled operator: Normal Log Density - -2.17517816728054) + ( IF (waveletlhh_glszm_smallareaemphas=.) THEN 0 ELSE Unhandled operator: Normal Log Density - 
  -4.1671456061931) + ( IF (wavelethhh_firstorder_minimum_fc=.) THEN 0 ELSE Unhandled operator: Normal Log Density - 2.30023168733928) + 
  ( IF (wavelethlh_firstorder_median_fc=.) THEN 0 ELSE Unhandled operator: Normal Log Density - -2.6828757175276)) - -7.49466227243816));
Naive_Score_Case = 
  Exp(((-0.691328998240887 + ( IF (wavelethhl_glcm_clusterprominenc=.) THEN 0 ELSE Unhandled operator: Normal Log Density - 
  -0.367762195190062) + ( IF (wavelethhl_glszm_largearealowgra=.) THEN 0 ELSE Unhandled operator: Normal Log Density - 12.5758732165363) + 
  ( IF (waveletllh_glszm_zoneentropy_fc=.) THEN 0 ELSE Unhandled operator: Normal Log Density - -2.05341859048501) + ( IF (
  original_glszm_smallareaemphasis=.) THEN 0 ELSE Unhandled operator: Normal Log Density - -4.44733947727752) + ( IF (v620_fc=.) THEN 
  0 ELSE Unhandled operator: Normal Log Density - -3.68114352907466) + ( IF (wavelethll_glszm_graylevelnonuni=.) THEN 0 ELSE 
  Unhandled operator: Normal Log Density - 5.87358100022121) + ( IF (waveletlll_glcm_imc2_fc=.) THEN 0 ELSE Unhandled operator: Normal Log Density - 
  -3.32345486225934) + ( IF (wavelethll_glszm_smallareaemphas=.) THEN 0 ELSE Unhandled operator: Normal Log Density - -3.86470676255455) + 
  ( IF (waveletllh_firstorder_minimum_fc=.) THEN 0 ELSE Unhandled operator: Normal Log Density - 3.48823397791469) + ( IF (
  waveletlll_glszm_graylevelnonuni=.) THEN 0 ELSE Unhandled operator: Normal Log Density - 5.28359597007616) + ( IF (v455_fc=.) THEN 
  0 ELSE Unhandled operator: Normal Log Density - -6.38732442525786) + ( IF (wavelethhl_glszm_smallareaemphas=.) THEN 0 ELSE 
  Unhandled operator: Normal Log Density - -3.80145451285076) + ( IF (waveletlhh_firstorder_kurtosis_f=.) THEN 0 ELSE Unhandled operator: Normal Log Density - 
  -0.745188632141356) + ( IF (waveletlhh_glszm_largearealowgra=.) THEN 0 ELSE Unhandled operator: Normal Log Density - 10.1046080889352) + 
  ( IF (waveletlhh_firstorder_maximum_fc=.) THEN 0 ELSE Unhandled operator: Normal Log Density - 3.18130339726819) + ( IF (
  wavelethhl_glcm_correlation_fc=.) THEN 0 ELSE Unhandled operator: Normal Log Density - -4.70765736503791) + ( IF (wavelethhh_glszm_largeareahighgr=.) THEN 
  0 ELSE Unhandled operator: Normal Log Density - 18.5241459793942) + ( IF (waveletlll_glcm_idn_fc=.) THEN 0 ELSE Unhandled operator: Normal Log Density - 
  -5.15215214500179) + ( IF (waveletllh_glszm_smallarealowgra=.) THEN 0 ELSE Unhandled operator: Normal Log Density - -6.23750899477973) + 
  ( IF (wavelethhl_gldm_smalldependencel=.) THEN 0 ELSE Unhandled operator: Normal Log Density - -7.12776104358228) + ( IF 
  (waveletlhl_firstorder_skewness_f=.) THEN 0 ELSE Unhandled operator: Normal Log Density - -2.33942548616718) + ( IF (original_firstorder_minimum_fc=.) THEN 
  0 ELSE Unhandled operator: Normal Log Density - 1.46199231976722) + ( IF (waveletlhl_glcm_clustershade_fc=.) THEN 0 ELSE 
  Unhandled operator: Normal Log Density - 0.608586649003487) + ( IF (waveletlhl_glcm_imc1_fc=.) THEN 0 ELSE Unhandled operator: Normal Log Density - 
  -5.00267206392272) + ( IF (original_shape_flatness_fc=.) THEN 0 ELSE Unhandled operator: Normal Log Density - -4.1039110663958) + 
  ( IF (waveletlhh_firstorder_mean_fc=.) THEN 0 ELSE Unhandled operator: Normal Log Density - -1.8970834747993) + ( IF (wavelethhh_firstorder_skewness_f=.) THEN 
  0 ELSE Unhandled operator: Normal Log Density - -3.39821997035615) + ( IF (wavelethhl_ngtdm_strength_fc=.) THEN 0 ELSE Unhandled operator: Normal Log Density - 
  -7.50001304528774) + ( IF (wavelethhh_firstorder_range_fc=.) THEN 0 ELSE Unhandled operator: Normal Log Density - 3.02764406235429) + 
  ( IF (original_shape_sphericity_fc=.) THEN 0 ELSE Unhandled operator: Normal Log Density - -4.41223787150666) + ( IF (waveletlhl_glszm_smallarealowgra=.) THEN 
  0 ELSE Unhandled operator: Normal Log Density - -5.67767402013621) + ( IF (waveletlhh_firstorder_median_fc=.) THEN 0 ELSE 
  Unhandled operator: Normal Log Density - -2.24021879491245) + ( IF (waveletlhh_glszm_smallareaemphas=.) THEN 0 ELSE Unhandled operator: Normal Log Density - 
  -4.29474871094496) + ( IF (wavelethhh_firstorder_minimum_fc=.) THEN 0 ELSE Unhandled operator: Normal Log Density - 2.27645362013997) + 
  ( IF (wavelethlh_firstorder_median_fc=.) THEN 0 ELSE Unhandled operator: Normal Log Density - -2.73476302359835)) - -7.49466227243816));
Naive_Score_Case_Naive_Score_Ca = 
  Exp((34.6277711877936 + ( IF (original_firstorder_minimum_fc=.) THEN 0 ELSE -1.46199231976722 + Unhandled operator: Normal Log Density) + 
  ( IF (original_glszm_smallareaemphasis=.) THEN 0 ELSE 4.44733947727752 + Unhandled operator: Normal Log Density) + ( IF (
  original_shape_elongation_lm=.) THEN 0 ELSE 3.44606835567658 + Unhandled operator: Normal Log Density) + ( IF (original_shape_sphericity_mm=.) THEN 
  0 ELSE 4.11882837625468 + Unhandled operator: Normal Log Density) + ( IF (v455_fc=.) THEN 0 ELSE 6.38732442525786 + Unhandled operator: Normal Log Density) + 
  ( IF (v620_fc=.) THEN 0 ELSE 3.68114352907466 + Unhandled operator: Normal Log Density) + ( IF (v810_mm=.) THEN 0 ELSE 3.56963151869869 + 
  Unhandled operator: Normal Log Density) + ( IF (wavelethhh_firstorder_minimum_fc=.) THEN 0 ELSE -2.27645362013997 + Unhandled operator: Normal Log Density) + 
  ( IF (wavelethhh_glcm_clustershade_mm=.) THEN 0 ELSE 6.1117886359281 + Unhandled operator: Normal Log Density) + ( IF (wavelethhh_glcm_imc1_lm=.) THEN 
  0 ELSE 6.295915992492 + Unhandled operator: Normal Log Density) + ( IF (wavelethhh_glrlm_runvariance_mm=.) THEN 0 ELSE 3.04311278910496 + 
  Unhandled operator: Normal Log Density) + ( IF (wavelethhh_glszm_largeareahighgr=.) THEN 0 ELSE -18.5241459793942 + Unhandled operator: Normal Log Density) + 
  ( IF (wavelethhl_firstorder_mean_mm=.) THEN 0 ELSE 2.70956162763264 + Unhandled operator: Normal Log Density) + ( IF (wavelethhl_glcm_clusterprominenc=.) THEN 
  0 ELSE 0.367762195190062 + Unhandled operator: Normal Log Density) + ( IF (wavelethhl_glcm_correlation_mm=.) THEN 0 ELSE 
  4.84443991609403 + Unhandled operator: Normal Log Density) + ( IF (wavelethhl_glcm_imc1_mm=.) THEN 0 ELSE 5.86572242567548 + 
  Unhandled operator: Normal Log Density) + ( IF (wavelethhl_glcm_imc1_tc=.) THEN 0 ELSE 5.09218436015282 + Unhandled operator: Normal Log Density) + 
  ( IF (wavelethhl_gldm_smalldependencel=.) THEN 0 ELSE 7.12776104358228 + Unhandled operator: Normal Log Density) + ( IF (
  wavelethhl_gldm_smalldependence2=.) THEN 0 ELSE 6.3638351761944 + Unhandled operator: Normal Log Density) + ( IF (wavelethhl_glrlm_longrunhighgray=.) THEN 
  0 ELSE -2.73928991543196 + Unhandled operator: Normal Log Density) + ( IF (wavelethhl_glszm_graylevelvarian=.) THEN 0 ELSE 
  2.1356673758417 + Unhandled operator: Normal Log Density) + ( IF (wavelethhl_glszm_largearealowgra=.) THEN 0 ELSE -12.5758732165363 + 
  Unhandled operator: Normal Log Density) + ( IF (wavelethhl_glszm_smallareaemphas=.) THEN 0 ELSE 3.80145451285076 + Unhandled operator: Normal Log Density) + 
  ( IF (wavelethlh_firstorder_median_lm=.) THEN 0 ELSE 2.54431537659471 + Unhandled operator: Normal Log Density) + ( IF (wavelethlh_glszm_largeareahighgr=.) THEN 
  0 ELSE -15.6127399919531 + Unhandled operator: Normal Log Density) + ( IF (wavelethlh_glszm_zoneentropy_tc=.) THEN 0 ELSE 
  1.38869060606963 + Unhandled operator: Normal Log Density) + ( IF (wavelethll_firstorder_kurtosis_m=.) THEN 0 ELSE -0.0630495017190976 + 
  Unhandled operator: Normal Log Density) + ( IF (wavelethll_firstorder_skewness_l=.) THEN 0 ELSE 2.17979912130199 + Unhandled operator: Normal Log Density) + 
  ( IF (wavelethll_glszm_graylevelnonuni=.) THEN 0 ELSE -5.87358100022121 + Unhandled operator: Normal Log Density) + ( IF 
  (wavelethll_glszm_largearealowgra=.) THEN 0 ELSE -9.90527073944226 + Unhandled operator: Normal Log Density) + ( IF (wavelethll_glszm_smallareaemphas=.) THEN 
  0 ELSE 3.86470676255455 + Unhandled operator: Normal Log Density) + ( IF (wavelethll_ngtdm_busyness_mm=.) THEN 0 ELSE -3.88411860577591 + 
  Unhandled operator: Normal Log Density) + ( IF (waveletlhh_firstorder_maximum_mm=.) THEN 0 ELSE -2.85313131418634 + Unhandled operator: Normal Log Density) + 
  ( IF (waveletlhh_firstorder_median_lm=.) THEN 0 ELSE 1.60255743076681 + Unhandled operator: Normal Log Density) + ( IF (waveletlhh_glszm_smallareaempha2=.) THEN 
  0 ELSE 3.45355496537128 + Unhandled operator: Normal Log Density) + ( IF (waveletlhl_firstorder_minimum_tc=.) THEN 0 ELSE 
  -3.52185911077717 + Unhandled operator: Normal Log Density) + ( IF (waveletlhl_firstorder_skewness_f=.) THEN 0 ELSE 2.33942548616718 + 
  Unhandled operator: Normal Log Density) + ( IF (waveletlhl_firstorder_skewness_t=.) THEN 0 ELSE 2.15458993069675 + Unhandled operator: Normal Log Density) + 
  ( IF (waveletlhl_glcm_clustershade_fc=.) THEN 0 ELSE -0.608586649003487 + Unhandled operator: Normal Log Density) + ( IF 
  (waveletlhl_glszm_zoneentropy_lm=.) THEN 0 ELSE 1.53342352773912 + Unhandled operator: Normal Log Density) + ( IF (waveletlhl_glszm_zoneentropy_mm=.) THEN 
  0 ELSE 1.57517275864608 + Unhandled operator: Normal Log Density) + ( IF (waveletllh_firstorder_minimum_fc=.) THEN 0 ELSE 
  -3.48823397791469 + Unhandled operator: Normal Log Density) + ( IF (waveletllh_glcm_correlation_mm=.) THEN 0 ELSE 3.75103276771794 + 
  Unhandled operator: Normal Log Density) + ( IF (waveletllh_glcm_imc1_mm=.) THEN 0 ELSE 4.94210163225806 + Unhandled operator: Normal Log Density) + 
  ( IF (waveletllh_gldm_smalldependencel=.) THEN 0 ELSE 7.74926382754169 + Unhandled operator: Normal Log Density) + ( IF (
  waveletllh_glszm_zoneentropy_fc=.) THEN 0 ELSE 2.05341859048501 + Unhandled operator: Normal Log Density) + ( IF (waveletlll_glcm_clustershade_lm=.) THEN 
  0 ELSE -4.74202851674432 + Unhandled operator: Normal Log Density) + ( IF (waveletlll_glcm_idn_fc=.) THEN 0 ELSE 5.15215214500179 + 
  Unhandled operator: Normal Log Density) + ( IF (waveletlll_gldm_largedependenceh=.) THEN 0 ELSE -7.25370444027467 + Unhandled operator: Normal Log Density) + 
  ( IF (waveletlll_glszm_graylevelnonuni=.) THEN 0 ELSE -5.28359597007616 + Unhandled operator: Normal Log Density) + ( IF 
  (waveletlll_glszm_graylevelvarian=.) THEN 0 ELSE -1.37760604528278 + Unhandled operator: Normal Log Density) + ( IF (waveletlll_ngtdm_busyness_tc=.) THEN 
  0 ELSE -0.612493937893744 + Unhandled operator: Normal Log Density)));
Naive_Score_Control_Naive_Score = Exp((34.6241315113461 + 
  ( IF (original_firstorder_minimum_fc=.) THEN 0 ELSE -1.40769939648407 + Unhandled operator: Normal Log Density) + ( IF (original_glszm_smallareaemphasis=.) THEN 
  0 ELSE 4.45430998046867 + Unhandled operator: Normal Log Density) + ( IF (original_shape_elongation_lm=.) THEN 0 ELSE 3.41891935472661 + 
  Unhandled operator: Normal Log Density) + ( IF (original_shape_sphericity_mm=.) THEN 0 ELSE 4.26831338745469 + Unhandled operator: Normal Log Density) + 
  ( IF (v455_fc=.) THEN 0 ELSE 6.44336298478878 + Unhandled operator: Normal Log Density) + ( IF (v620_fc=.) THEN 0 ELSE 3.73856978889719 + 
  Unhandled operator: Normal Log Density) + ( IF (v810_mm=.) THEN 0 ELSE 3.47763123013267 + Unhandled operator: Normal Log Density) + 
  ( IF (wavelethhh_firstorder_minimum_fc=.) THEN 0 ELSE -2.30023168733928 + Unhandled operator: Normal Log Density) + ( IF 
  (wavelethhh_glcm_clustershade_mm=.) THEN 0 ELSE 6.04272594054893 + Unhandled operator: Normal Log Density) + ( IF (wavelethhh_glcm_imc1_lm=.) THEN 
  0 ELSE 6.25214962802694 + Unhandled operator: Normal Log Density) + ( IF (wavelethhh_glrlm_runvariance_mm=.) THEN 0 ELSE 
  3.10710652673805 + Unhandled operator: Normal Log Density) + ( IF (wavelethhh_glszm_largeareahighgr=.) THEN 0 ELSE -18.7357919582415 + 
  Unhandled operator: Normal Log Density) + ( IF (wavelethhl_firstorder_mean_mm=.) THEN 0 ELSE 2.70525857133555 + Unhandled operator: Normal Log Density) + 
  ( IF (wavelethhl_glcm_clusterprominenc=.) THEN 0 ELSE 0.477363196165406 + Unhandled operator: Normal Log Density) + ( IF 
  (wavelethhl_glcm_correlation_mm=.) THEN 0 ELSE 4.86411657208708 + Unhandled operator: Normal Log Density) + ( IF (wavelethhl_glcm_imc1_mm=.) THEN 
  0 ELSE 5.81907677801971 + Unhandled operator: Normal Log Density) + ( IF (wavelethhl_glcm_imc1_tc=.) THEN 0 ELSE 5.19405641049375 + 
  Unhandled operator: Normal Log Density) + ( IF (wavelethhl_gldm_smalldependencel=.) THEN 0 ELSE 7.17009026198478 + Unhandled operator: Normal Log Density) + 
  ( IF (wavelethhl_gldm_smalldependence2=.) THEN 0 ELSE 6.52352511955377 + Unhandled operator: Normal Log Density) + ( IF (
  wavelethhl_glrlm_longrunhighgray=.) THEN 0 ELSE -2.63485330816982 + Unhandled operator: Normal Log Density) + ( IF (wavelethhl_glszm_graylevelvarian=.) THEN 
  0 ELSE 2.16538277287389 + Unhandled operator: Normal Log Density) + ( IF (wavelethhl_glszm_largearealowgra=.) THEN 0 ELSE 
  -13.113651920005 + Unhandled operator: Normal Log Density) + ( IF (wavelethhl_glszm_smallareaemphas=.) THEN 0 ELSE 3.70455119260605 + 
  Unhandled operator: Normal Log Density) + ( IF (wavelethlh_firstorder_median_lm=.) THEN 0 ELSE 2.58086805713443 + Unhandled operator: Normal Log Density) + 
  ( IF (wavelethlh_glszm_largeareahighgr=.) THEN 0 ELSE -16.2484481795929 + Unhandled operator: Normal Log Density) + ( IF 
  (wavelethlh_glszm_zoneentropy_tc=.) THEN 0 ELSE 1.23494870747774 + Unhandled operator: Normal Log Density) + ( IF (wavelethll_firstorder_kurtosis_m=.) THEN 
  0 ELSE -0.0159978298628314 + Unhandled operator: Normal Log Density) + ( IF (wavelethll_firstorder_skewness_l=.) THEN 0 ELSE 
  2.22294791043496 + Unhandled operator: Normal Log Density) + ( IF (wavelethll_glszm_graylevelnonuni=.) THEN 0 ELSE -5.82341912579405 + 
  Unhandled operator: Normal Log Density) + ( IF (wavelethll_glszm_largearealowgra=.) THEN 0 ELSE -10.3949557796378 + Unhandled operator: Normal Log Density) + 
  ( IF (wavelethll_glszm_smallareaemphas=.) THEN 0 ELSE 3.8749070750095 + Unhandled operator: Normal Log Density) + ( IF (wavelethll_ngtdm_busyness_mm=.) THEN 
  0 ELSE -3.76084689092138 + Unhandled operator: Normal Log Density) + ( IF (waveletlhh_firstorder_maximum_mm=.) THEN 0 ELSE 
  -2.91278319745801 + Unhandled operator: Normal Log Density) + ( IF (waveletlhh_firstorder_median_lm=.) THEN 0 ELSE 1.5722574761603 + 
  Unhandled operator: Normal Log Density) + ( IF (waveletlhh_glszm_smallareaempha2=.) THEN 0 ELSE 3.44307652207182 + Unhandled operator: Normal Log Density) + 
  ( IF (waveletlhl_firstorder_minimum_tc=.) THEN 0 ELSE -3.68257473265745 + Unhandled operator: Normal Log Density) + ( IF 
  (waveletlhl_firstorder_skewness_f=.) THEN 0 ELSE 2.25784725874086 + Unhandled operator: Normal Log Density) + ( IF (waveletlhl_firstorder_skewness_t=.) THEN 
  0 ELSE 2.109042275387 + Unhandled operator: Normal Log Density) + ( IF (waveletlhl_glcm_clustershade_fc=.) THEN 0 ELSE -0.703322748122837 + 
  Unhandled operator: Normal Log Density) + ( IF (waveletlhl_glszm_zoneentropy_lm=.) THEN 0 ELSE 1.44425080952749 + Unhandled operator: Normal Log Density) + 
  ( IF (waveletlhl_glszm_zoneentropy_mm=.) THEN 0 ELSE 1.51688970045589 + Unhandled operator: Normal Log Density) + ( IF (waveletllh_firstorder_minimum_fc=.) THEN 
  0 ELSE -3.65385200986414 + Unhandled operator: Normal Log Density) + ( IF (waveletllh_glcm_correlation_mm=.) THEN 0 ELSE 
  3.67331648930703 + Unhandled operator: Normal Log Density) + ( IF (waveletllh_glcm_imc1_mm=.) THEN 0 ELSE 4.82020658287596 + 
  Unhandled operator: Normal Log Density) + ( IF (waveletllh_gldm_smalldependencel=.) THEN 0 ELSE 7.70860795755376 + Unhandled operator: Normal Log Density) + 
  ( IF (waveletllh_glszm_zoneentropy_fc=.) THEN 0 ELSE 1.85310567037502 + Unhandled operator: Normal Log Density) + ( IF (waveletlll_glcm_clustershade_lm=.) THEN 
  0 ELSE -4.88425952849476 + Unhandled operator: Normal Log Density) + ( IF (waveletlll_glcm_idn_fc=.) THEN 0 ELSE 5.18820141715545 + 
  Unhandled operator: Normal Log Density) + ( IF (waveletlll_gldm_largedependenceh=.) THEN 0 ELSE -7.14533406406757 + Unhandled operator: Normal Log Density) + 
  ( IF (waveletlll_glszm_graylevelnonuni=.) THEN 0 ELSE -5.26800558023833 + Unhandled operator: Normal Log Density) + ( IF 
  (waveletlll_glszm_graylevelvarian=.) THEN 0 ELSE -1.54685845808043 + Unhandled operator: Normal Log Density) + ( IF (waveletlll_ngtdm_busyness_tc=.) THEN 
  0 ELSE -0.552643489650962 + Unhandled operator: Normal Log Density)));
Naive_Score_Sum_1 = Naive_Score_Case + Naive_Score_Control;
Naive_Prob_Case_Naive_Prob_Case = 
  Naive_Score_Case/Naive_Score_Sum_1;
Naive_Prob_Control_Naive_Prob_C = Naive_Score_Control/Naive_Score_Sum_1;
val_max = Naive_Prob_Case;
IF (not missing(val_max) AND (missing(acc_max) OR val_max > acc_max)) THEN DO;
  idx_max = 1;
  acc_max = val_max;
END;
val_max = Naive_Prob_Control;
IF (not missing(val_max) AND (missing(acc_max) OR val_max > acc_max)) THEN DO;
  idx_max = 2;
  acc_max = val_max;
END;

Naive_Predicted_Formula_itype1_ = 
  
 SELECT (idx_max)
  WHEN (1) 'Case'
  WHEN (2) 'Control'
  OTHERWISE ''
 END
;
drop Naive_Score_Case Naive_Score_Case_Naive_Score_Ca Naive_Score_Control Naive_Score_Control_Naive_Score Naive_Score_Sum_1;
