/* 
 * SAS code generated by JMP v16.2.0
 * From the following model(s): 
 *   Boosted Tree - itype1
 * Variable name mapping: 
 *   Most Likely itype1,!Most Likely itype1 => Most_Likely_itype1_Most_Likely_
 *   Prob(itype1==Case),!Prob(itype1==Case) => Prob_itype1_Case_Prob_itype1_
 *   Prob(itype1==Control) => Prob_itype1_Control_
 *   Prob(itype1==Control),!Prob(itype1==Control) => Prob_itype1_Control_Prob_ityp
 *   original_firstorder_minimum_fc => original_firstorder_minimum_fc
 *   original_glszm_smallareaemphasis_fc => original_glszm_smallareaemphasis
 *   original_shape_elongation_lm => original_shape_elongation_lm
 *   original_shape_sphericity_mm => original_shape_sphericity_mm
 *   v455_fc => v455_fc
 *   v620_fc => v620_fc
 *   v810_mm => v810_mm
 *   wavelethhh_firstorder_minimum_fc => wavelethhh_firstorder_minimum_fc
 *   wavelethhh_glcm_clustershade_mm => wavelethhh_glcm_clustershade_mm
 *   wavelethhh_glcm_imc1_lm => wavelethhh_glcm_imc1_lm
 *   wavelethhh_glrlm_runvariance_mm => wavelethhh_glrlm_runvariance_mm
 *   wavelethhh_glszm_largeareahighgr_fc => wavelethhh_glszm_largeareahighgr
 *   wavelethhl_firstorder_mean_mm => wavelethhl_firstorder_mean_mm
 *   wavelethhl_glcm_clusterprominenc_fc => wavelethhl_glcm_clusterprominenc
 *   wavelethhl_glcm_correlation_mm => wavelethhl_glcm_correlation_mm
 *   wavelethhl_glcm_imc1_mm => wavelethhl_glcm_imc1_mm
 *   wavelethhl_glcm_imc1_tc => wavelethhl_glcm_imc1_tc
 *   wavelethhl_gldm_smalldependencel_fc => wavelethhl_gldm_smalldependencel
 *   wavelethhl_gldm_smalldependencel_mm => wavelethhl_gldm_smalldependence2
 *   wavelethhl_glrlm_longrunhighgray_mm => wavelethhl_glrlm_longrunhighgray
 *   wavelethhl_glszm_graylevelvarian_mm => wavelethhl_glszm_graylevelvarian
 *   wavelethhl_glszm_largearealowgra_fc => wavelethhl_glszm_largearealowgra
 *   wavelethhl_glszm_smallareaemphas_fc => wavelethhl_glszm_smallareaemphas
 *   wavelethlh_firstorder_median_lm => wavelethlh_firstorder_median_lm
 *   wavelethlh_glszm_largeareahighgr_tc => wavelethlh_glszm_largeareahighgr
 *   wavelethlh_glszm_zoneentropy_tc => wavelethlh_glszm_zoneentropy_tc
 *   wavelethll_firstorder_kurtosis_mm => wavelethll_firstorder_kurtosis_m
 *   wavelethll_firstorder_skewness_lm => wavelethll_firstorder_skewness_l
 *   wavelethll_glszm_graylevelnonuni_fc => wavelethll_glszm_graylevelnonuni
 *   wavelethll_glszm_largearealowgra_lm => wavelethll_glszm_largearealowgra
 *   wavelethll_glszm_smallareaemphas_fc => wavelethll_glszm_smallareaemphas
 *   wavelethll_ngtdm_busyness_mm => wavelethll_ngtdm_busyness_mm
 *   waveletlhh_firstorder_maximum_mm => waveletlhh_firstorder_maximum_mm
 *   waveletlhh_firstorder_median_lm => waveletlhh_firstorder_median_lm
 *   waveletlhh_glszm_smallareaemphas_mm => waveletlhh_glszm_smallareaemphas
 *   waveletlhl_firstorder_skewness_fc => waveletlhl_firstorder_skewness_f
 *   waveletlhl_firstorder_skewness_tc => waveletlhl_firstorder_skewness_t
 *   waveletlhl_glcm_clustershade_fc => waveletlhl_glcm_clustershade_fc
 *   waveletlhl_glszm_zoneentropy_lm => waveletlhl_glszm_zoneentropy_lm
 *   waveletlhl_glszm_zoneentropy_mm => waveletlhl_glszm_zoneentropy_mm
 *   waveletllh_firstorder_minimum_fc => waveletllh_firstorder_minimum_fc
 *   waveletllh_glcm_correlation_mm => waveletllh_glcm_correlation_mm
 *   waveletllh_glcm_imc1_mm => waveletllh_glcm_imc1_mm
 *   waveletllh_gldm_smalldependencel_mm => waveletllh_gldm_smalldependencel
 *   waveletllh_glszm_zoneentropy_fc => waveletllh_glszm_zoneentropy_fc
 *   waveletlll_glcm_clustershade_lm => waveletlll_glcm_clustershade_lm
 *   waveletlll_glcm_idn_fc => waveletlll_glcm_idn_fc
 *   waveletlll_gldm_largedependenceh_lm => waveletlll_gldm_largedependenceh
 *   waveletlll_glszm_graylevelnonuni_fc => waveletlll_glszm_graylevelnonuni
 *   waveletlll_glszm_graylevelvarian_mm => waveletlll_glszm_graylevelvarian
 *   waveletlll_ngtdm_busyness_tc => waveletlll_ngtdm_busyness_tc
 */
DECLARE int idx_max;
DECLARE double val_max;
DECLARE double acc_max;
idx_max = 0;
acc_max = .;

Prob_itype1_Control_Prob_ityp = (1/(1+exp(-((-0.00364299127850098 + ( IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  4 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 1 THEN -0.0142746853045488 ELSE IF (waveletllh_gldm_smalldependencel=.) OR 
  waveletllh_gldm_smalldependencel < 0.00133976 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  3 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 2 THEN -0.0397688689914123 ELSE -0.0481159148671486 ELSE 
  -0.0284100871350376 ELSE IF (wavelethll_glszm_graylevelnonuni=.) OR wavelethll_glszm_graylevelnonuni < 620.99752 THEN -0.100995833068607 ELSE IF 
  (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 3 THEN 0.34681800951626 ELSE 0.113897023050604 ELSE 
  -0.000357191758547325) + ( IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 4 THEN  IF (original_firstorder_minimum_fc=.) OR 
  original_firstorder_minimum_fc < 3 THEN  IF (v620_fc=.) OR v620_fc < 0.44626562 THEN  IF (original_firstorder_minimum_fc=.) OR 
  original_firstorder_minimum_fc < 1 THEN -0.0322760570066295 ELSE -0.0611359690162508 ELSE 0.0529351079181299 ELSE IF (wavelethhh_glrlm_runvariance_mm=.) OR 
  wavelethhh_glrlm_runvariance_mm < 1.3428649 THEN  IF (wavelethhl_glcm_imc1_mm=.) OR wavelethhl_glcm_imc1_mm < -0.01675079 THEN 
  -0.0010141560761142 ELSE IF (wavelethhh_glcm_imc1_lm=.) OR wavelethhh_glcm_imc1_lm < -0.0098059 THEN -0.0991964207275028 ELSE 
  -0.354068013995786 ELSE 0.0926833798907364 ELSE 0.000865142697678387) + ( IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  4 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 3 THEN  IF (waveletlhl_firstorder_skewness_t=.) OR 
  waveletlhl_firstorder_skewness_t < -0.04958327 THEN 0.361340016130775 ELSE IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  1 THEN -0.0181346864761864 ELSE IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 2 THEN -0.0375169971249602 ELSE 
  -0.055388975342186 ELSE IF (wavelethll_glszm_graylevelnonuni=.) OR wavelethll_glszm_graylevelnonuni < 669.49855 THEN  IF 
  (waveletllh_gldm_smalldependencel=.) OR waveletllh_gldm_smalldependencel < 0.00123577 THEN -0.0731318599758024 ELSE -0.353716004395296 ELSE 
  0.0292529031518697 ELSE 0.000991785541724662) + ( IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  4 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 3 THEN  IF (waveletlll_glcm_idn_fc=.) OR 
  waveletlll_glcm_idn_fc < 0.94055986 THEN 0.0402032638949649 ELSE IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  1 THEN -0.0358310846458232 ELSE -0.0610713465676733 ELSE IF (waveletlll_gldm_largedependenceh=.) OR waveletlll_gldm_largedependenceh < 
  5147.7225 THEN  IF (wavelethll_firstorder_skewness_l=.) OR wavelethll_firstorder_skewness_l < 0.01921929 THEN  IF (waveletlll_glszm_graylevelvarian=.) OR 
  waveletlll_glszm_graylevelvarian < 14.23884 THEN -0.0569564457055251 ELSE -0.345930532477466 ELSE 0.051685315421393 ELSE 
  0.088562549408914 ELSE -0.000333615331521491) + ( IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  4 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 3 THEN  IF (waveletlll_glcm_idn_fc=.) OR 
  waveletlll_glcm_idn_fc < 0.94055986 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 1 THEN 
  0.0258174840646279 ELSE 0.054641431951149 ELSE IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  1 THEN -0.0395437539610775 ELSE IF (v620_fc=.) OR v620_fc < 0.43923148 THEN -0.355046106233073 ELSE -0.00607231986392785 ELSE IF 
  (wavelethll_glszm_graylevelnonuni=.) OR wavelethll_glszm_graylevelnonuni < 669.49855 THEN -0.115364889234314 ELSE 0.0329935007304613 ELSE 
  0.000808048749198896) + ( IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 4 THEN  IF (wavelethhh_glcm_clustershade_mm=.) OR 
  wavelethhh_glcm_clustershade_mm < -0.00252444 THEN 0.339286953077923 ELSE IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  1 THEN -0.040572050839508 ELSE IF (wavelethhh_glszm_largeareahighgr=.) OR wavelethhh_glszm_largeareahighgr < 212000000 THEN 
   IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 3 THEN  IF (original_firstorder_minimum_fc=.) OR 
  original_firstorder_minimum_fc < 2 THEN -0.0487055856914078 ELSE -0.0871558718795382 ELSE -0.0518985269352181 ELSE IF (original_firstorder_minimum_fc=.) OR 
  original_firstorder_minimum_fc < 3 THEN 0.0693527902634377 ELSE 0.00685588460115061 ELSE 0.000926270579173566) + ( IF (original_firstorder_minimum_fc=.) OR 
  original_firstorder_minimum_fc < 4 THEN  IF (wavelethhh_glcm_clustershade_mm=.) OR wavelethhh_glcm_clustershade_mm < -0.00252444 THEN 
  0.350113629933776 ELSE IF (wavelethhh_glszm_largeareahighgr=.) OR wavelethhh_glszm_largeareahighgr < 212000000 THEN  IF (
  original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 2 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  1 THEN -0.0161375546698868 ELSE -0.0412006178164417 ELSE IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  3 THEN -0.0943388383641191 ELSE IF (waveletlhl_glszm_zoneentropy_lm=.) OR waveletlhl_glszm_zoneentropy_lm < 6.1728639 THEN 
  -0.365442744006567 ELSE -0.00215346516941605 ELSE 0.0155689428212512 ELSE 0.00121724260324515) + ( IF (original_firstorder_minimum_fc=.) OR 
  original_firstorder_minimum_fc < 4 THEN  IF (wavelethhh_glcm_clustershade_mm=.) OR wavelethhh_glcm_clustershade_mm < -0.00252444 THEN 
  0.396231567063393 ELSE IF (waveletlll_ngtdm_busyness_tc=.) OR waveletlll_ngtdm_busyness_tc < 5.7465245 THEN  IF (waveletlhl_firstorder_skewness_t=.) OR 
  waveletlhl_firstorder_skewness_t < 0.09172026 THEN -0.0254109326728975 ELSE IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  2 THEN -0.405306378517424 ELSE -0.409331002467457 ELSE IF (wavelethhl_glcm_clusterprominenc=.) OR wavelethhl_glcm_clusterprominenc < 
  1.6780684 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 2 THEN 0.0977966488288542 ELSE 
  0.140972849032671 ELSE -0.104345827530942 ELSE 0.00379975754031191) + ( IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  4 THEN  IF (wavelethlh_glszm_zoneentropy_tc=.) OR wavelethlh_glszm_zoneentropy_tc < 2.2243476 THEN 0.342605708096494 ELSE IF 
  (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 3 THEN  IF (waveletlll_glcm_idn_fc=.) OR waveletlll_glcm_idn_fc < 
  0.94055986 THEN  IF (wavelethhl_gldm_smalldependence2=.) OR wavelethhl_gldm_smalldependence2 < 0.00223482 THEN -0.0284281137290858 ELSE 
  0.367859840810748 ELSE IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 2 THEN -0.0835052468188041 ELSE 
  -0.059288668406643 ELSE IF (waveletlll_gldm_largedependenceh=.) OR waveletlll_gldm_largedependenceh < 5147.7225 THEN -0.0670442436143234 ELSE 
  0.0806536435603059 ELSE 0.00106186888836971) + ( IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  4 THEN  IF (wavelethlh_glszm_zoneentropy_tc=.) OR wavelethlh_glszm_zoneentropy_tc < 2.2243476 THEN 0.386727414004942 ELSE IF 
  (wavelethhh_glcm_clustershade_mm=.) OR wavelethhh_glcm_clustershade_mm < -0.00252444 THEN 0.37898414142888 ELSE IF (wavelethlh_firstorder_median_lm=.) OR 
  wavelethlh_firstorder_median_lm < -0.02569448 THEN  IF (waveletlhh_firstorder_median_lm=.) OR waveletlhh_firstorder_median_lm < 
  0.10067047 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 2 THEN -0.392149556159657 ELSE IF 
  (wavelethlh_glszm_zoneentropy_tc=.) OR wavelethlh_glszm_zoneentropy_tc < 2.4464549 THEN -0.0368741695283868 ELSE -0.390319664715837 ELSE 
  0.0263036917564484 ELSE 0.00799495455049792 ELSE 0.00455637374469911) + ( IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  4 THEN  IF (waveletlhh_glszm_smallareaemphas=.) OR waveletlhh_glszm_smallareaemphas < 0.58605831 THEN  IF (wavelethhl_glcm_imc1_mm=.) OR 
  wavelethhl_glcm_imc1_mm < -0.01377353 THEN  IF (wavelethll_firstorder_skewness_l=.) OR wavelethll_firstorder_skewness_l < 
  -0.04394169 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 1 THEN -0.0249516228861171 ELSE IF 
  (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 3 THEN -0.0804421792106874 ELSE -0.0734068336338752 ELSE IF 
  (wavelethhl_glszm_graylevelvarian=.) OR wavelethhl_glszm_graylevelvarian < 2.2327002 THEN -0.0164180438589304 ELSE 0.361910602956096 ELSE 
  0.121516968556416 ELSE -0.135921528412001 ELSE 0.00113690459141672) + ( IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  4 THEN  IF (waveletllh_glszm_zoneentropy_fc=.) OR waveletllh_glszm_zoneentropy_fc < 5.9556771 THEN  IF (waveletllh_glszm_zoneentropy_fc=.) OR 
  waveletllh_glszm_zoneentropy_fc < 5.8965978 THEN  IF (wavelethlh_glszm_zoneentropy_tc=.) OR wavelethlh_glszm_zoneentropy_tc < 
  2.2447631 THEN 0.366577452904818 ELSE -0.0547750902685077 ELSE IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  3 THEN 0.0956239751766423 ELSE 0.38426359801579 ELSE IF (waveletlll_glcm_idn_fc=.) OR waveletlll_glcm_idn_fc < 0.93701498 THEN 
  0.025440302076873 ELSE IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 2 THEN -0.381052717817269 ELSE 
  -0.381600875896046 ELSE 0.00113278227922651) + ( IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  4 THEN  IF (waveletlll_glszm_graylevelnonuni=.) OR waveletlll_glszm_graylevelnonuni < 1514.1617 THEN  IF (original_firstorder_minimum_fc=.) OR 
  original_firstorder_minimum_fc < 2 THEN  IF (waveletlll_glcm_idn_fc=.) OR waveletlll_glcm_idn_fc < 0.93701498 THEN 0.359705431596781 ELSE 
  -0.0791018581503612 ELSE IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 3 THEN -0.0507436373274411 ELSE IF 
  (wavelethhl_glszm_largearealowgra=.) OR wavelethhl_glszm_largearealowgra < 354283.87 THEN 0.0151643445284309 ELSE -0.137778050401584 ELSE IF 
  (wavelethhh_glcm_clustershade_mm=.) OR wavelethhh_glcm_clustershade_mm < -0.00220238 THEN -0.021552322089803 ELSE 0.368308702824193 ELSE 
  0.0013032576052034) + ( IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 4 THEN  IF (waveletlll_glszm_graylevelnonuni=.) OR 
  waveletlll_glszm_graylevelnonuni < 1514.1617 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  2 THEN  IF (waveletlll_glcm_idn_fc=.) OR waveletlll_glcm_idn_fc < 0.93701498 THEN 0.372529366943398 ELSE -0.0846914970444662 ELSE IF 
  (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 3 THEN -0.054329350034646 ELSE IF (wavelethll_glszm_graylevelnonuni=.) OR 
  wavelethll_glszm_graylevelnonuni < 669.49855 THEN -0.134649103430136 ELSE 0.0204035280543226 ELSE IF (original_firstorder_minimum_fc=.) OR 
  original_firstorder_minimum_fc < 2 THEN 0.0359045138975655 ELSE 0.0923292740726912 ELSE 0.00139535075505199) + ( IF (original_firstorder_minimum_fc=.) OR 
  original_firstorder_minimum_fc < 4 THEN  IF (waveletlll_glszm_graylevelnonuni=.) OR waveletlll_glszm_graylevelnonuni < 1514.1617 THEN 
   IF (wavelethhh_glcm_clustershade_mm=.) OR wavelethhh_glcm_clustershade_mm < -0.00224646 THEN 0.369569719549414 ELSE IF (
  original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 2 THEN -0.0176836465797193 ELSE IF (original_firstorder_minimum_fc=.) OR 
  original_firstorder_minimum_fc < 3 THEN -0.0693187233979398 ELSE IF (wavelethll_glszm_graylevelnonuni=.) OR wavelethll_glszm_graylevelnonuni < 
  681.5964 THEN  IF (wavelethhl_firstorder_mean_mm=.) OR wavelethhl_firstorder_mean_mm < 0.14152586 THEN -0.372326928506542 ELSE 
  -0.394165141278208 ELSE 0.0195123795734713 ELSE 0.0779441460651871 ELSE 0.00395867291266232) + ( IF (original_firstorder_minimum_fc=.) OR 
  original_firstorder_minimum_fc < 5 THEN  IF (waveletlll_glcm_idn_fc=.) OR waveletlll_glcm_idn_fc < 0.9367715 THEN  IF (original_firstorder_minimum_fc=.) OR 
  original_firstorder_minimum_fc < 4 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 2 THEN 
  0.110580959395533 ELSE 0.00750922413614463 ELSE 0.387744894258728 ELSE IF (v620_fc=.) OR v620_fc < 0.45088551 THEN  IF (waveletllh_glcm_imc1_mm=.) OR 
  waveletllh_glcm_imc1_mm < -0.06133003 THEN -0.389716385272175 ELSE 0.0188845938245051 ELSE IF (original_firstorder_minimum_fc=.) OR 
  original_firstorder_minimum_fc < 4 THEN -0.0619834937876051 ELSE -0.391226159988768 ELSE 0.00132395894120613) + ( IF (original_firstorder_minimum_fc=.) OR 
  original_firstorder_minimum_fc < 7 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 4 THEN 
  -0.00436354385597901 ELSE IF (wavelethll_ngtdm_busyness_mm=.) OR wavelethll_ngtdm_busyness_mm < 125.45954 THEN  IF (wavelethll_glszm_graylevelnonuni=.) OR 
  wavelethll_glszm_graylevelnonuni < 463.7754 THEN  IF (wavelethhh_glszm_largeareahighgr=.) OR wavelethhh_glszm_largeareahighgr < 
  223000000 THEN 0.348961728762865 ELSE 0.362271086062879 ELSE -0.00529181267407377 ELSE IF (original_firstorder_minimum_fc=.) OR 
  original_firstorder_minimum_fc < 6 THEN  IF (wavelethll_firstorder_kurtosis_m=.) OR wavelethll_firstorder_kurtosis_m < 3.7893964 THEN 
  -0.0768344414204932 ELSE -0.368122073679478 ELSE -0.0249844678702442 ELSE 0.00111964040441889) + ( IF (original_firstorder_minimum_fc=.) OR 
  original_firstorder_minimum_fc < 7 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 5 THEN 
  -0.0046234424421962 ELSE IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 6 THEN  IF (v455_fc=.) OR 
  v455_fc < 0.06184083 THEN  IF (v810_mm=.) OR v810_mm < 0.32643467 THEN  IF (wavelethhh_glszm_largeareahighgr=.) OR wavelethhh_glszm_largeareahighgr < 
  307000000 THEN  IF (waveletlll_glcm_idn_fc=.) OR waveletlll_glcm_idn_fc < 0.93783357 THEN -0.00110953502531675 ELSE -0.359004840277107 ELSE 
  0.0791429824810432 ELSE 0.352981145111377 ELSE -0.0930810316396576 ELSE -0.0107945561875747 ELSE 0.000795828410329375) + 
  ( IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 7 THEN  IF (original_firstorder_minimum_fc=.) OR 
  original_firstorder_minimum_fc < 5 THEN -0.00444758395948759 ELSE IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  6 THEN  IF (waveletllh_glszm_zoneentropy_fc=.) OR waveletllh_glszm_zoneentropy_fc < 5.9368043 THEN  IF (waveletlhl_firstorder_skewness_t=.) OR 
  waveletlhl_firstorder_skewness_t < 0.10864944 THEN  IF (waveletllh_glszm_zoneentropy_fc=.) OR waveletllh_glszm_zoneentropy_fc < 
  5.892428 THEN -0.0888944450101131 ELSE 0.0725737809905672 ELSE 0.372041449447199 ELSE IF (waveletlhl_glszm_zoneentropy_lm=.) OR 
  waveletlhl_glszm_zoneentropy_lm < 6.1083433 THEN -0.138479100696367 ELSE 0.0337004048161903 ELSE -0.0100417306647315 ELSE 
  0.00104574700920133) + ( IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 7 THEN  IF (original_firstorder_minimum_fc=.) OR 
  original_firstorder_minimum_fc < 5 THEN -0.004318295230628 ELSE IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  6 THEN  IF (waveletllh_glszm_zoneentropy_fc=.) OR waveletllh_glszm_zoneentropy_fc < 5.9368043 THEN  IF (wavelethlh_firstorder_median_lm=.) OR 
  wavelethlh_firstorder_median_lm < 0.00198915 THEN  IF (wavelethhl_glcm_imc1_tc=.) OR wavelethhl_glcm_imc1_tc < -0.02008733 THEN 
  0.351797731708377 ELSE 0.0138072209608657 ELSE -0.0283277925173592 ELSE IF (wavelethlh_firstorder_median_lm=.) OR wavelethlh_firstorder_median_lm < 
  -0.10635683 THEN 0.0308701603427845 ELSE -0.113795317811774 ELSE -0.0100821154170145 ELSE 0.000743306063950427) + ( IF (original_firstorder_minimum_fc=.) OR 
  original_firstorder_minimum_fc < 7 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 5 THEN 
  -0.00415404340876946 ELSE IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 6 THEN  IF (waveletlhl_firstorder_skewness_f=.) OR 
  waveletlhl_firstorder_skewness_f < -0.28766931 THEN  IF (wavelethhl_glcm_correlation_mm=.) OR wavelethhl_glcm_correlation_mm < 
  0.00633414 THEN  IF (wavelethhl_glcm_clusterprominenc=.) OR wavelethhl_glcm_clusterprominenc < 1.4728768 THEN -0.37392046536903 ELSE 
  -0.0305726298099042 ELSE 0.0693926514794726 ELSE IF (waveletllh_glcm_correlation_mm=.) OR waveletllh_glcm_correlation_mm < 
  0.10711999 THEN 0.362817171215576 ELSE -0.0549843890436142 ELSE -0.00937897648218364 ELSE 0.000976730561233539) + ( IF (original_firstorder_minimum_fc=.) OR 
  original_firstorder_minimum_fc < 7 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 5 THEN 
  -0.00403328773623199 ELSE IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 6 THEN  IF (wavelethll_glszm_graylevelnonuni=.) OR 
  wavelethll_glszm_graylevelnonuni < 487.79011 THEN 0.337323844690631 ELSE IF (wavelethlh_glszm_zoneentropy_tc=.) OR wavelethlh_glszm_zoneentropy_tc < 
  2.2833136 THEN 0.0697716013680073 ELSE IF (waveletlll_glcm_clustershade_lm=.) OR waveletlll_glcm_clustershade_lm < 264.03725 THEN 
   IF (wavelethhl_glcm_imc1_mm=.) OR wavelethhl_glcm_imc1_mm < -0.01520764 THEN -0.35893626578106 ELSE -0.0978543871182876 ELSE 
  0.0119565661722499 ELSE -0.00941669574545614 ELSE 0.000694250016592664) + ( IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  7 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 5 THEN -0.00387987653549037 ELSE IF (original_firstorder_minimum_fc=.) OR 
  original_firstorder_minimum_fc < 6 THEN -0.00884158580951782 ELSE IF (waveletlll_glcm_idn_fc=.) OR waveletlll_glcm_idn_fc < 
  0.93500335 THEN -0.0872188289698964 ELSE IF (waveletllh_glcm_correlation_mm=.) OR waveletllh_glcm_correlation_mm < 0.07710429 THEN 
  0.356958599957856 ELSE IF (waveletllh_glcm_imc1_mm=.) OR waveletllh_glcm_imc1_mm < -0.05795894 THEN  IF (wavelethhl_glszm_graylevelvarian=.) OR 
  wavelethhl_glszm_graylevelvarian < 2.2222222 THEN -0.0361585191617679 ELSE 0.360882580587463 ELSE -0.125021604182829 ELSE 
  0.000912269117963904) + ( IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 7 THEN  IF (original_firstorder_minimum_fc=.) OR 
  original_firstorder_minimum_fc < 5 THEN -0.00376709073756183 ELSE IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  6 THEN  IF (waveletllh_gldm_smalldependencel=.) OR waveletllh_gldm_smalldependencel < 0.00089584 THEN 0.0545370823377459 ELSE IF 
  (waveletlhl_firstorder_skewness_f=.) OR waveletlhl_firstorder_skewness_f < -0.28766931 THEN  IF (v455_fc=.) OR v455_fc < 
  0.05989707 THEN -0.0228910618775116 ELSE -0.355237554057356 ELSE 0.0431431821981537 ELSE IF (wavelethhh_glcm_imc1_lm=.) OR 
  wavelethhh_glcm_imc1_lm < -0.01076942 THEN 0.0795830944842617 ELSE -0.02293403524955 ELSE 0.000648431491475099) + ( IF (original_firstorder_minimum_fc=.) OR 
  original_firstorder_minimum_fc < 7 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 6 THEN 
  -0.004910473994728 ELSE IF (original_glszm_smallareaemphasis=.) OR original_glszm_smallareaemphasis < 0.58890522 THEN  IF 
  (wavelethhl_glszm_graylevelvarian=.) OR wavelethhl_glszm_graylevelvarian < 2.1845007 THEN -0.042612991342372 ELSE IF (wavelethhl_gldm_smalldependence2=.) OR 
  wavelethhl_gldm_smalldependence2 < 0.00270206 THEN 0.357655074032125 ELSE 0.381027850541119 ELSE IF (wavelethhh_glcm_clustershade_mm=.) OR 
  wavelethhh_glcm_clustershade_mm < 0.0007936 THEN  IF (wavelethlh_glszm_zoneentropy_tc=.) OR wavelethlh_glszm_zoneentropy_tc < 
  2.4741431 THEN -0.096890453515154 ELSE -0.399292449895993 ELSE -0.00132396304888905 ELSE 0.00201046775672907) + ( IF (original_firstorder_minimum_fc=.) OR 
  original_firstorder_minimum_fc < 7 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 6 THEN 
  -0.00458638271259324 ELSE IF (waveletllh_glcm_correlation_mm=.) OR waveletllh_glcm_correlation_mm < 0.07710429 THEN  IF (
  waveletllh_gldm_smalldependencel=.) OR waveletllh_gldm_smalldependencel < 0.00109494 THEN 0.0142262083156491 ELSE 0.374886135739677 ELSE IF 
  (waveletllh_glcm_imc1_mm=.) OR waveletllh_glcm_imc1_mm < -0.05519788 THEN  IF (waveletllh_gldm_smalldependencel=.) OR waveletllh_gldm_smalldependencel < 
  0.00087116 THEN 0.367006483759625 ELSE IF (wavelethhh_firstorder_minimum_fc=.) OR wavelethhh_firstorder_minimum_fc < -46.573909 THEN 
  -0.125373783098873 ELSE 0.0271086216858124 ELSE -0.385018971139406 ELSE 0.00187777025844561) + ( IF (original_firstorder_minimum_fc=.) OR 
  original_firstorder_minimum_fc < 7 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 6 THEN 
  -0.00428368145479652 ELSE IF (waveletllh_glcm_correlation_mm=.) OR waveletllh_glcm_correlation_mm < 0.07710429 THEN 0.0623706023216114 ELSE IF 
  (waveletlhl_firstorder_skewness_t=.) OR waveletlhl_firstorder_skewness_t < -0.02618568 THEN 0.0627791544678062 ELSE IF (waveletllh_gldm_smalldependencel=.) OR 
  waveletllh_gldm_smalldependencel < 0.00087017 THEN 0.0206174945369518 ELSE IF (wavelethlh_glszm_zoneentropy_tc=.) OR wavelethlh_glszm_zoneentropy_tc < 
  2.6840752 THEN  IF (waveletllh_glszm_zoneentropy_fc=.) OR waveletllh_glszm_zoneentropy_fc < 5.8690282 THEN -0.390052837933545 ELSE 
  -0.368409190141584 ELSE -0.0425724115900917 ELSE 0.00175383382349281) + ( IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  7 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 6 THEN  IF (wavelethhh_glszm_largeareahighgr=.) OR 
  wavelethhh_glszm_largeareahighgr < 86900000 THEN 0.35189934984938 ELSE -0.0120667777331853 ELSE IF (waveletlhl_firstorder_skewness_t=.) OR 
  waveletlhl_firstorder_skewness_t < 0.05050573 THEN  IF (wavelethlh_glszm_zoneentropy_tc=.) OR wavelethlh_glszm_zoneentropy_tc < 
  2.4058996 THEN 0.351513036394131 ELSE IF (wavelethhl_firstorder_mean_mm=.) OR wavelethhl_firstorder_mean_mm < 0.14821092 THEN 
  -0.370482680979245 ELSE 0.0630950803023423 ELSE IF (wavelethhl_glrlm_longrunhighgray=.) OR wavelethhl_glrlm_longrunhighgray < 
  31.211591 THEN 0.0068370775804231 ELSE -0.360667620333209 ELSE 0.000852062005574232) + ( IF (original_firstorder_minimum_fc=.) OR 
  original_firstorder_minimum_fc < 7 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 6 THEN 
   IF (wavelethhh_glszm_largeareahighgr=.) OR wavelethhh_glszm_largeareahighgr < 86900000 THEN 0.366473361077122 ELSE IF (waveletlll_glcm_idn_fc=.) OR 
  waveletlll_glcm_idn_fc < 0.93538861 THEN 0.0393780373146216 ELSE IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  4 THEN -0.0166723436953433 ELSE IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 5 THEN -0.0473287649439749 ELSE IF 
  (wavelethhh_glcm_imc1_lm=.) OR wavelethhh_glcm_imc1_lm < -0.01025316 THEN 0.0771858798242543 ELSE -0.0759181675767684 ELSE 
  -0.00977532576499833 ELSE 0.00119875546777295) + ( IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  7 THEN  IF (wavelethlh_firstorder_median_lm=.) OR wavelethlh_firstorder_median_lm < -0.10635683 THEN  IF (waveletlll_glszm_graylevelnonuni=.) OR 
  waveletlll_glszm_graylevelnonuni < 1383.3636 THEN  IF (wavelethll_firstorder_kurtosis_m=.) OR wavelethll_firstorder_kurtosis_m < 
  5.3898469 THEN  IF (wavelethll_glszm_smallareaemphas=.) OR wavelethll_glszm_smallareaemphas < 0.55680004 THEN 0.0118554612499822 ELSE 
  -0.123175800315009 ELSE 0.0708594117673108 ELSE IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  4 THEN 0.0323613045706015 ELSE IF (waveletlll_gldm_largedependenceh=.) OR waveletlll_gldm_largedependenceh < 4404.278 THEN 
  0.362476028639924 ELSE 0.382535220771413 ELSE -0.0195714023115165 ELSE 0.00215254649609699) + ( IF (original_firstorder_minimum_fc=.) OR 
  original_firstorder_minimum_fc < 7 THEN  IF (wavelethlh_glszm_zoneentropy_tc=.) OR wavelethlh_glszm_zoneentropy_tc < 2.2095115 THEN 
   IF (wavelethhl_glszm_graylevelvarian=.) OR wavelethhl_glszm_graylevelvarian < 2.2277624 THEN  IF (original_firstorder_minimum_fc=.) OR 
  original_firstorder_minimum_fc < 5 THEN 0.31965933335173 ELSE 0.385173820288345 ELSE -0.0182599366174966 ELSE IF (waveletlll_glcm_clustershade_lm=.) OR 
  waveletlll_glcm_clustershade_lm < 250.70949 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  4 THEN -0.00963342813009514 ELSE IF (wavelethll_glszm_graylevelnonuni=.) OR wavelethll_glszm_graylevelnonuni < 463.7754 THEN 
  0.0889851983085045 ELSE -0.0583002093891683 ELSE 0.0225337157092087 ELSE 0.0012834613165243) + ( IF (original_firstorder_minimum_fc=.) OR 
  original_firstorder_minimum_fc < 7 THEN  IF (wavelethll_firstorder_kurtosis_m=.) OR wavelethll_firstorder_kurtosis_m < 6.1610522 THEN 
   IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 4 THEN -0.00444485727444046 ELSE IF (original_firstorder_minimum_fc=.) OR 
  original_firstorder_minimum_fc < 6 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 5 THEN 
  -0.0254978824762386 ELSE -0.015604332332607 ELSE -0.00679270418463944 ELSE IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  6 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 4 THEN 0.0183067636189264 ELSE 0.362738249197836 ELSE 
  -0.0267678710792418 ELSE 0.00137415319888347) + ( IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  7 THEN  IF (wavelethll_firstorder_kurtosis_m=.) OR wavelethll_firstorder_kurtosis_m < 6.1610522 THEN  IF (wavelethhl_gldm_smalldependence2=.) OR 
  wavelethhl_gldm_smalldependence2 < 0.00132218 THEN -0.172686352558132 ELSE IF (wavelethhl_glrlm_longrunhighgray=.) OR wavelethhl_glrlm_longrunhighgray < 
  58.037958 THEN -0.0200320381697381 ELSE IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 4 THEN 
  0.00841458837689286 ELSE 0.135971946247749 ELSE IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  6 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 4 THEN 0.0170257575768033 ELSE 0.379586114681591 ELSE 
  -0.0299422730115252 ELSE 0.00246755221780915) + ( IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  7 THEN  IF (waveletlhl_firstorder_skewness_f=.) OR waveletlhl_firstorder_skewness_f < -0.21443151 THEN  IF (wavelethll_glszm_graylevelnonuni=.) OR 
  wavelethll_glszm_graylevelnonuni < 463.7754 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  4 THEN -0.0365801180307361 ELSE IF (waveletlhl_glszm_zoneentropy_lm=.) OR waveletlhl_glszm_zoneentropy_lm < 5.8310909 THEN 
  0.378841276258803 ELSE 0.0503777996940636 ELSE -0.0222411588735552 ELSE IF (wavelethhl_glcm_imc1_tc=.) OR wavelethhl_glcm_imc1_tc < 
  -0.02291279 THEN -0.00675623097403493 ELSE IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 5 THEN 
  0.353803411477989 ELSE 0.381536523171361 ELSE 0.00230467077734787) + ( IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  7 THEN  IF (waveletlll_glcm_clustershade_lm=.) OR waveletlll_glcm_clustershade_lm < 250.70949 THEN -0.0205857150847632 ELSE IF 
  (wavelethll_firstorder_skewness_l=.) OR wavelethll_firstorder_skewness_l < -0.26617536 THEN -0.378401770155993 ELSE IF (wavelethhh_firstorder_minimum_fc=.) OR 
  wavelethhh_firstorder_minimum_fc < -69.553667 THEN -0.0873282888511315 ELSE IF (waveletlhl_firstorder_skewness_t=.) OR waveletlhl_firstorder_skewness_t < 
  0.19942181 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 4 THEN 0.0295834810153743 ELSE IF 
  (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 6 THEN 0.156622927445753 ELSE 0.381290529629731 ELSE 
  -0.0312890951534158 ELSE 0.00264195318880689) + ( IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  7 THEN  IF (waveletlll_glcm_clustershade_lm=.) OR waveletlll_glcm_clustershade_lm < 371.51804 THEN  IF (wavelethll_glszm_graylevelnonuni=.) OR 
  wavelethll_glszm_graylevelnonuni < 487.79011 THEN 0.0432469465851073 ELSE IF (waveletlhh_firstorder_median_lm=.) OR waveletlhh_firstorder_median_lm < 
  0.00115063 THEN 0.0000779911189901935 ELSE IF (wavelethlh_glszm_zoneentropy_tc=.) OR wavelethlh_glszm_zoneentropy_tc < 2.1626565 THEN 
  0.362901510404681 ELSE -0.123660120068413 ELSE IF (wavelethhl_gldm_smalldependencel=.) OR wavelethhl_gldm_smalldependencel < 
  0.00230001 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 4 THEN 0.0201817693216387 ELSE 
  0.391875771159531 ELSE -0.0333723194981099 ELSE 0.00282859769278797) + ( IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  10 THEN  IF (wavelethhl_gldm_smalldependence2=.) OR wavelethhl_gldm_smalldependence2 < 0.00122772 THEN -0.149537617568663 ELSE IF 
  (waveletlhl_firstorder_skewness_t=.) OR waveletlhl_firstorder_skewness_t < 0.19317896 THEN 0.0148490427872825 ELSE IF (wavelethhh_firstorder_minimum_fc=.) OR 
  wavelethhh_firstorder_minimum_fc < -62.035808 THEN 0.0699361452772862 ELSE IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  5 THEN -0.0033105687065037 ELSE IF (waveletllh_glcm_correlation_mm=.) OR waveletllh_glcm_correlation_mm < 0.07893957 THEN 
  -0.0223342600706362 ELSE IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 8 THEN -0.401552505116147 ELSE 
  -0.406204886032822 ELSE -0.00414051826465233) + ( IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  10 THEN  IF (waveletlhl_firstorder_skewness_t=.) OR waveletlhl_firstorder_skewness_t < 0.06597582 THEN  IF (wavelethll_firstorder_kurtosis_m=.) OR 
  wavelethll_firstorder_kurtosis_m < 3.9994079 THEN -0.0551636663510151 ELSE IF (original_glszm_smallareaemphasis=.) OR original_glszm_smallareaemphasis < 
  0.57143788 THEN -0.0864492320137986 ELSE IF (waveletlll_glszm_graylevelnonuni=.) OR waveletlll_glszm_graylevelnonuni < 1289.5176 THEN 
  0.0118653706364601 ELSE IF (waveletllh_glcm_imc1_mm=.) OR waveletllh_glcm_imc1_mm < -0.048472 THEN  IF (waveletlhl_glszm_zoneentropy_lm=.) OR 
  waveletlhl_glszm_zoneentropy_lm < 5.875191 THEN 0.060938568757926 ELSE 0.401450992017503 ELSE 0.0115331157511162 ELSE -0.01872566037601 ELSE 
  -0.00174315226426074) + ( IF (v455_fc=.) OR v455_fc < 0.05992914 THEN  IF (waveletlhl_firstorder_skewness_t=.) OR waveletlhl_firstorder_skewness_t < 
  0.12697069 THEN  IF (wavelethhl_glcm_imc1_tc=.) OR wavelethhl_glcm_imc1_tc < -0.03223608 THEN -0.0700559992227761 ELSE IF 
  (wavelethhh_glszm_largeareahighgr=.) OR wavelethhh_glszm_largeareahighgr < 281000000 THEN  IF (wavelethhh_glcm_clustershade_mm=.) OR 
  wavelethhh_glcm_clustershade_mm < -0.00040356 THEN 0.0468186903500811 ELSE IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  8 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 5 THEN 0.387189347918301 ELSE 0.39514722424888 ELSE 
  0.139844352866022 ELSE 0.0240270337907944 ELSE -0.0241042675312454 ELSE -0.010882446108258) + ( IF (v455_fc=.) OR v455_fc < 
  0.05992914 THEN  IF (waveletlhl_firstorder_skewness_t=.) OR waveletlhl_firstorder_skewness_t < 0.12697069 THEN  IF (wavelethlh_glszm_largeareahighgr=.) OR 
  wavelethlh_glszm_largeareahighgr < 8459596.3 THEN -0.0403474400721442 ELSE IF (waveletlll_glszm_graylevelnonuni=.) OR waveletlll_glszm_graylevelnonuni < 
  1656.6571 THEN  IF (wavelethhl_glrlm_longrunhighgray=.) OR wavelethhl_glrlm_longrunhighgray < 31.870173 THEN 0.0478768841414003 ELSE IF 
  (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 5 THEN 0.082861407824257 ELSE IF (original_firstorder_minimum_fc=.) OR 
  original_firstorder_minimum_fc < 11 THEN 0.388723412359343 ELSE 0.380121127304207 ELSE -0.066651263658226 ELSE -0.0194721972795475 ELSE 
  -0.0112932724281365) + ( IF (wavelethhl_firstorder_mean_mm=.) OR wavelethhl_firstorder_mean_mm < 0.10638043 THEN  IF (wavelethlh_glszm_largeareahighgr=.) OR 
  wavelethlh_glszm_largeareahighgr < 21236381 THEN  IF (wavelethlh_glszm_zoneentropy_tc=.) OR wavelethlh_glszm_zoneentropy_tc < 
  2.1933818 THEN 0.0626044715308383 ELSE IF (waveletlll_glszm_graylevelvarian=.) OR waveletlll_glszm_graylevelvarian < 21.86257 THEN 
   IF (wavelethhl_glszm_smallareaemphas=.) OR wavelethhl_glszm_smallareaemphas < 0.70129139 THEN 0.0303213694579073 ELSE IF 
  (waveletlll_glszm_graylevelvarian=.) OR waveletlll_glszm_graylevelvarian < 17.711761 THEN -0.0474287028793679 ELSE IF (wavelethhh_glcm_clustershade_mm=.) OR 
  wavelethhh_glcm_clustershade_mm < -0.0029384 THEN 0.00425609580592935 ELSE -0.209891227956787 ELSE 0.0216956517037711 ELSE 
  0.0971075729675909 ELSE 0.0177958625201065) + ( IF (wavelethhl_firstorder_mean_mm=.) OR wavelethhl_firstorder_mean_mm < 0.10638043 THEN 
   IF (wavelethlh_glszm_largeareahighgr=.) OR wavelethlh_glszm_largeareahighgr < 21236381 THEN  IF (wavelethlh_glszm_zoneentropy_tc=.) OR 
  wavelethlh_glszm_zoneentropy_tc < 2.3039227 THEN 0.0172043835321714 ELSE IF (waveletllh_glszm_zoneentropy_fc=.) OR waveletllh_glszm_zoneentropy_fc < 
  5.737238 THEN 0.0635007948242852 ELSE IF (waveletlll_glszm_graylevelvarian=.) OR waveletlll_glszm_graylevelvarian < 21.86257 THEN 
   IF (waveletlll_glcm_idn_fc=.) OR waveletlll_glcm_idn_fc < 0.93783357 THEN -0.0449732100575585 ELSE IF (waveletlhh_firstorder_maximum_mm=.) OR 
  waveletlhh_firstorder_maximum_mm < 107.88982 THEN -0.246830231981818 ELSE -0.0205751752384733 ELSE 0.0141716545885347 ELSE 
  0.0787534952626093 ELSE 0.0160274596292431) + ( IF (wavelethll_firstorder_kurtosis_m=.) OR wavelethll_firstorder_kurtosis_m < 
  3.9623783 THEN  IF (waveletlhh_glszm_smallareaemphas=.) OR waveletlhh_glszm_smallareaemphas < 0.54556678 THEN  IF (waveletlhl_firstorder_skewness_t=.) OR 
  waveletlhl_firstorder_skewness_t < 0.23995338 THEN  IF (waveletlhh_firstorder_maximum_mm=.) OR waveletlhh_firstorder_maximum_mm < 
  117.067 THEN  IF (wavelethll_ngtdm_busyness_mm=.) OR wavelethll_ngtdm_busyness_mm < 108.36131 THEN -0.0376701372021613 ELSE IF 
  (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 9 THEN -0.398552876745807 ELSE IF (original_firstorder_minimum_fc=.) OR 
  original_firstorder_minimum_fc < 14 THEN -0.387371597983264 ELSE -0.369665545575321 ELSE 0.0143292050648489 ELSE 0.0553333916048027 ELSE 
  0.00238566946485321 ELSE 0.0101503283430233) + ( IF (wavelethll_firstorder_kurtosis_m=.) OR wavelethll_firstorder_kurtosis_m < 
  3.9623783 THEN  IF (waveletlhl_firstorder_skewness_f=.) OR waveletlhl_firstorder_skewness_f < -0.2929288 THEN  IF (v620_fc=.) OR 
  v620_fc < 0.4569847 THEN  IF (waveletlhl_glcm_clustershade_fc=.) OR waveletlhl_glcm_clustershade_fc < -3.479976 THEN -0.407016647408859 ELSE 
  0.0459847209646096 ELSE IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 12 THEN  IF (original_firstorder_minimum_fc=.) OR 
  original_firstorder_minimum_fc < 8 THEN -0.40677839059983 ELSE IF (wavelethhl_glszm_largearealowgra=.) OR wavelethhl_glszm_largearealowgra < 
  561284.2 THEN -0.406066342269157 ELSE -0.406066342269157 ELSE -0.157986136531206 ELSE -0.00297965055349266 ELSE 0.0104143640998677) + 
  ( IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 7 THEN -0.0056467531872923 ELSE IF (original_firstorder_minimum_fc=.) OR 
  original_firstorder_minimum_fc < 10 THEN  IF (wavelethll_ngtdm_busyness_mm=.) OR wavelethll_ngtdm_busyness_mm < 72.325623 THEN 
   IF (waveletllh_glszm_zoneentropy_fc=.) OR waveletllh_glszm_zoneentropy_fc < 6.0614097 THEN  IF (wavelethll_firstorder_skewness_l=.) OR 
  wavelethll_firstorder_skewness_l < -0.02480231 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  8 THEN -0.14071456454832 ELSE IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 9 THEN -0.390953913079503 ELSE 
  -0.394455026629942 ELSE -0.00304562698921998 ELSE 0.065487199805249 ELSE 0.0332002137796081 ELSE -0.00265938694739516) + 
  ( IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 7 THEN -0.0052740674786423 ELSE IF (original_firstorder_minimum_fc=.) OR 
  original_firstorder_minimum_fc < 10 THEN  IF (wavelethll_ngtdm_busyness_mm=.) OR wavelethll_ngtdm_busyness_mm < 72.325623 THEN 
  -0.0325603015627441 ELSE IF (wavelethll_firstorder_kurtosis_m=.) OR wavelethll_firstorder_kurtosis_m < 4.012242 THEN -0.0308598098133657 ELSE IF 
  (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 9 THEN  IF (waveletllh_gldm_smalldependencel=.) OR 
  waveletllh_gldm_smalldependencel < 0.00094285 THEN -0.0403563101651149 ELSE IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  8 THEN 0.0961172095391108 ELSE 0.077877787709116 ELSE 0.383421504259383 ELSE -0.00248386740805196) + ( IF (original_firstorder_minimum_fc=.) OR 
  original_firstorder_minimum_fc < 7 THEN -0.00473991543675911 ELSE IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  10 THEN  IF (wavelethhh_glcm_clustershade_mm=.) OR wavelethhh_glcm_clustershade_mm < 0.00327324 THEN  IF (wavelethlh_firstorder_median_lm=.) OR 
  wavelethlh_firstorder_median_lm < 0.06185361 THEN  IF (waveletlhl_glszm_zoneentropy_mm=.) OR waveletlhl_glszm_zoneentropy_mm < 
  5.7973288 THEN -0.0223287272459047 ELSE IF (wavelethll_ngtdm_busyness_mm=.) OR wavelethll_ngtdm_busyness_mm < 91.065388 THEN 
  0.0132250714660753 ELSE 0.119850884087631 ELSE -0.385999252603252 ELSE IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  9 THEN -0.397281267029226 ELSE -0.0419794252821339 ELSE -0.00335273209270874) + ( IF (original_firstorder_minimum_fc=.) OR 
  original_firstorder_minimum_fc < 7 THEN -0.00454204457436474 ELSE IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  10 THEN  IF (waveletlhl_firstorder_skewness_t=.) OR waveletlhl_firstorder_skewness_t < 0.18775779 THEN  IF (wavelethhl_glcm_correlation_mm=.) OR 
  wavelethhl_glcm_correlation_mm < 0.00887596 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  9 THEN 0.0393485752508326 ELSE 0.0279271394965813 ELSE -0.0336136886421491 ELSE IF (wavelethll_firstorder_skewness_l=.) OR 
  wavelethll_firstorder_skewness_l < -0.08769953 THEN 0.0171048822335681 ELSE IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  9 THEN -0.378615010359132 ELSE -0.0862593818961588 ELSE -0.000570575960161281) + ( IF (original_firstorder_minimum_fc=.) OR 
  original_firstorder_minimum_fc < 7 THEN -0.00424226962852257 ELSE IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  10 THEN  IF (wavelethll_ngtdm_busyness_mm=.) OR wavelethll_ngtdm_busyness_mm < 72.325623 THEN  IF (waveletlhl_firstorder_skewness_t=.) OR 
  waveletlhl_firstorder_skewness_t < 0.06597582 THEN 0.0223797499658741 ELSE IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  8 THEN -0.059781753916247 ELSE IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 9 THEN -0.366545653411227 ELSE 
  -0.130418585464081 ELSE IF (wavelethll_firstorder_kurtosis_m=.) OR wavelethll_firstorder_kurtosis_m < 3.7961072 THEN -0.0478340985658017 ELSE 
  0.0450625049072445 ELSE -0.000532821897817764) + ( IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  7 THEN -0.00396227982959734 ELSE IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 10 THEN  IF (original_shape_sphericity_mm=.) OR 
  original_shape_sphericity_mm < 0.44400215 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  9 THEN  IF (wavelethhh_glcm_imc1_lm=.) OR wavelethhh_glcm_imc1_lm < -0.00918178 THEN  IF (waveletlhl_glcm_clustershade_fc=.) OR 
  waveletlhl_glcm_clustershade_fc < -2.0052297 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  8 THEN 0.113420359130371 ELSE 0.0792804260554177 ELSE -0.0939843624496773 ELSE -0.0166316742099841 ELSE 0.00947438060862388 ELSE 
  -0.126484111366805 ELSE -0.000497667925641162) + ( IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  7 THEN -0.00370076935783854 ELSE IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 10 THEN  IF (waveletlhh_glszm_smallareaemphas=.) OR 
  waveletlhh_glszm_smallareaemphas < 0.53297203 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  9 THEN  IF (waveletlhl_glcm_clustershade_fc=.) OR waveletlhl_glcm_clustershade_fc < -2.7581544 THEN  IF (wavelethll_glszm_largearealowgra=.) OR 
  wavelethll_glszm_largearealowgra < 27360.758 THEN 0.388134970449656 ELSE 0.365248813803503 ELSE 0.0212875420398903 ELSE 0.0147812413563631 ELSE IF 
  (v455_fc=.) OR v455_fc < 0.06063094 THEN 0.0199403128253421 ELSE -0.0419376049654909 ELSE -0.00046483256621681) + ( IF (original_firstorder_minimum_fc=.) OR 
  original_firstorder_minimum_fc < 10 THEN 0.00174187210852736 ELSE IF (v810_mm=.) OR v810_mm < 0.31608131 THEN  IF (waveletlll_glcm_idn_fc=.) OR 
  waveletlll_glcm_idn_fc < 0.93950349 THEN 0.00978522758789321 ELSE IF (waveletlll_glcm_idn_fc=.) OR waveletlll_glcm_idn_fc < 
  0.94355341 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 14 THEN  IF (original_firstorder_minimum_fc=.) OR 
  original_firstorder_minimum_fc < 13 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 12 THEN 
  -0.37565793728173 ELSE -0.393455241738241 ELSE -0.370334199423318 ELSE -0.00743136016904836 ELSE -0.000172307915883427 ELSE 
  0.0212142407203037) + ( IF (v620_fc=.) OR v620_fc < 0.46122497 THEN 0.0147441454866142 ELSE IF (wavelethlh_glszm_largeareahighgr=.) OR 
  wavelethlh_glszm_largeareahighgr < 21709228 THEN  IF (wavelethhh_glcm_clustershade_mm=.) OR wavelethhh_glcm_clustershade_mm < 
  -0.0038413 THEN 0.406716754549852 ELSE IF (waveletllh_glszm_zoneentropy_fc=.) OR waveletllh_glszm_zoneentropy_fc < 5.8117325 THEN 
  -0.0112577734569956 ELSE IF (waveletllh_gldm_smalldependencel=.) OR waveletllh_gldm_smalldependencel < 0.00198516 THEN  IF 
  (wavelethhh_glrlm_runvariance_mm=.) OR wavelethhh_glrlm_runvariance_mm < 1.2957695 THEN  IF (wavelethll_glszm_largearealowgra=.) OR 
  wavelethll_glszm_largearealowgra < 18079.034 THEN -0.0612940177633301 ELSE -0.404608904545514 ELSE -0.0375178210258797 ELSE 
  0.0532587316002023 ELSE 0.0814697920505207) + ( IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  3 THEN  IF (waveletlll_glcm_idn_fc=.) OR waveletlll_glcm_idn_fc < 0.94055986 THEN  IF (original_firstorder_minimum_fc=.) OR 
  original_firstorder_minimum_fc < 1 THEN 0.0246212895346309 ELSE 0.0454365994829657 ELSE IF (original_firstorder_minimum_fc=.) OR 
  original_firstorder_minimum_fc < 1 THEN -0.03438759335182 ELSE IF (waveletlhl_glszm_zoneentropy_mm=.) OR waveletlhl_glszm_zoneentropy_mm < 
  5.8889997 THEN -0.00698079082414862 ELSE -0.345192547368939 ELSE IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  10 THEN 0.0034479511377816 ELSE IF (v810_mm=.) OR v810_mm < 0.33293237 THEN -0.0179725346521199 ELSE 0.0480319435860204) + 
  ( IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 10 THEN 0.00236555827460428 ELSE IF (v810_mm=.) OR 
  v810_mm < 0.33293237 THEN  IF (waveletlhl_glcm_clustershade_fc=.) OR waveletlhl_glcm_clustershade_fc < -4.499647 THEN -0.14111585560219 ELSE 
  -0.002833553076789 ELSE IF (original_shape_elongation_lm=.) OR original_shape_elongation_lm < 0.54951699 THEN  IF (wavelethhl_gldm_smalldependencel=.) OR 
  wavelethhl_gldm_smalldependencel < 0.00243669 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  13 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 12 THEN 0.381995150131941 ELSE 0.382606112120728 ELSE 
  0.0911995679509512 ELSE 0.00482289842929699 ELSE -0.0654899824113448) + ( IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  10 THEN 0.00300741730100996 ELSE IF (v810_mm=.) OR v810_mm < 0.33188543 THEN  IF (waveletlhl_glcm_clustershade_fc=.) OR waveletlhl_glcm_clustershade_fc < 
  -4.499647 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 13 THEN -0.382711545172887 ELSE 
  -0.0948648576885265 ELSE -0.00362026978317577 ELSE IF (waveletllh_glcm_imc1_mm=.) OR waveletllh_glcm_imc1_mm < -0.05587645 THEN 
   IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 12 THEN 0.359948471810413 ELSE IF (original_firstorder_minimum_fc=.) OR 
  original_firstorder_minimum_fc < 13 THEN 0.375458687008464 ELSE 0.359946729682603 ELSE 0.00188937761075038) + ( IF (original_firstorder_minimum_fc=.) OR 
  original_firstorder_minimum_fc < 10 THEN 0.00618535254666699 ELSE IF (wavelethll_glszm_graylevelnonuni=.) OR wavelethll_glszm_graylevelnonuni < 
  826.82604 THEN  IF (v810_mm=.) OR v810_mm < 0.33137519 THEN 0.00114983450744445 ELSE IF (wavelethlh_firstorder_median_lm=.) OR 
  wavelethlh_firstorder_median_lm < 0.00052469 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  12 THEN 0.40221475653378 ELSE 0.400241172330654 ELSE 0.0430201555252073 ELSE IF (waveletlhl_firstorder_skewness_f=.) OR waveletlhl_firstorder_skewness_f < 
  -0.22590574 THEN  IF (waveletlhh_firstorder_median_lm=.) OR waveletlhh_firstorder_median_lm < -0.08607838 THEN -0.0169206328195082 ELSE 
  -0.207516301878977 ELSE 0.0795152332894677) + ( IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  14 THEN -0.00087055350627775 ELSE IF (original_shape_elongation_lm=.) OR original_shape_elongation_lm < 0.49878295 THEN  IF 
  (waveletlhh_glszm_smallareaemphas=.) OR waveletlhh_glszm_smallareaemphas < 0.55455868 THEN 0.0145600582802572 ELSE 0.365250144722241 ELSE IF 
  (waveletllh_glcm_imc1_mm=.) OR waveletllh_glcm_imc1_mm < -0.0515193 THEN  IF (wavelethhl_gldm_smalldependencel=.) OR wavelethhl_gldm_smalldependencel < 
  0.00243816 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 15 THEN 0.0412739269700955 ELSE IF 
  (waveletlll_glcm_idn_fc=.) OR waveletlll_glcm_idn_fc < 0.9416236 THEN -0.372350973277702 ELSE -0.0178925352613912 ELSE 0.37247892912155 ELSE 
  -0.360026273433538) + ( IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 14 THEN 0.00168004694679016 ELSE IF 
  (waveletllh_glcm_imc1_mm=.) OR waveletllh_glcm_imc1_mm < -0.0515193 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  16 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 15 THEN  IF (wavelethhl_gldm_smalldependence2=.) OR 
  wavelethhl_gldm_smalldependence2 < 0.00260437 THEN 0.00490441410345091 ELSE IF (wavelethll_firstorder_kurtosis_m=.) OR wavelethll_firstorder_kurtosis_m < 
  4.7166448 THEN 0.377510587221285 ELSE 0.361412897839815 ELSE 0.0688227036188183 ELSE -0.00294447710714348 ELSE IF (waveletllh_glcm_correlation_mm=.) OR 
  waveletllh_glcm_correlation_mm < 0.06797899 THEN 0.000889706152899339 ELSE -0.37772035507778) + ( IF (original_firstorder_minimum_fc=.) OR 
  original_firstorder_minimum_fc < 14 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 13 THEN 
  0.000925615881527692 ELSE IF (wavelethhl_glcm_imc1_mm=.) OR wavelethhl_glcm_imc1_mm < -0.01539957 THEN 0.0751640658128034 ELSE IF 
  (wavelethll_glszm_largearealowgra=.) OR wavelethll_glszm_largearealowgra < 33171.017 THEN -0.393324795207653 ELSE -0.072717406285223 ELSE IF 
  (wavelethll_firstorder_kurtosis_m=.) OR wavelethll_firstorder_kurtosis_m < 4.000707 THEN -0.34156763516773 ELSE IF (original_shape_elongation_lm=.) OR 
  original_shape_elongation_lm < 0.49878295 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  16 THEN 0.352707956887192 ELSE 0.353945208815983 ELSE 0.000896985552572391) + ( IF (original_firstorder_minimum_fc=.) OR 
  original_firstorder_minimum_fc < 16 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 14 THEN 
  -0.00145380618621195 ELSE IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 15 THEN  IF (wavelethhl_glszm_graylevelvarian=.) OR 
  wavelethhl_glszm_graylevelvarian < 2.2230999 THEN  IF (wavelethhh_glcm_imc1_lm=.) OR wavelethhh_glcm_imc1_lm < -0.00741314 THEN 
  0.338954621047443 ELSE 0.353856550408411 ELSE -0.0288000818849363 ELSE 0.00563003812513416 ELSE IF (waveletlll_glcm_idn_fc=.) OR 
  waveletlll_glcm_idn_fc < 0.93613481 THEN 0.0462246929766065 ELSE IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  18 THEN -0.0994002730288651 ELSE -0.0105911566732285) + ( IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  16 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 14 THEN -0.00135785497788051 ELSE IF (
  original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 15 THEN  IF (waveletllh_glcm_correlation_mm=.) OR waveletllh_glcm_correlation_mm < 
  0.08677828 THEN -0.0512881713128885 ELSE 0.0849111635613147 ELSE IF (original_glszm_smallareaemphasis=.) OR original_glszm_smallareaemphasis < 
  0.59270329 THEN -0.0814772663143766 ELSE 0.0745321124899136 ELSE IF (waveletlll_glcm_idn_fc=.) OR waveletlll_glcm_idn_fc < 
  0.93613481 THEN 0.0431738624683694 ELSE IF (waveletllh_firstorder_minimum_fc=.) OR waveletllh_firstorder_minimum_fc < -235.16487 THEN 
  -0.350324915200028 ELSE 0.029574171918915) + ( IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  16 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 14 THEN 0.00133518508835272 ELSE IF (waveletllh_glcm_imc1_mm=.) OR 
  waveletllh_glcm_imc1_mm < -0.0515193 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 15 THEN 
   IF (wavelethhh_glrlm_runvariance_mm=.) OR wavelethhh_glrlm_runvariance_mm < 1.3024643 THEN 0.403315459864289 ELSE 0.00837410187135484 ELSE 
  0.0747233557980664 ELSE -0.135780670472731 ELSE IF (wavelethll_firstorder_kurtosis_m=.) OR wavelethll_firstorder_kurtosis_m < 
  4.2417557 THEN -0.392807541368579 ELSE IF (waveletllh_gldm_smalldependencel=.) OR waveletllh_gldm_smalldependencel < 0.00084059 THEN 
  -0.094140921161159 ELSE 0.137860426491398) + ( IF (wavelethlh_glszm_largeareahighgr=.) OR wavelethlh_glszm_largeareahighgr < 
  21028651 THEN  IF (wavelethhl_firstorder_mean_mm=.) OR wavelethhl_firstorder_mean_mm < 0.10638043 THEN -0.0366915640215995 ELSE 
  0.0129671920671726 ELSE IF (wavelethhl_gldm_smalldependencel=.) OR wavelethhl_gldm_smalldependencel < 0.00170829 THEN  IF 
  (wavelethhl_glcm_imc1_tc=.) OR wavelethhl_glcm_imc1_tc < -0.01718607 THEN  IF (wavelethhl_glrlm_longrunhighgray=.) OR wavelethhl_glrlm_longrunhighgray < 
  31.122117 THEN -0.403163471850495 ELSE 0.0166194202586265 ELSE 0.148235362523368 ELSE IF (original_firstorder_minimum_fc=.) OR 
  original_firstorder_minimum_fc < 8 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 6 THEN 
  0.402236233034788 ELSE 0.102861795265484 ELSE 0.403763200165836) + ( IF (waveletlhh_firstorder_median_lm=.) OR waveletlhh_firstorder_median_lm < 
  -0.07088577 THEN 0.015734387191745 ELSE IF (v455_fc=.) OR v455_fc < 0.05989707 THEN 0.0143030870017431 ELSE IF (v810_mm=.) OR 
  v810_mm < 0.31636439 THEN  IF (waveletlhl_glszm_zoneentropy_mm=.) OR waveletlhl_glszm_zoneentropy_mm < 5.5645628 THEN 0.00980511463930873 ELSE IF 
  (waveletllh_firstorder_minimum_fc=.) OR waveletllh_firstorder_minimum_fc < -272.64744 THEN -0.0049766255825341 ELSE IF (v620_fc=.) OR 
  v620_fc < 0.48244004 THEN  IF (wavelethll_ngtdm_busyness_mm=.) OR wavelethll_ngtdm_busyness_mm < 83.153587 THEN -0.397947815033261 ELSE 
  -0.0943366775155592 ELSE 0.024595613073332 ELSE 0.005672626262773) + ( IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  7 THEN -0.00322838834920264 ELSE IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 16 THEN  IF (original_firstorder_minimum_fc=.) OR 
  original_firstorder_minimum_fc < 14 THEN 0.00181769315283161 ELSE IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  15 THEN  IF (wavelethhl_glszm_graylevelvarian=.) OR wavelethhl_glszm_graylevelvarian < 2.2230999 THEN 0.34224929771282 ELSE 
  -0.0260363177307346 ELSE 0.00534890316731862 ELSE IF (original_shape_elongation_lm=.) OR original_shape_elongation_lm < 0.49878295 THEN 
  0.05167979436581 ELSE IF (wavelethhl_gldm_smalldependencel=.) OR wavelethhl_gldm_smalldependencel < 0.0021827 THEN -0.346177230227182 ELSE 
  0.0359857849790258) + ( IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 10 THEN 0.00220943142820656 ELSE IF 
  (waveletlhl_firstorder_skewness_f=.) OR waveletlhl_firstorder_skewness_f < -0.22590574 THEN  IF (wavelethll_glszm_graylevelnonuni=.) OR 
  wavelethll_glszm_graylevelnonuni < 864.76939 THEN 0.00928381252439036 ELSE IF (waveletllh_glcm_correlation_mm=.) OR waveletllh_glcm_correlation_mm < 
  0.0932493 THEN -0.0176383792261176 ELSE -0.177824511296836 ELSE IF (wavelethhl_glcm_imc1_mm=.) OR wavelethhl_glcm_imc1_mm < 
  -0.01637026 THEN -0.0413365183245398 ELSE IF (wavelethhl_gldm_smalldependence2=.) OR wavelethhl_gldm_smalldependence2 < 0.00411718 THEN 
   IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 12 THEN 0.39149944753218 ELSE 0.380992920337935 ELSE 
  0.0417692531869457) + ( IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 10 THEN 0.00280892775883182 ELSE IF 
  (original_shape_elongation_lm=.) OR original_shape_elongation_lm < 0.53867045 THEN 0.00779513516507897 ELSE IF (wavelethhl_glcm_imc1_mm=.) OR 
  wavelethhl_glcm_imc1_mm < -0.01607211 THEN  IF (waveletlll_glcm_clustershade_lm=.) OR waveletlll_glcm_clustershade_lm < 156.88672 THEN 
  -0.0172353781076651 ELSE IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 12 THEN -0.383731544364206 ELSE 
  -0.38008407898817 ELSE IF (waveletlhl_firstorder_skewness_t=.) OR waveletlhl_firstorder_skewness_t < 0.07220243 THEN  IF 
  (waveletllh_glcm_imc1_mm=.) OR waveletllh_glcm_imc1_mm < -0.05272139 THEN 0.379035924632305 ELSE -0.0255608129025289 ELSE 
  -0.0582973227757924) + ( IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 10 THEN 0.00577711927916612 ELSE IF 
  (original_shape_elongation_lm=.) OR original_shape_elongation_lm < 0.52739427 THEN 0.0187123091441536 ELSE IF (waveletlhh_firstorder_median_lm=.) OR 
  waveletlhh_firstorder_median_lm < -0.13526909 THEN 0.0330880407152966 ELSE IF (wavelethll_firstorder_skewness_l=.) OR wavelethll_firstorder_skewness_l < 
  0.07956173 THEN  IF (waveletlhl_glszm_zoneentropy_lm=.) OR waveletlhl_glszm_zoneentropy_lm < 5.8028362 THEN -0.0239519543589087 ELSE IF 
  (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 11 THEN -0.395645083840603 ELSE IF (original_firstorder_minimum_fc=.) OR 
  original_firstorder_minimum_fc < 13 THEN -0.154463496053723 ELSE -0.392245975870294 ELSE 0.0392561691262235) + ( IF (original_firstorder_minimum_fc=.) OR 
  original_firstorder_minimum_fc < 11 THEN 0.00234883907286691 ELSE IF (original_shape_elongation_lm=.) OR original_shape_elongation_lm < 
  0.54474267 THEN  IF (waveletllh_glcm_correlation_mm=.) OR waveletllh_glcm_correlation_mm < 0.08166778 THEN  IF (waveletllh_glcm_correlation_mm=.) OR 
  waveletllh_glcm_correlation_mm < 0.0643739 THEN -0.0371849077216552 ELSE 0.0699085467947098 ELSE -0.0176882160454802 ELSE IF 
  (wavelethhl_glcm_imc1_mm=.) OR wavelethhl_glcm_imc1_mm < -0.01531122 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  13 THEN -0.377280508151407 ELSE -0.363434890861503 ELSE IF (wavelethlh_glszm_largeareahighgr=.) OR wavelethlh_glszm_largeareahighgr < 
  9321272.5 THEN 0.144729625682554 ELSE -0.0596883359944275) + ( IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  14 THEN 0.00179876546756159 ELSE IF (wavelethll_firstorder_kurtosis_m=.) OR wavelethll_firstorder_kurtosis_m < 4.000707 THEN 
  -0.366527376077757 ELSE IF (wavelethll_ngtdm_busyness_mm=.) OR wavelethll_ngtdm_busyness_mm < 81.168357 THEN  IF (wavelethhl_glcm_clusterprominenc=.) OR 
  wavelethhl_glcm_clusterprominenc < 1.7872414 THEN  IF (waveletlhh_glszm_smallareaemphas=.) OR waveletlhh_glszm_smallareaemphas < 
  0.56691117 THEN -0.389765280842322 ELSE -0.00371154708487298 ELSE 0.0965157438143979 ELSE IF (wavelethhl_glcm_correlation_mm=.) OR 
  wavelethhl_glcm_correlation_mm < 0.00400129 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  15 THEN 0.385723569748352 ELSE 0.395995762678344 ELSE 0.0284378829212168) + ( IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 
  7 THEN -0.0034565185776026 ELSE IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 13 THEN 0.00308277019941021 ELSE IF 
  (wavelethhl_gldm_smalldependence2=.) OR wavelethhl_gldm_smalldependence2 < 0.0042021 THEN  IF (wavelethhh_glcm_imc1_lm=.) OR 
  wavelethhh_glcm_imc1_lm < -0.00662237 THEN  IF (v455_fc=.) OR v455_fc < 0.06277331 THEN 0.045107296384183 ELSE -0.348187260929437 ELSE 
  -0.0687009846749421 ELSE IF (wavelethhl_glcm_imc1_mm=.) OR wavelethhl_glcm_imc1_mm < -0.01589438 THEN 0.0254531074193634 ELSE IF 
  (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 14 THEN -0.364447981919914 ELSE -0.0706688185640408) + 
  ( IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 14 THEN -0.0000484733759211898 ELSE IF (wavelethll_firstorder_kurtosis_m=.) OR 
  wavelethll_firstorder_kurtosis_m < 4.000707 THEN -0.353926250396313 ELSE IF (original_shape_elongation_lm=.) OR original_shape_elongation_lm < 
  0.49878295 THEN  IF (original_firstorder_minimum_fc=.) OR original_firstorder_minimum_fc < 16 THEN 0.37220192715602 ELSE 
  0.381728512636891 ELSE IF (wavelethll_ngtdm_busyness_mm=.) OR wavelethll_ngtdm_busyness_mm < 81.168357 THEN  IF (wavelethhh_firstorder_minimum_fc=.) OR 
  wavelethhh_firstorder_minimum_fc < -55.943774 THEN 0.0255046509370741 ELSE -0.128485450851045 ELSE IF (waveletlll_glcm_clustershade_lm=.) OR 
  waveletlll_glcm_clustershade_lm < 199.68613 THEN 0.373360258351516 ELSE -0.015185611893372))))));
Prob_itype1_Case_Prob_itype1_ = 
  1 + -1*Prob_itype1_Control_;
val_max = 1 + -1*Prob_itype1_Control_;
IF (not missing(val_max) AND (missing(acc_max) OR val_max > acc_max)) THEN DO;
  idx_max = 1;
  acc_max = val_max;
END;
val_max = Prob_itype1_Control_;
IF (not missing(val_max) AND (missing(acc_max) OR val_max > acc_max)) THEN DO;
  idx_max = 2;
  acc_max = val_max;
END;

Most_Likely_itype1_Most_Likely_ = 
 SELECT (idx_max)
  WHEN (1) 'Case'
  WHEN (2) 'Control'
  OTHERWISE ''
 END
;
