"use strict";

var jmp = require('./jmp_score.js');


/* ==================================================================
 Copyright(C) 2018 SAS Institute Inc.All rights reserved.
 
 Notice:
 The following permissions are granted provided that the
 above copyright and this notice appear in the score code and
 any related documentation. Permission to copy, modify
 and distribute the score code generated using
 JMP(R) software is limited to customers of SAS Institute Inc. ("SAS")
 and successive third parties, all without any warranty, express or
 implied, or any other obligation by SAS. SAS and all other SAS
 Institute Inc. product and service names are registered
 trademarks or trademarks of SAS Institute Inc. in the USA
 and other countries. Except as contained in this notice,
 the name of the SAS Institute Inc. and JMP shall not be used in
 the advertising or promotion of products or services without
 prior written authorization from SAS Institute Inc.
 ================================================================== */

/* JavaScript code generated by JMP v16.2.0 */
var getModelMetadata = function() {
	return {"creator": "Fit Nominal Logistic", "modelName": "", "predicted": "itype1", "table": "final-2022-11-18", "version": "16.2.0", "timestamp": "2023-02-13T04:53:01Z"};
};

var getInputMetadata = function() {
    return {
   "$schema": "http://json-schema.org/draft-04/schema#",
   "id": "/",
   "type": "object",
   "properties": {
     "v810_mm": {
       "id": "v810_mm",
       "type": "number"
     },
     "wavelethhl_glcm_correlation_mm": {
       "id": "wavelethhl_glcm_correlation_mm",
       "type": "number"
     },
     "wavelethhl_glcm_imc1_tc": {
       "id": "wavelethhl_glcm_imc1_tc",
       "type": "number"
     },
     "wavelethhl_gldm_smalldependencel_mm": {
       "id": "wavelethhl_gldm_smalldependencel_mm",
       "type": "number"
     },
     "wavelethhl_glrlm_longrunhighgray_mm": {
       "id": "wavelethhl_glrlm_longrunhighgray_mm",
       "type": "number"
     },
     "wavelethhl_glszm_graylevelvarian_mm": {
       "id": "wavelethhl_glszm_graylevelvarian_mm",
       "type": "number"
     },
     "wavelethhl_glszm_smallareaemphas_fc": {
       "id": "wavelethhl_glszm_smallareaemphas_fc",
       "type": "number"
     },
     "wavelethlh_firstorder_median_lm": {
       "id": "wavelethlh_firstorder_median_lm",
       "type": "number"
     },
     "wavelethlh_glszm_largeareahighgr_tc": {
       "id": "wavelethlh_glszm_largeareahighgr_tc",
       "type": "number"
     },
     "wavelethlh_glszm_zoneentropy_tc": {
       "id": "wavelethlh_glszm_zoneentropy_tc",
       "type": "number"
     },
     "wavelethll_firstorder_skewness_lm": {
       "id": "wavelethll_firstorder_skewness_lm",
       "type": "number"
     },
     "waveletlhh_firstorder_median_lm": {
       "id": "waveletlhh_firstorder_median_lm",
       "type": "number"
     },
     "waveletlhl_firstorder_skewness_tc": {
       "id": "waveletlhl_firstorder_skewness_tc",
       "type": "number"
     },
     "waveletlhl_glszm_zoneentropy_lm": {
       "id": "waveletlhl_glszm_zoneentropy_lm",
       "type": "number"
     },
     "waveletlll_glcm_clustershade_lm": {
       "id": "waveletlll_glcm_clustershade_lm",
       "type": "number"
     },
     "waveletlll_glcm_idn_fc": {
       "id": "waveletlll_glcm_idn_fc",
       "type": "number"
     },
     "Prob[Control]": {
       "id": "Prob[Control]",
       "type": "number"
     },
     "Prob[Case]": {
       "id": "Prob[Case]",
       "type": "number"
     }   },
   "additionalProperties": false,
  };
};

var getOutputMetadata = function() {
    return {
   "$schema": "http://json-schema.org/draft-04/schema#",
   "id": "/",
   "type": "object",
   "properties": {
     "Prob[Control],!Prob[Control]": {
       "id": "Prob[Control],!Prob[Control]",
       "type": "number"
     },
     "Prob[Case],!Prob[Case]": {
       "id": "Prob[Case],!Prob[Case]",
       "type": "number"
     },
     "Most Likely itype1,!Most Likely itype1": {
       "id": "Most Likely itype1,!Most Likely itype1",
       "type": "string"
     }   },
   "additionalProperties": false,
  };
};

var score = function(indata, outdata) {
    // Original name was: 'Lin[Control]_1'
    var Lin_Control__1;
    var _temp_0;
    var _temp_1 = [];
    var _temp_2 = "";

    Lin_Control__1 = 67.8225584206322 + 17.9139066181218 * indata["v810_mm"] + -44.4484024147687 * indata["wavelethhl_glcm_correlation_mm"] + 37.1611631286306 * indata["wavelethhl_glcm_imc1_tc"] + -543.08691361572 * indata["wavelethhl_gldm_smalldependencel_mm"] + -0.0605076619251482 * indata["wavelethhl_glrlm_longrunhighgray_mm"] + 4.23079348309421 * indata["wavelethhl_glszm_graylevelvarian_mm"] + -17.427377971716 * indata["wavelethhl_glszm_smallareaemphas_fc"] + -3.3401829838497 * indata["wavelethlh_firstorder_median_lm"] + 0.0000000600668512722 * indata["wavelethlh_glszm_largeareahighgr_tc"] + -1.00398340579847 * indata["wavelethlh_glszm_zoneentropy_tc"] + 1.25412905444842 * indata["wavelethll_firstorder_skewness_lm"] + -1.35301244832444 * indata["waveletlhh_firstorder_median_lm"] + -2.49611308125717 * indata["waveletlhl_firstorder_skewness_tc"] + -1.29104858312071 * indata["waveletlhl_glszm_zoneentropy_lm"] + 0.00279307501761915 * indata["waveletlll_glcm_clustershade_lm"] + -59.8246992075537 * indata["waveletlll_glcm_idn_fc"];

    outdata["Prob[Control],!Prob[Control]"] = 1 / (1 + Math.exp(-(Lin_Control__1)));

    outdata["Prob[Case],!Prob[Case]"] = 1 / (1 + Math.exp(Lin_Control__1));

    _temp_1[0] = indata["Prob[Control]"];
    _temp_1[1] = indata["Prob[Case]"];
    _temp_0 = jmp.max_array(2, _temp_1);
    switch (_temp_0) {
        case 0: {
            _temp_2 = "Control";
        }
        break;
        case 1: {
            _temp_2 = "Case";
        }
        break;
        default: {
            _temp_2 = "";
        }
    }
    outdata["Most Likely itype1,!Most Likely itype1"] = _temp_2;

    return outdata["Most Likely itype1,!Most Likely itype1"];
};


module.exports = {
  getInputMetadata: getInputMetadata,
  getOutputMetadata : getOutputMetadata,
  getModelMetadata : getModelMetadata,
  score : score
};



