from __future__ import division
import jmp_score as jmp
from math import *
import numpy as np


""" ==================================================================
 Copyright(C) 2018 SAS Institute Inc.All rights reserved.
 
 Notice:
 The following permissions are granted provided that the
 above copyright and this notice appear in the score code and
 any related documentation. Permission to copy, modify
 and distribute the score code generated using
 JMP(R) software is limited to customers of SAS Institute Inc. ("SAS")
 and successive third parties, all without any warranty, express or
 implied, or any other obligation by SAS. SAS and all other SAS
 Institute Inc. product and service names are registered
 trademarks or trademarks of SAS Institute Inc. in the USA
 and other countries. Except as contained in this notice,
 the name of the SAS Institute Inc. and JMP shall not be used in
 the advertising or promotion of products or services without
 prior written authorization from SAS Institute Inc.
 ================================================================== """

""" Python code generated by JMP v16.2.0 """

def getModelMetadata():
	return {"creator": u"Fit Nominal Logistic", "modelName": u"", "predicted": u"itype1", "table": u"final-2022-11-18", "version": u"16.2.0", "timestamp": u"2023-02-13T04:52:51Z"}


def getInputMetadata():
    return {
        u"v810_mm": "float",
        u"wavelethhl_glcm_correlation_mm": "float",
        u"wavelethhl_glcm_imc1_tc": "float",
        u"wavelethhl_gldm_smalldependencel_mm": "float",
        u"wavelethhl_glrlm_longrunhighgray_mm": "float",
        u"wavelethhl_glszm_graylevelvarian_mm": "float",
        u"wavelethhl_glszm_smallareaemphas_fc": "float",
        u"wavelethlh_firstorder_median_lm": "float",
        u"wavelethlh_glszm_largeareahighgr_tc": "float",
        u"wavelethlh_glszm_zoneentropy_tc": "float",
        u"wavelethll_firstorder_skewness_lm": "float",
        u"waveletlhh_firstorder_median_lm": "float",
        u"waveletlhl_firstorder_skewness_tc": "float",
        u"waveletlhl_glszm_zoneentropy_lm": "float",
        u"waveletlll_glcm_clustershade_lm": "float",
        u"waveletlll_glcm_idn_fc": "float",
        u"Prob[Control]": "float",
        u"Prob[Case]": "float"
	}


def getOutputMetadata():
    return {
        u"Prob[Control],!Prob[Control]": "float",
        u"Prob[Case],!Prob[Case]": "float",
        u"Most Likely itype1,!Most Likely itype1": "str"
	}


def score(indata, outdata):
    # Original name was: 'Lin[Control]_1'

    _temp_1 = [0 for i in range(2)]
    _temp_2 = u""

    Lin_Control__1 = 67.8225584206322 + 17.9139066181218 * indata[u"v810_mm"] + -44.4484024147687 * indata[u"wavelethhl_glcm_correlation_mm"] + 37.1611631286306 * indata[u"wavelethhl_glcm_imc1_tc"] + -543.08691361572 * indata[u"wavelethhl_gldm_smalldependencel_mm"] + -0.0605076619251482 * indata[u"wavelethhl_glrlm_longrunhighgray_mm"] + 4.23079348309421 * indata[u"wavelethhl_glszm_graylevelvarian_mm"] + -17.427377971716 * indata[u"wavelethhl_glszm_smallareaemphas_fc"] + -3.3401829838497 * indata[u"wavelethlh_firstorder_median_lm"] + 0.0000000600668512722 * indata[u"wavelethlh_glszm_largeareahighgr_tc"] + -1.00398340579847 * indata[u"wavelethlh_glszm_zoneentropy_tc"] + 1.25412905444842 * indata[u"wavelethll_firstorder_skewness_lm"] + -1.35301244832444 * indata[u"waveletlhh_firstorder_median_lm"] + -2.49611308125717 * indata[u"waveletlhl_firstorder_skewness_tc"] + -1.29104858312071 * indata[u"waveletlhl_glszm_zoneentropy_lm"] + 0.00279307501761915 * indata[u"waveletlll_glcm_clustershade_lm"] + -59.8246992075537 * indata[u"waveletlll_glcm_idn_fc"]

    outdata[u"Prob[Control],!Prob[Control]"] = 1 / (1 + jmp.exp(-(Lin_Control__1)))

    outdata[u"Prob[Case],!Prob[Case]"] = 1 / (1 + jmp.exp(Lin_Control__1))

    _temp_1[0] = indata[u"Prob[Control]"]
    _temp_1[1] = indata[u"Prob[Case]"]
    _temp_0 = jmp.max_array(2, _temp_1)
    if jmp.mz(_temp_0 == 0):
        _temp_2 = u"Control"
    elif jmp.mz(_temp_0 == 1):
        _temp_2 = u"Case"
    else:
        _temp_2 = u""
    outdata[u"Most Likely itype1,!Most Likely itype1"] = _temp_2

    return outdata[u"Most Likely itype1,!Most Likely itype1"]


