/* 
 * SAS code generated by JMP v16.2.0
 * From the following model(s): 
 *   K Nearest Neighbors - itype1
 * Variable name mapping: 
 *   Predicted Formula itype1 4,!Predicted Formula itype1 4 => Predicted_Formula_itype1_4_Pred
 *   original_firstorder_minimum_fc => original_firstorder_minimum_fc
 *   original_glszm_smallareaemphasis_fc => original_glszm_smallareaemphasis
 *   original_shape_elongation_lm => original_shape_elongation_lm
 *   original_shape_sphericity_mm => original_shape_sphericity_mm
 *   v455_fc => v455_fc
 *   v620_fc => v620_fc
 *   v810_mm => v810_mm
 *   wavelethhh_firstorder_minimum_fc => wavelethhh_firstorder_minimum_fc
 *   wavelethhh_glcm_clustershade_mm => wavelethhh_glcm_clustershade_mm
 *   wavelethhh_glcm_imc1_lm => wavelethhh_glcm_imc1_lm
 *   wavelethhh_glrlm_runvariance_mm => wavelethhh_glrlm_runvariance_mm
 *   wavelethhh_glszm_largeareahighgr_fc => wavelethhh_glszm_largeareahighgr
 *   wavelethhl_firstorder_mean_mm => wavelethhl_firstorder_mean_mm
 *   wavelethhl_glcm_clusterprominenc_fc => wavelethhl_glcm_clusterprominenc
 *   wavelethhl_glcm_correlation_mm => wavelethhl_glcm_correlation_mm
 *   wavelethhl_glcm_imc1_mm => wavelethhl_glcm_imc1_mm
 *   wavelethhl_glcm_imc1_tc => wavelethhl_glcm_imc1_tc
 *   wavelethhl_gldm_smalldependencel_fc => wavelethhl_gldm_smalldependencel
 *   wavelethhl_gldm_smalldependencel_mm => wavelethhl_gldm_smalldependence2
 *   wavelethhl_glrlm_longrunhighgray_mm => wavelethhl_glrlm_longrunhighgray
 *   wavelethhl_glszm_graylevelvarian_mm => wavelethhl_glszm_graylevelvarian
 *   wavelethhl_glszm_largearealowgra_fc => wavelethhl_glszm_largearealowgra
 *   wavelethhl_glszm_smallareaemphas_fc => wavelethhl_glszm_smallareaemphas
 *   wavelethlh_firstorder_median_lm => wavelethlh_firstorder_median_lm
 *   wavelethlh_glszm_largeareahighgr_tc => wavelethlh_glszm_largeareahighgr
 *   wavelethlh_glszm_zoneentropy_tc => wavelethlh_glszm_zoneentropy_tc
 *   wavelethll_firstorder_kurtosis_mm => wavelethll_firstorder_kurtosis_m
 *   wavelethll_firstorder_skewness_lm => wavelethll_firstorder_skewness_l
 *   wavelethll_glszm_graylevelnonuni_fc => wavelethll_glszm_graylevelnonuni
 *   wavelethll_glszm_largearealowgra_lm => wavelethll_glszm_largearealowgra
 *   wavelethll_glszm_smallareaemphas_fc => wavelethll_glszm_smallareaemphas
 *   wavelethll_ngtdm_busyness_mm => wavelethll_ngtdm_busyness_mm
 *   waveletlhh_firstorder_maximum_mm => waveletlhh_firstorder_maximum_mm
 *   waveletlhh_firstorder_median_lm => waveletlhh_firstorder_median_lm
 *   waveletlhh_glszm_smallareaemphas_mm => waveletlhh_glszm_smallareaemphas
 *   waveletlhl_firstorder_minimum_tc => waveletlhl_firstorder_minimum_tc
 *   waveletlhl_firstorder_skewness_fc => waveletlhl_firstorder_skewness_f
 *   waveletlhl_firstorder_skewness_tc => waveletlhl_firstorder_skewness_t
 *   waveletlhl_glcm_clustershade_fc => waveletlhl_glcm_clustershade_fc
 *   waveletlhl_glszm_zoneentropy_lm => waveletlhl_glszm_zoneentropy_lm
 *   waveletlhl_glszm_zoneentropy_mm => waveletlhl_glszm_zoneentropy_mm
 *   waveletllh_firstorder_minimum_fc => waveletllh_firstorder_minimum_fc
 *   waveletllh_glcm_correlation_mm => waveletllh_glcm_correlation_mm
 *   waveletllh_glcm_imc1_mm => waveletllh_glcm_imc1_mm
 *   waveletllh_gldm_smalldependencel_mm => waveletllh_gldm_smalldependencel
 *   waveletllh_glszm_zoneentropy_fc => waveletllh_glszm_zoneentropy_fc
 *   waveletlll_glcm_clustershade_lm => waveletlll_glcm_clustershade_lm
 *   waveletlll_glcm_idn_fc => waveletlll_glcm_idn_fc
 *   waveletlll_gldm_largedependenceh_lm => waveletlll_gldm_largedependenceh
 *   waveletlll_glszm_graylevelnonuni_fc => waveletlll_glszm_graylevelnonuni
 *   waveletlll_glszm_graylevelvarian_mm => waveletlll_glszm_graylevelvarian
 *   waveletlll_ngtdm_busyness_tc => waveletlll_ngtdm_busyness_tc
 */


Predicted_Formula_itype1_4_Pred = Unhandled operator: List[];
